name: Deploy (Triggered by Release Manifest)

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: 'Environment to deploy to'
        options:
          - development
          - qa1
          - qa2
          - qa3
          - qa4
          - qa5
          - staging
          - production
      ref_to_build:
        required: true
        type: string
        description: 'Git ref (tag) to deploy'

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: ${{ inputs.environment }}
      ref_to_build: ${{ inputs.ref_to_build }}
    secrets: inherit
