import dotenv from "dotenv";
import { hostname } from "os";

dotenv.config({
	path: process.env.NODE_ENV === "production" ? ".env" : ".env.local"
});

const parseBool = (str, valueIfEmpty = false) => {
	if (typeof str === "string" && str.length) {
		return str.toLowerCase() === "true";
	}
	return valueIfEmpty;
};

const {
	NODE_ENV,
	CONFIG_APP_PORT,
	CONFIG_HEALTH_CHECK_MODE,
	CONFIG_SERVICE_MODE,
	SUBDOMAIN,
	CONFIG_DB_HOST,
	CONFIG_DB_PORT,
	CONFIG_DB_USER,
	CONFIG_DB_PASSWORD,
	CONFIG_DB_NAME,
	CONFIG_DB_MAX_CONNECTIONS,
	CONFIG_JWT_SECRET_KEY,
	CONFIG_JWT_REFRESH_SECRET_KEY,
	CONFIG_EMAIL_HOST,
	CONFIG_EMAIL_PORT,
	CONFIG_EMAIL_USER,
	CONFIG_EMAIL_PASSWORD,
	CONFIG_CRYPTO_SECRET_KEY,
	CONFIG_CRYPTO_IV,
	CONFIG_FRONTEND_BASE_URL,
	CONFIG_APPLICANT_FRONTEND_BASE_URL,
	CONFIG_WORTH_ADMIN_FRONTEND_BASE_URL,
	CONFIG_CUSTOMER_ADMIN_FRONTEND_BASE_URL,
	CONFIG_FRONTEND_LOCAL_BASE_URLS,
	CONFIG_KAFKA_GROUP_ID,
	CONFIG_KAFKA_BROKERS,
	CONFIG_KAFKA_SSL_ENABLED,
	CONFIG_KAFKA_CLIENT_ID,
	CONFIG_KAFKA_SASL_USERNAME,
	CONFIG_KAFKA_SASL_PASSWORD,
	CONFIG_WORTH_ADMIN_USER_POOL_ID,
	CONFIG_CUSTOMER_USER_POOL_ID,
	CONFIG_APPLICANT_USER_POOL_ID,
	CONFIG_WORTH_ADMIN_CLIENT_ID,
	CONFIG_CUSTOMER_CLIENT_ID,
	CONFIG_APPLICANT_CLIENT_ID,
	CONFIG_AUTH_BASE_URL,
	CONFIG_INTEGRATION_BASE_URL,
	CONFIG_MANUAL_SCORE_BASE_URL,
	CONFIG_STRIPE_SECRET_KEY,
	CONFIG_STRIPE_SUBSCRIPTION_SUCCESS_URL,
	CONFIG_STRIPE_SUBSCRIPTION_CANCEL_URL,
	CONFIG_STRIPE_SUBSCRIPTIONS_WEBHOOK_SECRET,
	CONFIG_REDIS_URL,
	CONFIG_REDIS_HOST,
	CONFIG_REDIS_PORT,
	CONFIG_REDIS_PASSWORD,
	CONFIG_REDIS_EC_CLUSTER,
	CONFIG_REDIS_DISABLE_TLS,
	CONFIG_REDIS_DISABLE_TLS_REJECT_UNAUTHORIZED,
	CONFIG_REDIS_RECONNECT_MAX_WAIT,
	CONFIG_REDIS_KEY_PREFIX,
	CONFIG_EIN_ENCRYPTION_CRYPTO_SECRET_KEY,
	CONFIG_EIN_ENCRYPTION_CRYPTO_IV,
	CONFIG_ENTERPRISE_APPLICANT_ID,
	CONFIG_AWS_BACKEND_BUCKET,
	CONFIG_AWS_ACCESS_KEY_ID,
	CONFIG_AWS_ACCESS_KEY_SECRET,
	CONFIG_AWS_SES_REGION,
	CONFIG_LD_SDK_KEY,
	CONFIG_LD_INTIALIZATION_TIMEOUT,
	CONFIG_LD_TEST_FLAGS_FILE,
	CONFIG_CUSTOM_FIELDS_TEMPLATE,
	CONFIG_LOG_LEVEL,
	CONFIG_REPORT_BASE_URL,
	CONFIG_REPORTS,
	CONFIG_WEBHOOKS,
	CONFIG_INTEGRATIONS,
	CONFIG_NOTIFICATIONS,
	CONFIG_SCORES,
	CONFIG_BUSINESS,
	CONFIG_CASES,
	CONFIG_USERS_NEW,
	CONFIG_DLQTOPIC,
	CONFIG_TIN_VERIFICATION_ATTEMPTS,
	CONFIG_AWS_ELECTRONIC_CONSENT_BUCKET,
	CONFIG_ECONSENT_API_KEY,
	CONFIG_ELECTRONIC_CONSENT_BASE_URL,
	CONFIG_WAREHOUSE_BASE_URL
} = process.env;

export const envConfig = {
	ENV: NODE_ENV,
	HOSTNAME: hostname(),

	APP_PORT: parseFloat(CONFIG_APP_PORT),
	HEALTH_CHECK_MODE: parseBool(CONFIG_HEALTH_CHECK_MODE, false),
	SERVICE_MODE: CONFIG_SERVICE_MODE,
	SUBDOMAIN,
	LOG_LEVEL: CONFIG_LOG_LEVEL,
	DB_HOST: CONFIG_DB_HOST,
	DB_PORT: CONFIG_DB_PORT,
	DB_USER: CONFIG_DB_USER,
	DB_PASSWORD: CONFIG_DB_PASSWORD,
	DB_NAME: CONFIG_DB_NAME,
	DB_MAX_CONNECTIONS: CONFIG_DB_MAX_CONNECTIONS,

	JWT_SECRET_KEY: CONFIG_JWT_SECRET_KEY,
	JWT_REFRESH_SECRET_KEY: CONFIG_JWT_REFRESH_SECRET_KEY,

	EMAIL_PORT: CONFIG_EMAIL_PORT,
	EMAIL_HOST: CONFIG_EMAIL_HOST,
	EMAIL_USER: CONFIG_EMAIL_USER,
	EMAIL_PASSWORD: CONFIG_EMAIL_PASSWORD,

	CRYPTO_SECRET_KEY: CONFIG_CRYPTO_SECRET_KEY,
	CRYPTO_IV: CONFIG_CRYPTO_IV,
	FRONTEND_BASE_URL: CONFIG_FRONTEND_BASE_URL,

	FRONTEND_LOCAL_BASE_URLS: CONFIG_FRONTEND_LOCAL_BASE_URLS || "",

	APPLICANT_FRONTEND_BASE_URL: CONFIG_APPLICANT_FRONTEND_BASE_URL || "",
	WORTH_ADMIN_FRONTEND_BASE_URL: CONFIG_WORTH_ADMIN_FRONTEND_BASE_URL || "",
	CUSTOMER_ADMIN_FRONTEND_BASE_URL: CONFIG_CUSTOMER_ADMIN_FRONTEND_BASE_URL || "",

	AUTH_BASE_URL: CONFIG_AUTH_BASE_URL,
	INTEGRATION_BASE_URL: CONFIG_INTEGRATION_BASE_URL,
	MANUAL_SCORE_BASE_URL: CONFIG_MANUAL_SCORE_BASE_URL,
	WAREHOUSE_BASE_URL: CONFIG_WAREHOUSE_BASE_URL,

	KAFKA_GROUP_ID: CONFIG_KAFKA_GROUP_ID,
	KAFKA_BROKERS: CONFIG_KAFKA_BROKERS,
	KAFKA_SSL_ENABLED: parseBool(CONFIG_KAFKA_SSL_ENABLED, true),
	KAFKA_CLIENT_ID: CONFIG_KAFKA_CLIENT_ID,
	KAFKA_SASL_USERNAME: CONFIG_KAFKA_SASL_USERNAME,
	KAFKA_SASL_PASSWORD: CONFIG_KAFKA_SASL_PASSWORD,

	WORTH_ADMIN_USER_POOL_ID: CONFIG_WORTH_ADMIN_USER_POOL_ID,
	CUSTOMER_USER_POOL_ID: CONFIG_CUSTOMER_USER_POOL_ID,
	APPLICANT_USER_POOL_ID: CONFIG_APPLICANT_USER_POOL_ID,

	APPLICANT_CLIENT_ID: CONFIG_APPLICANT_CLIENT_ID,
	WORTH_ADMIN_CLIENT_ID: CONFIG_WORTH_ADMIN_CLIENT_ID,
	CUSTOMER_CLIENT_ID: CONFIG_CUSTOMER_CLIENT_ID,

	STRIPE_SECRET_KEY: CONFIG_STRIPE_SECRET_KEY || "",
	STRIPE_SUBSCRIPTION_SUCCESS_URL: CONFIG_STRIPE_SUBSCRIPTION_SUCCESS_URL,
	STRIPE_SUBSCRIPTION_CANCEL_URL: CONFIG_STRIPE_SUBSCRIPTION_CANCEL_URL,
	STRIPE_SUBSCRIPTIONS_WEBHOOK_SECRET: CONFIG_STRIPE_SUBSCRIPTIONS_WEBHOOK_SECRET,

	REDIS_URL: CONFIG_REDIS_URL,
	REDIS_HOST: CONFIG_REDIS_HOST,
	REDIS_PORT: CONFIG_REDIS_PORT,
	REDIS_PASSWORD: CONFIG_REDIS_PASSWORD,
	REDIS_EC_CLUSTER: parseBool(CONFIG_REDIS_EC_CLUSTER, true),
	REDIS_DISABLE_TLS: parseBool(CONFIG_REDIS_DISABLE_TLS, true),
	REDIS_DISABLE_TLS_REJECT_UNAUTHORIZED: parseBool(CONFIG_REDIS_DISABLE_TLS_REJECT_UNAUTHORIZED, true),
	REDIS_RECONNECT_MAX_WAIT: parseInt(CONFIG_REDIS_RECONNECT_MAX_WAIT),
	REDIS_KEY_PREFIX: CONFIG_REDIS_KEY_PREFIX || "",

	EIN_ENCRYPTION_CRYPTO_SECRET_KEY: CONFIG_EIN_ENCRYPTION_CRYPTO_SECRET_KEY,
	EIN_ENCRYPTION_CRYPTO_IV: CONFIG_EIN_ENCRYPTION_CRYPTO_IV,
	ENTERPRISE_APPLICANT_ID: CONFIG_ENTERPRISE_APPLICANT_ID,

	AWS_BACKEND_BUCKET: CONFIG_AWS_BACKEND_BUCKET,
	AWS_ACCESS_KEY_ID: CONFIG_AWS_ACCESS_KEY_ID,
	AWS_ACCESS_KEY_SECRET: CONFIG_AWS_ACCESS_KEY_SECRET,
	AWS_SES_REGION: CONFIG_AWS_SES_REGION,

	LD_SDK_KEY: CONFIG_LD_SDK_KEY,
	LD_INTIALIZATION_TIMEOUT: parseInt(CONFIG_LD_INTIALIZATION_TIMEOUT),
	LD_TEST_FLAGS_FILE: CONFIG_LD_TEST_FLAGS_FILE,

	CUSTOM_FIELDS_TEMPLATE: CONFIG_CUSTOM_FIELDS_TEMPLATE,
	REPORT_BASE_URL: CONFIG_REPORT_BASE_URL,

	REPORTS: CONFIG_REPORTS,
	WEBHOOKS: CONFIG_WEBHOOKS,
	INTEGRATIONS: CONFIG_INTEGRATIONS,
	NOTIFICATIONS: CONFIG_NOTIFICATIONS,
	SCORES: CONFIG_SCORES,
	BUSINESS: CONFIG_BUSINESS,
	CASES: CONFIG_CASES,
	USERS_NEW: CONFIG_USERS_NEW,
	DLQTOPIC: CONFIG_DLQTOPIC,
	TIN_VERIFICATION_ATTEMPTS: forceInteger(CONFIG_TIN_VERIFICATION_ATTEMPTS, 15),

	AWS_ELECTRONIC_CONSENT_BUCKET: CONFIG_AWS_ELECTRONIC_CONSENT_BUCKET,

	ELECTRONIC_CONSENT_BASE_URL: CONFIG_ELECTRONIC_CONSENT_BASE_URL,
	ECONSENT_API_KEY: CONFIG_ECONSENT_API_KEY
};

/**
 * Helper to return either the numeric integer version of a string or default value if it's not an integer
 * @param {*} value
 * @param {*} defaultIfNotInteger
 * @returns value as integer or defaultIfNotInteger
 */
function forceInteger(value, defaultIfNotInteger = 0) {
	const parsedValue = parseInt(value);
	return Number.isInteger(parsedValue) ? parsedValue : defaultIfNotInteger;
}
