import { Router } from "express";
import accountingRoutes from "./modules/accounting/routes";
import adverseMediaRoutes from "./modules/adverse-media/routes";
import bankingRoutes from "./modules/banking/routes";
import bureauRoutes from "./modules/bureau/routes";
import callbackRoutes from "./modules/callback/routes";
import coreRoutes from "./modules/core/routes";
import publicRecordsRoutes from "./modules/public-records/routes";
import scoreRoutes from "./modules/score/routes";
import taskRoutes from "./modules/tasks/routes";
import taxationRoutes from "./modules/taxation/routes";
import verificationRoutes from "./modules/verification/routes";
import faqChatboutRoutes from "./modules/faq-chatbot/routes";
import extractDocumentDetailsRoutes from "./modules/extract-document-details/routes";
import applicantRoutes from "./modules/applicants/routes";
import insightsRoutes from "./modules/insights/routes";
import queueRoues from "./modules/queue/routes";
import riskAlertsRouter from "./modules/risk-alerts/routes";
import whiteLabelRoutes from "./modules/white-label/routes";
import dataScrapeRoutes from "./modules/data-scrape/routes";
import ocrRoutes from "./modules/ocr/routes";
import fakerRoutes from "./modules/faker/routes";
import fileRoutes from "./modules/file/routes";
import factRoutes from "./modules/facts/routes";
import customerIntegrationSettingsRoutes from "./modules/customer-integration-settings/routes";
import processingHistoryRoutes from "./modules/processing-history/routes";
import electronicConsentRoutes from "./modules/electronic-consent/routes";
import documentsRoutes from "./modules/documents/routes";
import businessExtendedData from "./modules/business-extended-data/routes";
import caseTabValuesRoutes from "./modules/case-tab-values/routes";
import secretsRoutes from "./modules/secrets/routes";
import matchProRoutes from "./modules/match-pro/routes";
import xyxRoutes from "./modules/kyx/routes";
import paymentProcessors from "./modules/paymentProcessors/routes";
import geocodingRoutes from "./modules/geocoding/routes";
import { router as jobsRoutes } from "./modules/jobs/routes";
import customFieldsRoutes from "./modules/custom-fields/routes";

const router = new Router();

router.get("/", (req, res) => {
	res.jsend.success("Hello v1 API");
});

router.use(faqChatboutRoutes);
router.use(extractDocumentDetailsRoutes);
router.use(verificationRoutes);
router.use(accountingRoutes);
router.use(adverseMediaRoutes);
router.use(bankingRoutes);
router.use(coreRoutes);
router.use(publicRecordsRoutes);
router.use(scoreRoutes);
router.use(taskRoutes);
router.use(callbackRoutes);
router.use(bureauRoutes);
router.use(taxationRoutes);
router.use(applicantRoutes);
router.use(insightsRoutes);
router.use(queueRoues);
router.use(riskAlertsRouter);
router.use(whiteLabelRoutes);
router.use(dataScrapeRoutes);
router.use(ocrRoutes);
router.use(fakerRoutes);
router.use(fileRoutes);
router.use(factRoutes);
router.use(customerIntegrationSettingsRoutes);
router.use(processingHistoryRoutes);
router.use(electronicConsentRoutes);
router.use(documentsRoutes);
router.use(businessExtendedData);
router.use(caseTabValuesRoutes);
router.use(secretsRoutes);
router.use(matchProRoutes);
router.use(xyxRoutes);
router.use(paymentProcessors);
router.use(geocodingRoutes);
router.use(jobsRoutes);
router.use(customFieldsRoutes);
export default router;
