export const CASE_STATUS = {
	INVITED: 1, //deprecated: to be removed
	INVITE_EXPIRED: 2, //deprecated: to be removed
	ONBOARDING: 3,
	UNDER_MANUAL_REVIEW: 4,
	MANUALLY_APPROVED: 5,
	AUTO_APPROVED: 6,
	SCORE_CALCULATED: 7,
	MANUALLY_REJECTED: 8,
	ARCHIVED: 9,
	PENDING_DECISION: 10,
	INFORMATION_REQUESTED: 11,
	SUBMITTED: 12,
	AUTO_REJECTED: 13,
	RISK_ALERT: 14,
	INVESTIGATING: 15,
	DISMISSED: 16,
	ESCALATED: 17,
	PAUSED: 18,
	INFORMATION_UPDATED: 19,
	CREATED: 20
} as const;

export const CASE_STATUS_REVERSE = Object.fromEntries(Object.entries(CASE_STATUS).map(([k, v]) => [v, k]));

export enum CASE_STATUS_ENUM {
	INVITED = "INVITED", //deprecated: to be removed
	INVITE_EXPIRED = "INVITE_EXPIRED", //deprecated: to be removed
	ONBOARDING = "ONBOARDING",
	UNDER_MANUAL_REVIEW = "UNDER_MANUAL_REVIEW",
	MANUALLY_APPROVED = "MANUALLY_APPROVED",
	AUTO_APPROVED = "AUTO_APPROVED",
	SCORE_CALCULATED = "SCORE_CALCULATED",
	MANUALLY_REJECTED = "MANUALLY_REJECTED",
	ARCHIVED = "ARCHIVED",
	PENDING_DECISION = "PENDING_DECISION",
	INFORMATION_REQUESTED = "INFORMATION_REQUESTED",
	SUBMITTED = "SUBMITTED",
	AUTO_REJECTED = "AUTO_REJECTED",
	RISK_ALERT = "RISK_ALERT",
	INVESTIGATING = "INVESTIGATING",
	DISMISSED = "DISMISSED",
	ESCALATED = "ESCALATED",
	PAUSED = "PAUSED",
	INFORMATION_UPDATED = "INFORMATION_UPDATED",
	CREATED = "CREATED"
}
