export enum ERROR_CODES {
	UNAUTHENTICATED = "UNAUTHENTICATED",
	UNAUTHORIZED = "UNAUTHORIZED",
	NOT_FOUND = "NOT_FOUND",
	NOT_ALLOWED = "NOT_ALLOWED",
	INVALID = "INVALID",
	DUPLICATE = "DUPLICATE",
	UNKNOWN_ERROR = "UNKNOWN_ERROR",
	DEPRECATED = "DEPRECATED",
	MAINTENANCE = "MAINTENANCE",
	AWAITING_THIRD_PARTY_RESPONSE = "AWAITING_THIRD_PARTY_RESPONSE"
}
