export const CONNECTION_STATUS = {
	CREATED: "CREATED",
	INITIALIZED: "INITIALIZED",
	SUCCESS: "SUCCESS",
	FAILED: "FAILED",
	NEEDS_ACTION: "NEEDS_ACTION",
	REVOKED: "REVOKED"
} as const;

export enum GIACT_VERIFICATION_STATUS {
	CREATED = "CREATED",
	INITIALIZED = "INITIALIZED",
	IN_PROGRESS = "IN_PROGRESS",
	SUCCESS = "SUCCESS",
	FAILED = "FAILED",
	ERRORED = "ERRORED"
}

export const IDV_STATUS = {
	SUCCESS: 1,
	PENDING: 2,
	CANCELED: 3,
	EXPIRED: 4,
	FAILED: 99
} as const;

export const INTEGRATION_ID = {
	PLAID: 1,
	QUICKBOOKS: 2,
	PERSONA: 3,
	VERDATA: 4,
	RUTTER_QUICKBOOKS: 5,
	RUTTER_XERO: 6,
	RUTTER_ZOHO: 7,
	RUTTER_FRESHBOOKS: 8,
	RUTTER_QUICKBOOKSDESKTOP: 9,
	RUTTER_WAVE: 10,
	RUTTER_NETSUITE: 11,
	RUTTER_STRIPE: 12,
	RUTTER_SQUARE: 13,
	RUTTER_PAYPAL: 14,
	TAX_STATUS: 15,
	MIDDESK: 16,
	EQUIFAX: 17,
	PLAID_IDV: 18,
	GOOGLE_PLACES_REVIEWS: 19,
	GOOGLE_BUSINESS_REVIEWS: 20,
	MANUAL: 21,
	SERP_SCRAPE: 22,
	OPENCORPORATES: 23,
	ZOOMINFO: 24,
	ELECTRONIC_SIGNATURE: 25,
	GIACT: 26,
	ADVERSE_MEDIA: 27,
	NPI: 28,
	STRIPE: 41
} as const;

export const INTEGRATION_CATEGORIES = {
	BANKING: "Banking"
} as const;

export type ConnectionStatus = keyof typeof CONNECTION_STATUS;
export type GiactVerificationStatus = keyof typeof GIACT_VERIFICATION_STATUS;
export type IdvStatus = keyof typeof IDV_STATUS;
export type IntegrationPlatform = keyof typeof INTEGRATION_ID;
