export const SCORE_TRIGGER = {
	ONBOARDING_INVITE: "ONBOARDING_INVITE",
	MANUAL_REFRESH: "MANUAL_REFRESH",
	MONITORING_REFRESH: "MONITORING_REFRESH",
	SUBSCRIPTION_REFRESH: "SUBSCRIPTION_REFRESH",
	APPLICATION_EDIT: "APPLICATION_EDIT"
} as const;
