export const SUBSCRIPTIONS = {
	SUBSCRIBED: "SUBSCRIBED",
	UNSUBSCRIBED: "UNSUBSCRIBED",
	NOT_SUBSCRIBED: "NOT_SUBSCRIBED",
	PAYMENT_PENDING: "PAYMENT_PENDING",
	PAYMENT_DECLINED: "PAYMENT_DECLINED",
	PAYMENT_FAILED: "PAYMENT_FAILED"
} as const;
