export const VALIDATION_ERRORS = {
	external_id: "External Id is required and must be a non-empty string.",
	address_line_1: "Address Line 1 must be a string.",
	address_line_2: "Address Line 2 must be a string.",
	address_city: "Address City must be a string.",
	address_state: "Address State must be a string.",
	address_country: "Address Country must be a string.",
	address_postal_code: "Address Postal Code must be a string.",
	mobile: "Mobile must be a string of exactly 11 digits.",
	official_website: "Official Website must be a string.",
	naics_code: "Naics Code must be a number.",
	naics_title: "Naics Title must be a string.",
	mcc_code: "Mcc Code must be a number.",
	is_monitoring_enabled: "Is Monitoring Enabled must be a boolean.",
	applicant_id: "Applicant Id must be a valid UUID.",
	send_invitation: "Send Invitation must be a boolean.",
	applicant_first_name: "Applicant First Name must be a string up to 50 characters.",
	applicant_last_name: "Applicant Last Name must be a string up to 50 characters.",
	applicant_email: "Applicant Email must be a valid, non-disposable email address.",
	dba1_name: "Dba1 Name must be a string.",
	address1_line_1: "Address1 Line 1 must be a string.",
	address1_apartment: "Address1 Apartment must be a string.",
	address1_city: "Address1 City must be a string.",
	address1_state: "Address1 State must be a string of exactly 2 characters.",
	address1_country: "Address1 Country must be a string.",
	address1_postal_code: "Address1 Postal Code must be a string.",
	address1_mobile: "Address1 Mobile must be a string of exactly 11 digits.",
	year_created: "Year Created must be a number.",
	annual_total_income: "Annual Total Income must be a number.",
	total_wages: "Total Wages must be a number.",
	annual_net_income: "Annual Net Income must be a number.",
	cost_of_goods_sold: "Cost Of Goods Sold must be a number.",
	total_liabilities: "Total Liabilities must be a number.",
	total_assets: "Total Assets must be a number.",
	total_equity: "Total Equity must be a number.",
	total_accounts_payable: "Total Accounts Payable must be a number.",
	total_accounts_recievable: "Total Accounts Receivable must be a number.",
	total_cash_and_cash_equivalents: "Total Cash And Cash Equivalents must be a number.",
	total_short_term_investments: "Total Short Term Investments must be a number.",
	total_current_assets: "Total Current Assets must be a number.",
	total_current_liabilities: "Total Current Liabilities must be a number.",
	non_current_liablities: "Non Current Liabilities must be a number.",
	annual_cost_of_goods_sold: "Annual Cost Of Goods Sold must be a number.",
	annual_gross_profit: "Annual Gross Profit must be a number.",
	annual_taxes_paid: "Annual Taxes Paid must be a number.",
	annual_interest_expenses: "Annual Interest Expenses must be a number.",
	number_of_employees: "Number Of Employees must be a number.",
	business_type: "Business Type must be a string.",
	sic_code: "Sic Code must be a number.",
	score_retrieval_date: "Score Retrieval Date must be a string.",
	business_liens: "Business Liens must be a number.",
	business_liens_file_date: "Business Liens File Date must be a string.",
	business_liens_status: "Business Liens Status must be a string.",
	business_liens_status_date: "Business Liens Status Date must be a string.",
	business_bankruptcies: "Business Bankruptcies must be a number.",
	business_bankruptcies_file_date: "Business Bankruptcies File Date must be a string.",
	business_bankruptcies_chapter: "Business Bankruptcies Chapter must be a string.",
	business_bankruptcies_voluntary: "Business Bankruptcies Voluntary must be a string.",
	business_bankruptcies_status: "Business Bankruptcies Status must be a string.",
	business_bankruptcies_status_date: "Business Bankruptcies Status Date must be a string.",
	business_judgements: "Business Judgements must be a number.",
	business_judgements_file_date: "Business Judgements File Date must be a string.",
	business_judgements_status: "Business Judgements Status must be a string.",
	business_judgements_status_date: "Business Judgements Status Date must be a string.",
	business_judgements_amount: "Business Judgements Amount must be a number.",
	social_review_count: "Social Review Count must be a number.",
	social_review_score: "Social Review Score must be a number.",
	owner1_title: "Owner1 Title must be a string.",
	owner1_first_name: "Owner1 First Name must be a string.",
	owner1_last_name: "Owner1 Last Name must be a string.",
	owner1_email: "Owner1 Email must be a valid email address.",
	owner1_mobile: "Owner1 Mobile must be a string and more than 10 digits in length.",
	owner1_ssn: "Owner1 Ssn must be a string of exactly 4 or 9 digits in length.",
	owner1_dob: "Owner1 Dob must be a string and follow a valid ISO date (YYYY-MM-DD).",
	owner1_address_line_1: "Owner1 Address Line 1 must be a string.",
	owner1_address_line_2: "Owner1 Address Line 2 must be a string.",
	owner1_address_city: "Owner1 Address City must be a string.",
	owner1_address_state: "Owner1 Address State must be a string.",
	owner1_address_postal: "Owner1 Address Postal must be a string.",
	owner1_address_country: "Owner1 Address Country must be a string.",
	owner1_owner_type: "Owner1 Owner Type must be a string.",
	owner1_ownership_percentage: "Owner1 Ownership Percentage must be a number between 0 and 100.",
	bank_account_number: "Bank Account Number must be a string.",
	bank_name: "Bank Name must be a string.",
	institution_name: "Institution Name must be a string.",
	bank_routing_number: "Bank Routing Number must be a string exactly 9 digits in length.",
	bank_wire_routing_number: "Bank wire routing number must be a string exactly 9 digits (if provided).",
	bank_official_name: "Bank Official Name must be a string.",
	bank_account_type: "Bank Account Type must be a string.",
	bank_account_subtype: "Bank Account Subtype must be a string.",
	bank_account_balance_current: "Bank Account Balance Current must be a number.",
	bank_account_balance_available: "Bank Account Balance Available must be a number.",
	bank_account_balance_limit: "Bank Account Balance Limit must be a number.",
	bank_account_holder_type: "Bank Account Holder Type must be either 'business' or 'personal'.",
	bank_account_holder_name: "Bank Account Holder Name must be a string.",
	deposit_account: "Deposit Account must be a boolean.",
	public_website: "Public Website must be a string.",
	social_account: "Social Account must be a string.",
	industry: "Industry must be an object with id, code, and name.",
	dba: "DBA must be a string between 3 and 100 characters.",
	name: "Name must be a string between 3 and 100 characters.",
	tin: "TIN must be a string of exactly 9 digits.",
	npi_provider_number: "NPI provider number must be exactly 10 digits."
} as const;
