import type { EntityMatchTask } from "#lib/entityMatching/types";
import type { UUID } from "crypto";

export type NPIMatchResult = {
	npi: string;
	"replacement npi": string;
	"employer identification number (ein)": string;
	"provider organization name (legal business name)": string;
	"entity type code": string;
	"is sole proprietor": string;
	"last update date": string;
	"npi deactivation date"?: string;
	"npi reactivation date"?: string;
	"npi deactivation reason code": string;
	"provider gender code": string;
	"provider first name": string;
	"provider middle name": string;
	"provider last name (legal name)": string;
	"provider credential text": string;
	"provider first line business mailing address": string;
	"provider second line business mailing address": string;
	"provider business mailing address city name": string;
	"provider business mailing address state name": string;
	"provider business mailing address postal code": string;
	"provider business mailing address country code (if outside u.s.)": string;
	"provider business mailing address telephone number": string;
	"provider business mailing address fax number": string;
	"healthcare provider taxonomy code_1"?: string;
	"healthcare provider taxonomy code_2"?: string;
	"healthcare provider taxonomy code_3"?: string;
	"healthcare provider taxonomy code_4"?: string;
	"healthcare provider taxonomy code_5"?: string;
	"healthcare provider taxonomy code_6"?: string;
	"healthcare provider taxonomy code_7"?: string;
	"healthcare provider taxonomy code_8"?: string;
	"healthcare provider taxonomy code_9"?: string;
	"healthcare provider taxonomy code_10"?: string;
	"healthcare provider taxonomy code_11"?: string;
	"healthcare provider taxonomy code_12"?: string;
	"healthcare provider taxonomy code_13"?: string;
	"healthcare provider taxonomy code_14"?: string;
	"healthcare provider taxonomy code_15"?: string;
	"provider license number state code_1"?: string;
	"provider license number state code_2"?: string;
	"provider license number state code_3"?: string;
	"provider license number state code_4"?: string;
	"provider license number state code_5"?: string;
	"provider license number state code_6"?: string;
	"provider license number state code_7"?: string;
	"provider license number state code_8"?: string;
	"provider license number state code_9"?: string;
	"provider license number state code_10"?: string;
	"provider license number state code_11"?: string;
	"provider license number state code_12"?: string;
	"provider license number state code_13"?: string;
	"provider license number state code_14"?: string;
	"provider license number state code_15"?: string;
};

export type NPIMatchRecord = {
	business_integration_task_id: string;
	submitted_npi: string;
	business_id: string;
	case_id?: string;
	is_matched: boolean;
	employer_identification_number?: string;
	is_sole_proprietor?: boolean;
	created_at?: string;
	updated_at?: string;
	provider_gender_code?: string;
	provider_first_name?: string;
	provider_middle_name?: string;
	provider_last_name?: string;
	provider_organization_name?: string;
	provider_credential_text?: string;
	metadata?: Record<string, any>;
};

export type NPIResponse = {
	match: MatchResult;
	firmographic?: FirmographicResult;
	match_mode?: "ai";
}

export type MatchResult = {
	source: "npi";
	country: "US" | string;

	npi: string;
	first_name?: string;
	last_name?: string;
	practice_phone_number?: string;
	practice_fax_number?: string;
	authorized_official_middle_name?: string;
	authorized_official_telephone_number?: string;
	provider_license_number: string;
	authorized_official_credential_text?: string;
	replacement_npi?: string;
	employer_identification_number?: string;
	entity_type_code?: string;
	healthcare_provider_taxonomy_code_1?: string;
	last_update_date?: string;
	is_sole_proprietor?: string;
	npi_deactivation_date?: string;
	npi_reactivation_date?: string;
	npi_deactivation_reason_code?: string;
	row?: Record<string, any>;


	zip: string;
	city: string;
	name: string;
	zip3: string;
	region: string;
	address: string;
	short_name: string;
	state_code: string;
	other_names: string;
	street_name: string;
	collected_at: Date;
	street_number: number;
	canonical_name: string;
	normalized_zip: string;
	sanitized_name: string;
	normalized_name: string;
	other_addresses: string;
	normalized_address: string;
	extra_verification: {
		name_match: boolean | null;
		npi_match: boolean | null;
		canada_open_business_number_match: boolean | null;
		canada_open_corporate_id_match: boolean | null;
	}
};

export type NPIEntityMatchTask = EntityMatchTask<{match: MatchResult}>;


export type FirmographicResult = {
"npi": string | null;
"entity type code": string | null;
"replacement npi": string | null;
"employer identification number (ein)": string | null;
"provider organization name (legal business name)": string | null;
"provider last name (legal name)": string | null;
"provider first name": string | null;
"provider middle name": string | null;
"provider name prefix text": string | null;
"provider name suffix text": string | null;
"provider credential text": string | null;
"provider other organization name": string | null;
"provider other organization name type code": string | null;
"provider other last name": string | null;
"provider other first name": string | null;
"provider other middle name": string | null;
"provider other name prefix text": string | null;
"provider other name suffix text": string | null;
"provider other credential text": string | null;
"provider other last name type code": string | null;
"provider first line business mailing address": string | null;
"provider second line business mailing address": string | null;
"provider business mailing address city name": string | null;
"provider business mailing address state name": string | null;
"provider business mailing address postal code": string | null;
"provider business mailing address country code (if outside u.s.)": string | null;
"provider business mailing address telephone number": string | null;
"provider business mailing address fax number": string | null;
"provider first line business practice location address": string | null;
"provider second line business practice location address": string | null;
"provider business practice location address city name": string | null;
"provider business practice location address state name": string | null;
"provider business practice location address postal code": string | null;
"provider business practice location address country code (if outside u.s.)": string | null;
"provider business practice location address telephone number": string | null;
"provider business practice location address fax number": string | null;
"provider enumeration date": string | null;
"last update date": string | null;
"npi deactivation reason code": string | null;
"npi deactivation date": string | null;
"npi reactivation date": string | null;
"provider gender code": string | null;
"authorized official last name": string | null;
"authorized official first name": string | null;
"authorized official middle name": string | null;
"authorized official title or position": string | null;
"authorized official telephone number": string | null;
"healthcare provider taxonomy code_1": string | null;
"provider license number_1": string | null;
"provider license number state code_1": string | null;
"healthcare provider primary taxonomy switch_1": string | null;
"healthcare provider taxonomy code_2": string | null;
"provider license number_2": string | null;
"provider license number state code_2": string | null;
"healthcare provider primary taxonomy switch_2": string | null;
"healthcare provider taxonomy code_3": string | null;
"provider license number_3": string | null;
"provider license number state code_3": string | null;
"healthcare provider primary taxonomy switch_3": string | null;
"healthcare provider taxonomy code_4": string | null;
"provider license number_4": string | null;
"provider license number state code_4": string | null;
"healthcare provider primary taxonomy switch_4": string | null;
"healthcare provider taxonomy code_5": string | null;
"provider license number_5": string | null;
"provider license number state code_5": string | null;
"healthcare provider primary taxonomy switch_5": string | null;
"healthcare provider taxonomy code_6": string | null;
"provider license number_6": string | null;
"provider license number state code_6": string | null;
"healthcare provider primary taxonomy switch_6": string | null;
"healthcare provider taxonomy code_7": string | null;
"provider license number_7": string | null;
"provider license number state code_7": string | null;
"healthcare provider primary taxonomy switch_7": string | null;
"healthcare provider taxonomy code_8": string | null;
"provider license number_8": string | null;
"provider license number state code_8": string | null;
"healthcare provider primary taxonomy switch_8": string | null;
"healthcare provider taxonomy code_9": string | null;
"provider license number_9": string | null;
"provider license number state code_9": string | null;
"healthcare provider primary taxonomy switch_9": string | null;
"healthcare provider taxonomy code_10": string | null;
"provider license number_10": string | null;
"provider license number state code_10": string | null;
"healthcare provider primary taxonomy switch_10": string | null;
"healthcare provider taxonomy code_11": string | null;
"provider license number_11": string | null;
"provider license number state code_11": string | null;
"healthcare provider primary taxonomy switch_11": string | null;
"healthcare provider taxonomy code_12": string | null;
"provider license number_12": string | null;
"provider license number state code_12": string | null;
"healthcare provider primary taxonomy switch_12": string | null;
"healthcare provider taxonomy code_13": string | null;
"provider license number_13": string | null;
"provider license number state code_13": string | null;
"healthcare provider primary taxonomy switch_13": string | null;
"healthcare provider taxonomy code_14": string | null;
"provider license number_14": string | null;
"provider license number state code_14": string | null;
"healthcare provider primary taxonomy switch_14": string | null;
"healthcare provider taxonomy code_15": string | null;
"provider license number_15": string | null;
"provider license number state code_15": string | null;
"healthcare provider primary taxonomy switch_15": string | null;
"other provider identifier_1": string | null;
"other provider identifier type code_1": string | null;
"other provider identifier state_1": string | null;
"other provider identifier issuer_1": string | null;
"other provider identifier_2": string | null;
"other provider identifier type code_2": string | null;
"other provider identifier state_2": string | null;
"other provider identifier issuer_2": string | null;
"other provider identifier_3": string | null;
"other provider identifier type code_3": string | null;
"other provider identifier state_3": string | null;
"other provider identifier issuer_3": string | null;
"other provider identifier_4": string | null;
"other provider identifier type code_4": string | null;
"other provider identifier state_4": string | null;
"other provider identifier issuer_4": string | null;
"other provider identifier_5": string | null;
"other provider identifier type code_5": string | null;
"other provider identifier state_5": string | null;
"other provider identifier issuer_5": string | null;
"other provider identifier_6": string | null;
"other provider identifier type code_6": string | null;
"other provider identifier state_6": string | null;
"other provider identifier issuer_6": string | null;
"other provider identifier_7": string | null;
"other provider identifier type code_7": string | null;
"other provider identifier state_7": string | null;
"other provider identifier issuer_7": string | null;
"other provider identifier_8": string | null;
"other provider identifier type code_8": string | null;
"other provider identifier state_8": string | null;
"other provider identifier issuer_8": string | null;
"other provider identifier_9": string | null;
"other provider identifier type code_9": string | null;
"other provider identifier state_9": string | null;
"other provider identifier issuer_9": string | null;
"other provider identifier_10": string | null;
"other provider identifier type code_10": string | null;
"other provider identifier state_10": string | null;
"other provider identifier issuer_10": string | null;
"other provider identifier_11": string | null;
"other provider identifier type code_11": string | null;
"other provider identifier state_11": string | null;
"other provider identifier issuer_11": string | null;
"other provider identifier_12": string | null;
"other provider identifier type code_12": string | null;
"other provider identifier state_12": string | null;
"other provider identifier issuer_12": string | null;
"other provider identifier_13": string | null;
"other provider identifier type code_13": string | null;
"other provider identifier state_13": string | null;
"other provider identifier issuer_13": string | null;
"other provider identifier_14": string | null;
"other provider identifier type code_14": string | null;
"other provider identifier state_14": string | null;
"other provider identifier issuer_14": string | null;
"other provider identifier_15": string | null;
"other provider identifier type code_15": string | null;
"other provider identifier state_15": string | null;
"other provider identifier issuer_15": string | null;
"other provider identifier_16": string | null;
"other provider identifier type code_16": string | null;
"other provider identifier state_16": string | null;
"other provider identifier issuer_16": string | null;
"other provider identifier_17": string | null;
"other provider identifier type code_17": string | null;
"other provider identifier state_17": string | null;
"other provider identifier issuer_17": string | null;
"other provider identifier_18": string | null;
"other provider identifier type code_18": string | null;
"other provider identifier state_18": string | null;
"other provider identifier issuer_18": string | null;
"other provider identifier_19": string | null;
"other provider identifier type code_19": string | null;
"other provider identifier state_19": string | null;
"other provider identifier issuer_19": string | null;
"other provider identifier_20": string | null;
"other provider identifier type code_20": string | null;
"other provider identifier state_20": string | null;
"other provider identifier issuer_20": string | null;
"other provider identifier_21": string | null;
"other provider identifier type code_21": string | null;
"other provider identifier state_21": string | null;
"other provider identifier issuer_21": string | null;
"other provider identifier_22": string | null;
"other provider identifier type code_22": string | null;
"other provider identifier state_22": string | null;
"other provider identifier issuer_22": string | null;
"other provider identifier_23": string | null;
"other provider identifier type code_23": string | null;
"other provider identifier state_23": string | null;
"other provider identifier issuer_23": string | null;
"other provider identifier_24": string | null;
"other provider identifier type code_24": string | null;
"other provider identifier state_24": string | null;
"other provider identifier issuer_24": string | null;
"other provider identifier_25": string | null;
"other provider identifier type code_25": string | null;
"other provider identifier state_25": string | null;
"other provider identifier issuer_25": string | null;
"other provider identifier_26": string | null;
"other provider identifier type code_26": string | null;
"other provider identifier state_26": string | null;
"other provider identifier issuer_26": string | null;
"other provider identifier_27": string | null;
"other provider identifier type code_27": string | null;
"other provider identifier state_27": string | null;
"other provider identifier issuer_27": string | null;
"other provider identifier_28": string | null;
"other provider identifier type code_28": string | null;
"other provider identifier state_28": string | null;
"other provider identifier issuer_28": string | null;
"other provider identifier_29": string | null;
"other provider identifier type code_29": string | null;
"other provider identifier state_29": string | null;
"other provider identifier issuer_29": string | null;
"other provider identifier_30": string | null;
"other provider identifier type code_30": string | null;
"other provider identifier state_30": string | null;
"other provider identifier issuer_30": string | null;
"other provider identifier_31": string | null;
"other provider identifier type code_31": string | null;
"other provider identifier state_31": string | null;
"other provider identifier issuer_31": string | null;
"other provider identifier_32": string | null;
"other provider identifier type code_32": string | null;
"other provider identifier state_32": string | null;
"other provider identifier issuer_32": string | null;
"other provider identifier_33": string | null;
"other provider identifier type code_33": string | null;
"other provider identifier state_33": string | null;
"other provider identifier issuer_33": string | null;
"other provider identifier_34": string | null;
"other provider identifier type code_34": string | null;
"other provider identifier state_34": string | null;
"other provider identifier issuer_34": string | null;
"other provider identifier_35": string | null;
"other provider identifier type code_35": string | null;
"other provider identifier state_35": string | null;
"other provider identifier issuer_35": string | null;
"other provider identifier_36": string | null;
"other provider identifier type code_36": string | null;
"other provider identifier state_36": string | null;
"other provider identifier issuer_36": string | null;
"other provider identifier_37": string | null;
"other provider identifier type code_37": string | null;
"other provider identifier state_37": string | null;
"other provider identifier issuer_37": string | null;
"other provider identifier_38": string | null;
"other provider identifier type code_38": string | null;
"other provider identifier state_38": string | null;
"other provider identifier issuer_38": string | null;
"other provider identifier_39": string | null;
"other provider identifier type code_39": string | null;
"other provider identifier state_39": string | null;
"other provider identifier issuer_39": string | null;
"other provider identifier_40": string | null;
"other provider identifier type code_40": string | null;
"other provider identifier state_40": string | null;
"other provider identifier issuer_40": string | null;
"other provider identifier_41": string | null;
"other provider identifier type code_41": string | null;
"other provider identifier state_41": string | null;
"other provider identifier issuer_41": string | null;
"other provider identifier_42": string | null;
"other provider identifier type code_42": string | null;
"other provider identifier state_42": string | null;
"other provider identifier issuer_42": string | null;
"other provider identifier_43": string | null;
"other provider identifier type code_43": string | null;
"other provider identifier state_43": string | null;
"other provider identifier issuer_43": string | null;
"other provider identifier_44": string | null;
"other provider identifier type code_44": string | null;
"other provider identifier state_44": string | null;
"other provider identifier issuer_44": string | null;
"other provider identifier_45": string | null;
"other provider identifier type code_45": string | null;
"other provider identifier state_45": string | null;
"other provider identifier issuer_45": string | null;
"other provider identifier_46": string | null;
"other provider identifier type code_46": string | null;
"other provider identifier state_46": string | null;
"other provider identifier issuer_46": string | null;
"other provider identifier_47": string | null;
"other provider identifier type code_47": string | null;
"other provider identifier state_47": string | null;
"other provider identifier issuer_47": string | null;
"other provider identifier_48": string | null;
"other provider identifier type code_48": string | null;
"other provider identifier state_48": string | null;
"other provider identifier issuer_48": string | null;
"other provider identifier_49": string | null;
"other provider identifier type code_49": string | null;
"other provider identifier state_49": string | null;
"other provider identifier issuer_49": string | null;
"other provider identifier_50": string | null;
"other provider identifier type code_50": string | null;
"other provider identifier state_50": string | null;
"other provider identifier issuer_50": string | null;
"is sole proprietor": string | null;
"is organization subpart": string | null;
"parent organization lbn": string | null;
"parent organization tin": string | null;
"authorized official name prefix text": string | null;
"authorized official name suffix text": string | null;
"authorized official credential text": string | null;
"healthcare provider taxonomy group_1": string | null;
"healthcare provider taxonomy group_2": string | null;
"healthcare provider taxonomy group_3": string | null;
"healthcare provider taxonomy group_4": string | null;
"healthcare provider taxonomy group_5": string | null;
"healthcare provider taxonomy group_6": string | null;
"healthcare provider taxonomy group_7": string | null;
"healthcare provider taxonomy group_8": string | null;
"healthcare provider taxonomy group_9": string | null;
"healthcare provider taxonomy group_10": string | null;
"healthcare provider taxonomy group_11": string | null;
"healthcare provider taxonomy group_12": string | null;
"healthcare provider taxonomy group_13": string | null;
"healthcare provider taxonomy group_14": string | null;
"healthcare provider taxonomy group_15": string | null;
"certification date": string | null;
}

export type NPIFirmographicsEventBaseSchema = {
	records: FirmographicResult[];
}

export type NPIFirmographicsEventSchema = {
	collected_at: Date;
	business_id: UUID;
	source: "npi";
	firmographics: NPIFirmographicsEventBaseSchema;
}
