STREET_ABBREVIATIONS = {
    "ALY": "ALLEY",
    "ANX": "ANEX",
    "ARC": "ARCADE",
    "AVE": "AVENUE",
    "BYU": "BAYOU",
    "BCH": "BEACH",
    "BND": "BEND",
    "BLF": "BLUFF",
    "BLFS": "BLUFFS",
    "BTM": "BOTTOM",
    "BLVD": "BOULEVARD",
    "BR": "BRANCH",
    "BRG": "BRIDGE",
    "BRK": "BROOK",
    "BRKS": "BROOKS",
    "BG": "BURG",
    "BGS": "BURGS",
    "BYP": "BYPASS",
    "CP": "CAMP",
    "CYN": "CANYON",
    "CPE": "CAPE",
    "CSWY": "CAUSEWAY",
    "CTR": "CENTER",
    "CTRS": "CENTERS",
    "CIR": "CIRCLE",
    "CIRS": "CIRCLES",
    "CLF": "CLIFF",
    "CLFS": "CLIFFS",
    "CLB": "CLUB",
    "CMN": "COMMON",
    "CMNS": "COMMONS",
    "COR": "CORNER",
    "CORS": "CORNERS",
    "CRSE": "COURSE",
    "CT": "COURT",
    "CTS": "COURTS",
    "CV": "COVE",
    "CVS": "COVES",
    "CRK": "CREEK",
    "CRES": "CRESCENT",
    "CRST": "CREST",
    "XING": "CROSSING",
    "XRD": "CROSSROAD",
    "XRDS": "CROSSROADS",
    "CURV": "CURVE",
    "DL": "DALE",
    "DM": "DAM",
    "DV": "DIVIDE",
    "DR": "DRIVE",
    "DRS": "DRIVES",
    "EST": "ESTATE",
    "ESTS": "ESTATES",
    "EXPY": "EXPRESSWAY",
    "EXT": "EXTENSION",
    "EXTS": "EXTENSIONS",
    "FALL": "FALL",
    "FLS": "FALLS",
    "FRY": "FERRY",
    "FLD": "FIELD",
    "FLDS": "FIELDS",
    "FLT": "FLAT",
    "FLTS": "FLATS",
    "FRD": "FORD",
    "FRDS": "FORDS",
    "FRST": "FOREST",
    "FRG": "FORGE",
    "FRGS": "FORGES",
    "FRK": "FORK",
    "FRKS": "FORKS",
    "FT": "FORT",
    "FWY": "FREEWAY",
    "GALL": "GALLERIA",
    "GDN": "GARDEN",
    "GDNS": "GARDENS",
    "GTWY": "GATEWAY",
    "GLN": "GLEN",
    "GLNS": "GLENS",
    "GRN": "GREEN",
    "GRNS": "GREENS",
    "GRV": "GROVE",
    "GRVS": "GROVES",
    "HBR": "HARBOR",
    "HBRS": "HARBORS",
    "HVN": "HAVEN",
    "HTS": "HEIGHTS",
    "HWY": "HIGHWAY",
    "HL": "HILL",
    "HLS": "HILLS",
    "HOLW": "HOLLOW",
    "INLT": "INLET",
    "IS": "ISLAND",
    "ISS": "ISLANDS",
    "ISLE": "ISLE",
    "JCT": "JUNCTION",
    "JCTS": "JUNCTIONS",
    "KY": "KEY",
    "KYS": "KEYS",
    "KNL": "KNOLL",
    "KNLS": "KNOLLS",
    "LK": "LAKE",
    "LKS": "LAKES",
    "LAND": "LAND",
    "LNDG": "LANDING",
    "LN": "LANE",
    "LGT": "LIGHT",
    "LGTS": "LIGHTS",
    "LF": "LOAF",
    "LCK": "LOCK",
    "LCKS": "LOCKS",
    "LDG": "LODGE",
    "LOOP": "LOOP",
    "MALL": "MALL",
    "MNR": "MANOR",
    "MNRS": "MANORS",
    "MDW": "MEADOW",
    "MDWS": "MEADOWS",
    "MEWS": "MEWS",
    "ML": "MILL",
    "MLS": "MILLS",
    "MSN": "MISSION",
    "MTWY": "MOTORWAY",
    "MT": "MOUNT",
    "MTN": "MOUNTAIN",
    "MTNS": "MOUNTAINS",
    "NCK": "NECK",
    "ORCH": "ORCHARD",
    "OVAL": "OVAL",
    "OPAS": "OVERPASS",
    "PARK": "PARK",
    "PARKS": "PARK",
    "PKWY": "PARKWAY",
    "PASS": "PASS",
    "PSGE": "PASSAGE",
    "PATH": "PATH",
    "PIKE": "PIKE",
    "PNE": "PINE",
    "PNES": "PINES",
    "PL": "PLACE",
    "PLN": "PLAIN",
    "PLNS": "PLAINS",
    "PLZ": "PLAZA",
    "PT": "POINT",
    "PTS": "POINTS",
    "PRT": "PORT",
    "PRTS": "PORTS",
    "PR": "PRARIE",
    "RADL": "RADIAL",
    "RAMP": "RAMP",
    "RNCH": "RANCH",
    "RPD": "RAPID",
    "RPDS": "RAPIDS",
    "RCH": "REACH",
    "RST": "REST",
    "RDG": "RIDGE",
    "RDGS": "RIDGES",
    "RIV": "RIVER",
    "RD": "ROAD",
    "RDS": "ROADS",
    "RTE": "ROUTE",
    "ROW": "ROW",
    "RUE": "RUE",
    "RUN": "RUN",
    "SHL": "SHOAL",
    "SHLS": "SHOALS",
    "SHR": "SHORE",
    "SHRS": "SHORES",
    "SKWY": "SKYWAY",
    "SPG": "SPRING",
    "SPGS": "SPRINGS",
    "SPUR": "SPUR",
    "SPURS": "SPUR",
    "SQ": "SQUARE",
    "SQS": "SQUARES",
    "STA": "STATION",
    "STRA": "STRAVENUE",
    "STRM": "STREAM",
    "ST": "STREET",
    "STS": "STREETS",
    "SMT": "SUMMIT",
    "TER": "TERRACE",
    "TRWY": "THROUGHWAY",
    "TRCE": "TRACE",
    "TRAK": "TRACK",
    "TRFY": "TRAFFICWAY",
    "TRL": "TRAIL",
    "TRLR": "TRAILER",
    "TUNN": "TUNNEL",
    "TPKE": "TURNPIKE",
    "UPAS": "UNDERPASS",
    "UN": "UNION",
    "UNS": "UNIONS",
    "VLY": "VALLEY",
    "VLYS": "VALLEYS",
    "VIA": "VIADUCT",
    "VW": "VIEW",
    "VWS": "VIEWS",
    "VLG": "VILLAGE",
    "VLGS": "VILLAGES",
    "VL": "VILLE",
    "VIS": "VISTA",
    "WALK": "WALK",
    "WALKS": "WALK",
    "WALL": "WALL",
    "WAY": "WAY",
    "WAYS": "WAYS",
    "WL": "WELL",
    "WLS": "WELLS",
    "BX": "BOX",
}

DIRECTIONS = {
    "S": "SOUTH",
    "N": "NORTH",
    "E": "EAST",
    "W": "WEST",
    "NE": "NORTHEAST",
    "NW": "NORTHWEST",
    "SE": "SOUTHEAST",
    "SW": "SOUTHWEST",
}

SECONDARY_ABBREVIATIONS = {
    "APT": "APARTMENT",
    "BLDG": "BUILDING",
    "FL": "FLOOR",
    "STE": "SUITE",
    "UNIT": "UNIT",
    "RM": "ROOM",
    "DEPT": "DEPARTMENT",
    "NUM": "NUMBER",
}

STATE_ABBREVIATIONS = {
    # United States
    "ALABAMA": "AL",
    "ALASKA": "AK",
    "ARIZONA": "AZ",
    "ARKANSAS": "AR",
    "CALIFORNIA": "CA",
    "COLORADO": "CO",
    "CONNECTICUT": "CT",
    "DELAWARE": "DE",
    "FLORIDA": "FL",
    "GEORGIA": "GA",
    "HAWAII": "HI",
    "IDAHO": "ID",
    "ILLINOIS": "IL",
    "INDIANA": "IN",
    "IOWA": "IA",
    "KANSAS": "KS",
    "KENTUCKY": "KY",
    "LOUISIANA": "LA",
    "MAINE": "ME",
    "MARYLAND": "MD",
    "MASSACHUSETTS": "MA",
    "MICHIGAN": "MI",
    "MINNESOTA": "MN",
    "MISSISSIPPI": "MS",
    "MISSOURI": "MO",
    "MONTANA": "MT",
    "NEBRASKA": "NE",
    "NEVADA": "NV",
    "NEW HAMPSHIRE": "NH",
    "NEW JERSEY": "NJ",
    "NEW MEXICO": "NM",
    "NEW YORK": "NY",
    "NORTH CAROLINA": "NC",
    "NORTH DAKOTA": "ND",
    "OHIO": "OH",
    "OKLAHOMA": "OK",
    "OREGON": "OR",
    "PENNSYLVANIA": "PA",
    "RHODE ISLAND": "RI",
    "SOUTH CAROLINA": "SC",
    "SOUTH DAKOTA": "SD",
    "TENNESSEE": "TN",
    "TEXAS": "TX",
    "UTAH": "UT",
    "VERMONT": "VT",
    "VIRGINIA": "VA",
    "WASHINGTON": "WA",
    "WEST VIRGINIA": "WV",
    "WISCONSIN": "WI",
    "WYOMING": "WY",
    "PUERTO RICO": "PR",
    "DISTRICT OF COLUMBIA": "DC",
    # Canada
    "ALBERTA": "AB",
    "BRITISH COLUMBIA": "BC",
    "MANITOBA": "MB",
    "NEW BRUNSWICK": "NB",
    "NEWFOUNDLAND AND LABRADOR": "NL",
    "NOVA SCOTIA": "NS",
    "NORTHWEST TERRITORIES": "NT",
    "NUNAVUT": "NU",
    "ONTARIO": "ON",
    "PRINCE EDWARD ISLAND": "PE",
    "QUEBEC": "QC",
    "SASKATCHEWAN": "SK",
    "YUKON": "YT",
}

UK_POSTAL_LOCALITIES = {
    "ABERDEEN": "AB",
    "ST ALBANS": "AL",
    "BIRMINGHAM": "B",
    "BATH": "BA",
    "BLACKBURN": "BB",
    "BRADFORD": "BD",
    "BOURNEMOUTH": "BH",
    "BOLTON": "BL",
    "BRIGHTON": "BN",
    "BROMLEY": "BR",
    "BRISTOL": "BS",
    "BELFAST": "BT",
    "CARLISLE": "CA",
    "CAMBRIDGE": "CB",
    "CARDIFF": "CF",
    "CHESTER": "CH",
    "CHELMSFORD": "CM",
    "COLCHESTER": "CO",
    "CROYDON": "CR",
    "CANTERBURY": "CT",
    "COVENTRY": "CV",
    "CREWE": "CW",
    "DARTFORD": "DA",
    "DUNDEE": "DD",
    "DERBY": "DE",
    "DUMFRIES AND GALLOWAY": "DG",
    "DURHAM": "DH",
    "DARLINGTON": "DL",
    "DONCASTER": "DN",
    "DORCHESTER": "DT",
    "DUDLEY": "DY",
    "EAST LONDON": "E",
    "EAST CENTRAL LONDON": "EC",
    "EDINBURGH": "EH",
    "ENFIELD": "EN",
    "EXETER": "EX",
    "FALKIRK": "FK",
    "BLACKPOOL": "FY",
    "GLASGOW": "G",
    "GLOUCESTER": "GL",
    "GUILDFORD": "GU",
    "GUERNSEY": "GY",
    "HARROW": "HA",
    "HUDDERSFIELD": "HD",
    "HARROGATE": "HG",
    "HEMEL HEMPSTEAD": "HP",
    "HEREFORD": "HR",
    "OUTER HEBRIDES": "HS",
    "HULL": "HU",
    "HALIFAX": "HX",
    "ILFORD": "IG",
    "ISLE OF MAN": "IM",
    "IPSWICH": "IP",
    "INVERNESS": "IV",
    "JERSEY": "JE",
    "KILMARNOCK": "KA",
    "KINGSTON UPON THAMES": "KT",
    "KIRKWALL": "KW",
    "KIRKCALDY": "KY",
    "LIVERPOOL": "L",
    "LANCASTER": "LA",
    "LLANDRINDOD WELLS": "LD",
    "LEICESTER": "LE",
    "LLANDUDNO": "LL",
    "LINCOLN": "LN",
    "LEEDS": "LS",
    "LUTON": "LU",
    "MANCHESTER": "M",
    "MEDWAY": "ME",
    "MILTON KEYNES": "MK",
    "MOTHERWELL": "ML",
    "NORTH LONDON": "N",
    "NEWCASTLE UPON TYNE": "NE",
    "NOTTINGHAM": "NG",
    "NORTHAMPTON": "NN",
    "NEWPORT": "NP",
    "NORWICH": "NR",
    "NORTH WEST LONDON": "NW",
    "OLDHAM": "OL",
    "OXFORD": "OX",
    "PAISLEY": "PA",
    "PETERBOROUGH": "PE",
    "PERTH": "PH",
    "PLYMOUTH": "PL",
    "PORTSMOUTH": "PO",
    "PRESTON": "PR",
    "READING": "RG",
    "REDHILL": "RH",
    "ROMFORD": "RM",
    "SHEFFIELD": "S",
    "SWANSEA": "SA",
    "SOUTH EAST LONDON": "SE",
    "STEVENAGE": "SG",
    "STOCKPORT": "SK",
    "SLOUGH": "SL",
    "SUTTON": "SM",
    "SWINDON": "SN",
    "SOUTHAMPTON": "SO",
    "SALISBURY": "SP",
    "SUNDERLAND": "SR",
    "SOUTHEND-ON-SEA": "SS",
    "STOKE-ON-TRENT": "ST",
    "SOUTH WEST LONDON": "SW",
    "SHREWSBURY": "SY",
    "TAUNTON": "TA",
    "GALASHIELS": "TD",
    "TELFORD": "TF",
    "TONBRIDGE": "TN",
    "TORQUAY": "TQ",
    "TRURO": "TR",
    "TEESSIDE": "TS",
    "TWICKENHAM": "TW",
    "SOUTHALL": "UB",
    "WEST LONDON": "W",
    "WARRINGTON": "WA",
    "WEST CENTRAL LONDON": "WC",
    "WATFORD": "WD",
    "WAKEFIELD": "WF",
    "WIGAN": "WN",
    "WORCESTER": "WR",
    "WALSALL": "WS",
    "WOLVERHAMPTON": "WV",
    "YORK": "YO",
    "LERWICK": "ZE",
}

NORMALIZATION_WORD_PARTS = {
    "prefix": ["THE", "A", "AN", "LE", "LA", "LES", "LAS", "LOS", "L’"],
    "suffix": [
        "PLLC",
        "LLC",
        "PROFESSIONAL LIMITED LIABILITY COMPANY",
        "LIMITED LIABILITY COMPANY",
        "LIMITED LIABILITY CO",
        "CORP",
        "NONPROFIT CORPORATION",
        "PROFESSIONAL CORPORATION",
        "CORPORATION",
        "INC",
        "INCORPORATED",
        "INCORPOREE",
        "LTD",
        "LIMITED",
        "CO",
        "COMPANY",
        "LLP",
        "LP",
        "LIMITED LIABILITY PARTNERSHIP",
        "LIMITED PARTNERSHIP",
        "GP",
        "GENERAL PARTNERSHIP",
        "PC",
        "PA",
        "PROFESSIONAL ASSOCIATION",
        "NFP",
        "NOT FOR PROFIT",
        "ASSOC",
        "ASSOCIATION",
        "ULC",
        "UNLIMITED LIABILITY COMPANY",
        "LTEE",
        "LIMITEE",
        "SENC",
        "SEC",
        "SCOP",
        "SENCRL",
        "COOP",
        "COOPERATIVE",
        "FOUNDATION",
        "FONDATION",
        "SOCIETE",
        "SOCIETY",
    ],
}

SUPPORTED_COUNTRIES = {
    "CAN": "CA",
    "CANADA": "CA",
    "AMERICA": "US",
    "THE UNITED STATES": "US",
    "THE UNITED STATES OF AMERICA": "US",
    "UNITED STATES": "US",
    "UNITED STATES OF AMERICA": "US",
    "USA": "US",
    "ENGLAND": "GB",
    "NORTHERN IRELAND": "GB",
    "SCOTLAND": "GB",
    "THE UNITED KINGDOM": "GB",
    "UK": "GB",
    "UNITED KINGDOM": "GB",
    "WALES": "GB",
    "GREAT BRITAIN": "GB",
    "IRELAND": "IE",
    "REPUBLIC OF IRELAND": "IE",
}

UK_POSTAL_CODE_PATTERN = r"^[A-z]{1,2}\d[A-z\d]? \d[A-z]{2}$"
UK_POSTAL_CODE_PREFIX_PATTERN = r"^[A-z]{1,2}"
IE_POSTAL_CODE_PATTERN = r"^(?:[A-Z]\d{2}|[A-Z]{2}\d)[ ]?[A-Z0-9]{4}$"

IE_POSTAL_CODE_PREFIX_TO_COUNTY = {
    "A41": "DUBLIN",
    "A42": "DUBLIN",
    "A45": "DUBLIN",
    "A63": "WICKLOW",
    "A67": "WICKLOW",
    "A75": "MONAGHAN",
    "A81": "MONAGHAN",
    "A82": "CAVAN",
    "A83": "MEATH",
    "A84": "MEATH",
    "A85": "MEATH",
    "A86": "MEATH",
    "A91": "LOUTH",
    "A92": "MEATH",
    "A94": "DUBLIN",
    "A96": "DUBLIN",
    "A98": "WICKLOW",
    "C15": "MEATH",
    "D01": "DUBLIN",
    "D02": "DUBLIN",
    "D03": "DUBLIN",
    "D04": "DUBLIN",
    "D05": "DUBLIN",
    "D06": "DUBLIN",
    "D07": "DUBLIN",
    "D08": "DUBLIN",
    "D09": "DUBLIN",
    "D10": "DUBLIN",
    "D11": "DUBLIN",
    "D12": "DUBLIN",
    "D13": "DUBLIN",
    "D14": "DUBLIN",
    "D15": "DUBLIN",
    "D16": "DUBLIN",
    "D17": "DUBLIN",
    "D18": "DUBLIN",
    "D20": "DUBLIN",
    "D22": "DUBLIN",
    "D24": "DUBLIN",
    "D6W": "DUBLIN",
    "E21": "TIPPERARY",
    "E25": "TIPPERARY",
    "E32": "TIPPERARY",
    "E34": "TIPPERARY",
    "E41": "TIPPERARY",
    "E45": "TIPPERARY",
    "E53": "TIPPERARY",
    "E91": "TIPPERARY",
    "F12": "MAYO",
    "F23": "MAYO",
    "F26": "MAYO",
    "F28": "MAYO",
    "F31": "MAYO",
    "F35": "MAYO",
    "F42": "ROSCOMMON",
    "F45": "ROSCOMMON",
    "F52": "ROSCOMMON",
    "F56": "SLIGO",
    "F91": "SLIGO",
    "F92": "DONEGAL",
    "F93": "DONEGAL",
    "F94": "DONEGAL",
    "H12": "CAVAN",
    "H14": "CAVAN",
    "H16": "CAVAN",
    "H18": "MONAGHAN",
    "H23": "MONAGHAN",
    "H53": "GALWAY",
    "H54": "GALWAY",
    "H62": "GALWAY",
    "H65": "GALWAY",
    "H71": "GALWAY",
    "H91": "GALWAY",
    "K32": "DUBLIN",
    "K34": "DUBLIN",
    "K36": "DUBLIN",
    "K45": "DUBLIN",
    "K56": "DUBLIN",
    "K67": "DUBLIN",
    "K78": "DUBLIN",
    "N37": "WESTMEATH",
    "N39": "LONGFORD",
    "N41": "LEITRIM",
    "N91": "WESTMEATH",
    "P12": "CORK",
    "P14": "CORK",
    "P17": "CORK",
    "P24": "CORK",
    "P25": "CORK",
    "P31": "CORK",
    "P32": "CORK",
    "P36": "CORK",
    "P43": "CORK",
    "P47": "CORK",
    "P51": "CORK",
    "P56": "CORK",
    "P61": "CORK",
    "P67": "CORK",
    "P72": "CORK",
    "P75": "CORK",
    "P81": "CORK",
    "P85": "CORK",
    "R14": "KILDARE",
    "R21": "CARLOW",
    "R32": "LAOIS",
    "R35": "OFFALY",
    "R42": "OFFALY",
    "R45": "MEATH",
    "R51": "KILDARE",
    "R56": "KILDARE",
    "R93": "CARLOW",
    "R95": "KILKENNY",
    "T12": "CORK",
    "T23": "CORK",
    "T34": "CORK",
    "T45": "CORK",
    "T56": "CORK",
    "V14": "CLARE",
    "V15": "CLARE",
    "V23": "KERRY",
    "V31": "KERRY",
    "V35": "LIMERICK",
    "V42": "LIMERICK",
    "V92": "KERRY",
    "V93": "KERRY",
    "V94": "LIMERICK",
    "V95": "CLARE",
    "W12": "KILDARE",
    "W23": "KILDARE",
    "W34": "KILDARE",
    "W91": "KILDARE",
    "X35": "WATERFORD",
    "X42": "WATERFORD",
    "X91": "WATERFORD",
    "Y14": "WICKLOW",
    "Y21": "WEXFORD",
    "Y25": "WEXFORD",
    "Y34": "WEXFORD",
    "Y35": "WEXFORD",
}
