CREATE OR REPLACE PROCEDURE public.sp_truncate_and_insert_ae_zoominfo_standard_us()

    LANGUAGE plpgsql
AS

$$
BEGIN
    -- Step 4: https://worth-ai.atlassian.net/browse/INFRA-55
    DROP TABLE IF EXISTS datascience.ae_zoominfo_standard_us;

    CREATE TABLE
        datascience.ae_zoominfo_standard_us DISTSTYLE EVEN
                                            INTERLEAVED SORTKEY
                                                (
                                                zi_c_location_id,
                                                zi_c_company_id,
                                                zi_es_location_id
                                                ) AS
    SELECT
        zi_c_location_id,
        zi_c_company_id,
        zi_es_location_id,
        zi_c_name,
        zi_c_name_display,
        zi_c_names_other,
        zi_c_url,
        zi_c_street,
        zi_c_street_2,
        zi_c_city,
        zi_c_state,
        zi_c_zip,
        zi_c_country,
        zi_c_county,
        zi_c_latitude,
        zi_c_longitude,
        zi_c_year_founded,
        zi_c_phone,
        zi_c_fax,
        zi_c_ein,

        UPPER(REGEXP_REPLACE(zi_c_name, '[^a-zA-Z0-9 ]', ''))             AS zi_eng_companyname,
        UPPER(REGEXP_REPLACE(zi_c_name_display, '[^a-zA-Z0-9 ]', ''))     AS zi_eng_dba,
        UPPER(REGEXP_REPLACE(zi_c_names_other, '[^a-zA-Z0-9 ]', ''))      AS zi_eng_dba2,
        REPLACE(REPLACE(REPLACE(
                                UPPER(TRIM(zi_c_url))
                            , 'WWW.', '')
                    , 'HTTPS://', '')
            , 'HTTP://', '')
                                                                          AS zi_eng_website,
        REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                                                                                                                        REPLACE(
                                                                                                                                REPLACE(
                                                                                                                                        REPLACE(
                                                                                                                                                REPLACE(
                                                                                                                                                        REPLACE(
                                                                                                                                                                REPLACE(
                                                                                                                                                                        REPLACE(
                                                                                                                                                                                REPLACE(
                                                                                                                                                                                        REPLACE(
                                                                                                                                                                                                REPLACE(
                                                                                                                                                                                                        REPLACE(
                                                                                                                                                                                                                REPLACE(
                                                                                                                                                                                                                        REPLACE(
                                                                                                                                                                                                                                REPLACE(
                                                                                                                                                                                                                                        REPLACE(
                                                                                                                                                                                                                                                REPLACE(
                                                                                                                                                                                                                                                        REPLACE(
                                                                                                                                                                                                                                                                REPLACE(
                                                                                                                                                                                                                                                                        REPLACE(
                                                                                                                                                                                                                                                                                REPLACE(
                                                                                                                                                                                                                                                                                        REPLACE(
                                                                                                                                                                                                                                                                                                REPLACE(
                                                                                                                                                                                                                                                                                                        REPLACE(
                                                                                                                                                                                                                                                                                                                REPLACE(
                                                                                                                                                                                                                                                                                                                        REPLACE(
                                                                                                                                                                                                                                                                                                                                REPLACE(
                                                                                                                                                                                                                                                                                                                                        REPLACE(
                                                                                                                                                                                                                                                                                                                                                REPLACE(
                                                                                                                                                                                                                                                                                                                                                        REPLACE(
                                                                                                                                                                                                                                                                                                                                                                REPLACE(
                                                                                                                                                                                                                                                                                                                                                                        REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                        REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                        REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                        REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                        REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                        REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        UPPER(REGEXP_REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                REGEXP_REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        CONCAT(CONCAT(zi_c_street, ' '), zi_c_street_2),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        '[^a-zA-Z0-9 ]',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ''),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                '([0-9]+)[A-Z]{2}',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                '$1')),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ' AVE ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ' AVENUE '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ' APT ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ' '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ' STE ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ' '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ' BLVD ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ' BOULEVARD '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ' CIR ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ' CIRCLE '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ' CT ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ' COURT '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ' DR ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ' DRIVE '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ' HWY ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ' HIGHWAY '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ' LN ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ' LANE '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ' PKWY ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ' PARKWAY '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ' PL ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ' PLACE '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ' RD ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ' ROAD '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ' SQ ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ' SQUARE '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ' ST ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ' STREET '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ' TER ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ' TERRACE '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                ' WAY ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                ' WAY '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                        ' ALY ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                        ' ALLEY '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                ' BCH ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                ' BEACH '),
                                                                                                                                                                                                                                                                                                                                                                                                                                        ' BND ',
                                                                                                                                                                                                                                                                                                                                                                                                                                        ' BEND '),
                                                                                                                                                                                                                                                                                                                                                                                                                                ' BRG ',
                                                                                                                                                                                                                                                                                                                                                                                                                                ' BRIDGE '),
                                                                                                                                                                                                                                                                                                                                                                                                                        ' BRK ',
                                                                                                                                                                                                                                                                                                                                                                                                                        ' BROOK '),
                                                                                                                                                                                                                                                                                                                                                                                                                ' BYU ',
                                                                                                                                                                                                                                                                                                                                                                                                                ' BAYOU '),
                                                                                                                                                                                                                                                                                                                                                                                                        ' CMN ',
                                                                                                                                                                                                                                                                                                                                                                                                        ' COMMON '),
                                                                                                                                                                                                                                                                                                                                                                                                ' CPE ',
                                                                                                                                                                                                                                                                                                                                                                                                ' CAPE '),
                                                                                                                                                                                                                                                                                                                                                                                        ' CRK ',
                                                                                                                                                                                                                                                                                                                                                                                        ' CREEK '),
                                                                                                                                                                                                                                                                                                                                                                                ' CRST ',
                                                                                                                                                                                                                                                                                                                                                                                ' CREST '),
                                                                                                                                                                                                                                                                                                                                                                        ' XING ',
                                                                                                                                                                                                                                                                                                                                                                        ' CROSSING '),
                                                                                                                                                                                                                                                                                                                                                                ' DM ',
                                                                                                                                                                                                                                                                                                                                                                ' DAM '),
                                                                                                                                                                                                                                                                                                                                                        ' EXPY ',
                                                                                                                                                                                                                                                                                                                                                        ' EXPRESSWAY '),
                                                                                                                                                                                                                                                                                                                                                ' FLD ',
                                                                                                                                                                                                                                                                                                                                                ' FIELD '),
                                                                                                                                                                                                                                                                                                                                        ' FWY ',
                                                                                                                                                                                                                                                                                                                                        ' FREEWAY '),
                                                                                                                                                                                                                                                                                                                                ' GDNS ',
                                                                                                                                                                                                                                                                                                                                ' GARDENS '),
                                                                                                                                                                                                                                                                                                                        ' GLN ',
                                                                                                                                                                                                                                                                                                                        ' GLEN '),
                                                                                                                                                                                                                                                                                                                ' GRN ',
                                                                                                                                                                                                                                                                                                                ' GREEN '),
                                                                                                                                                                                                                                                                                                        ' GRV ',
                                                                                                                                                                                                                                                                                                        ' GROVE '),
                                                                                                                                                                                                                                                                                                ' HOLW ',
                                                                                                                                                                                                                                                                                                ' HOLLOW '),
                                                                                                                                                                                                                                                                                        ' HTS ',
                                                                                                                                                                                                                                                                                        ' HEIGHTS '),
                                                                                                                                                                                                                                                                                ' ISLE ',
                                                                                                                                                                                                                                                                                ' ISLE '),
                                                                                                                                                                                                                                                                        ' JCT ',
                                                                                                                                                                                                                                                                        ' JUNCTION '),
                                                                                                                                                                                                                                                                ' LNDG ',
                                                                                                                                                                                                                                                                ' LANDING '),
                                                                                                                                                                                                                                                        ' LK ',
                                                                                                                                                                                                                                                        ' LAKE '),
                                                                                                                                                                                                                                                ' LGT ',
                                                                                                                                                                                                                                                ' LIGHT '),
                                                                                                                                                                                                                                        ' MDWS ',
                                                                                                                                                                                                                                        ' MEADOWS '),
                                                                                                                                                                                                                                ' MNR ',
                                                                                                                                                                                                                                ' MANOR '),
                                                                                                                                                                                                                        ' MTN ',
                                                                                                                                                                                                                        ' MOUNTAIN '),
                                                                                                                                                                                                                ' MTWY ',
                                                                                                                                                                                                                ' MOTORWAY '),
                                                                                                                                                                                                        ' PASS ',
                                                                                                                                                                                                        ' PASS '),
                                                                                                                                                                                                ' PT ',
                                                                                                                                                                                                ' POINT '),
                                                                                                                                                                                        ' RADL ',
                                                                                                                                                                                        ' RADIAL '),
                                                                                                                                                                                ' RCH ',
                                                                                                                                                                                ' REACH '),
                                                                                                                                                                        ' RST ',
                                                                                                                                                                        ' REST '),
                                                                                                                                                                ' SHRS ',
                                                                                                                                                                ' SHORES '),
                                                                                                                                                        ' SPG ',
                                                                                                                                                        ' SPRING '),
                                                                                                                                                ' SQ ',
                                                                                                                                                ' SQUARE '),
                                                                                                                                        ' STA ',
                                                                                                                                        ' STATION '),
                                                                                                                                ' TRCE ',
                                                                                                                                ' TRACE '),
                                                                                                                        ' TRL ',
                                                                                                                        ' TRAIL '),
                                                                                                                ' TRFY ',
                                                                                                                ' TRAFFICWAY '),
                                                                                                        ' TUNN ',
                                                                                                        ' TUNNEL '),
                                                                                                ' VLY ', ' VALLEY '),
                                                                                        ' VW ', ' VIEW '), ' XING ',
                                                                                ' CROSSING '), ' S ', ' SOUTH '), ' N ',
                                                                ' NORTH '), ' W ', ' WEST '), ' E ', ' EAST '), ' SE ',
                                        ' SOUTHEAST '), ' NE ', ' NORTHEAST '), ' SW ', ' SOUTHWEST '), ' NW ',
                ' NORTHWEST ')                                            AS zi_eng_address,
        REGEXP_SUBSTR(zi_c_street, '^[0-9]+')                             AS zi_eng_street_num,
        state_code                                                        AS zi_eng_state,
        UPPER(zi_c_city)                                                  AS zi_eng_city,
        LPAD(SPLIT_PART(TRIM(zi_c_zip), '-', 1), 5, '0')                  AS zi_eng_zipcode,
        SUBSTRING(LPAD(SPLIT_PART(TRIM(zi_c_zip), '-', 1), 5, '0'), 1, 3) AS zi_eng_zipcode_threedigits,
        LPAD(SPLIT_PART(TRIM(zi_c_zip), '-', 2), 4, '0')                  AS zi_eng_zip4,
        UPPER(zi_c_county)                                                AS zi_eng_county,
        UPPER(zi_c_country)                                               AS zi_eng_country,
        LTRIM(REGEXP_SUBSTR(zi_c_phone, ' [0-9]+'))                       AS zi_eng_phone_number,
        REGEXP_SUBSTR(zi_c_phone, '\\+[0-9]+')                            AS zi_eng_phone_countrycode,
        LTRIM(REGEXP_SUBSTR(zi_c_fax, ' [0-9]+'))                         AS zi_eng_fax_number,
        REGEXP_SUBSTR(zi_c_fax, '\\+[0-9]+')                              AS zi_eng_fax_countrycode


    FROM zoominfo.comp_standard_global
        LEFT JOIN state_lookup
                ON UPPER(comp_standard_global.zi_c_state) = state_lookup.state_name_upper

    WHERE zi_c_country = 'United States';

END
$$
