CREATE OR REPLACE PROCEDURE public.sp_truncate_and_insert_equifax_us_standardized()
    LANGUAGE plpgsql
AS
$$
BEGIN

    DROP TABLE IF EXISTS warehouse.equifax_us_standardized;


    CREATE TABLE warehouse.equifax_us_standardized DISTSTYLE EVEN
        INTERLEAVED SORTKEY (efx_id, efx_eng_companyname, efx_eng_address, efx_eng_city, efx_eng_state, efx_eng_zipcode)
    AS
    WITH
        latest_year_mon AS (SELECT
                                efx_id,
                                MAX(TO_DATE(equifax_us_raw.yr || '-' || equifax_us_raw.mon || '-01',
                                            'YYYY-MM-DD')) AS max_date
                            FROM warehouse.equifax_us_raw
                            GROUP BY
                                efx_id

        ),

        base_data AS (SELECT DISTINCT
                          -- ORIGINAL FIELDS
                          equifax_us_raw.efx_id,
                          equifax_us_raw.yr,
                          equifax_us_raw.mon,
                          public.sanitize_business_name(efx_name)                          AS efx_name,
                          public.sanitize_business_name(efx_legal_name)                    AS efx_legal_name,
                          efx_address,
                          efx_city,
                          efx_state,
                          efx_zipcode,
                          efx_zip4,
                          efx_phone,
                          efx_faxphone,
                          efx_contct,
                          efx_lastnam,
                          efx_fstnam,
                          efx_email,
                          efx_ceoname,
                          efx_cioname,
                          efx_cfoname,
                          efx_web,
                          efx_yrest,

                          -- ENGINEERED FIELDS
                          -- Company Name
                          public.canonize_business_name(efx_name)                          AS efx_eng_companyname,
                          SUBSTRING(public.canonize_business_name(efx_name), 1, 1)         AS efx_eng_companyname_firstletter,
                          public.canonize_business_name(efx_legal_name)                    AS efx_eng_legalname,
                          SUBSTRING(public.canonize_business_name(efx_legal_name), 1, 1)   AS efx_eng_legalname_firstletter,
                          REPLACE(REPLACE(REPLACE(UPPER(TRIM(efx_web)), 'WWW.', ''), 'HTTPS://', ''), 'HTTP://',
                                  '')                                                      AS efx_eng_website,
                          TRIM(efx_yrest)                                                  AS efx_eng_yearestablished,

                          -- Company Address
                          REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                                                                                                                  REPLACE(
                                                                                                                          REPLACE(
                                                                                                                                  REPLACE(
                                                                                                                                          REPLACE(
                                                                                                                                                  REPLACE(
                                                                                                                                                          REPLACE(
                                                                                                                                                                  REPLACE(
                                                                                                                                                                          REPLACE(
                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          UPPER(REGEXP_REPLACE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  REGEXP_REPLACE(efx_address, '[^a-zA-Z0-9 ]', ''),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  '([0-9]+)[A-Z]{2}',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  '$1')),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ' AVE ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ' AVENUE '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ' APT ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ' '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ' STE ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ' '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ' BLVD ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ' BOULEVARD '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ' CIR ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ' CIRCLE '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ' CT ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ' COURT '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ' DR ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ' DRIVE '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ' HWY ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ' HIGHWAY '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ' LN ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ' LANE '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ' PKWY ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ' PARKWAY '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ' PL ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ' PLACE '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ' RD ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ' ROAD '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ' SQ ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ' SQUARE '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ' ST ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ' STREET '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ' TER ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ' TERRACE '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ' WAY ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ' WAY '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ' ALY ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ' ALLEY '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ' BCH ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ' BEACH '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                          ' BND ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                          ' BEND '),
                                                                                                                                                                                                                                                                                                                                                                                                                                                  ' BRG ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                  ' BRIDGE '),
                                                                                                                                                                                                                                                                                                                                                                                                                                          ' BRK ',
                                                                                                                                                                                                                                                                                                                                                                                                                                          ' BROOK '),
                                                                                                                                                                                                                                                                                                                                                                                                                                  ' BYU ',
                                                                                                                                                                                                                                                                                                                                                                                                                                  ' BAYOU '),
                                                                                                                                                                                                                                                                                                                                                                                                                          ' CMN ',
                                                                                                                                                                                                                                                                                                                                                                                                                          ' COMMON '),
                                                                                                                                                                                                                                                                                                                                                                                                                  ' CPE ',
                                                                                                                                                                                                                                                                                                                                                                                                                  ' CAPE '),
                                                                                                                                                                                                                                                                                                                                                                                                          ' CRK ',
                                                                                                                                                                                                                                                                                                                                                                                                          ' CREEK '),
                                                                                                                                                                                                                                                                                                                                                                                                  ' CRST ',
                                                                                                                                                                                                                                                                                                                                                                                                  ' CREST '),
                                                                                                                                                                                                                                                                                                                                                                                          ' XING ',
                                                                                                                                                                                                                                                                                                                                                                                          ' CROSSING '),
                                                                                                                                                                                                                                                                                                                                                                                  ' DM ',
                                                                                                                                                                                                                                                                                                                                                                                  ' DAM '),
                                                                                                                                                                                                                                                                                                                                                                          ' EXPY ',
                                                                                                                                                                                                                                                                                                                                                                          ' EXPRESSWAY '),
                                                                                                                                                                                                                                                                                                                                                                  ' FLD ',
                                                                                                                                                                                                                                                                                                                                                                  ' FIELD '),
                                                                                                                                                                                                                                                                                                                                                          ' FWY ',
                                                                                                                                                                                                                                                                                                                                                          ' FREEWAY '),
                                                                                                                                                                                                                                                                                                                                                  ' GDNS ',
                                                                                                                                                                                                                                                                                                                                                  ' GARDENS '),
                                                                                                                                                                                                                                                                                                                                          ' GLN ',
                                                                                                                                                                                                                                                                                                                                          ' GLEN '),
                                                                                                                                                                                                                                                                                                                                  ' GRN ',
                                                                                                                                                                                                                                                                                                                                  ' GREEN '),
                                                                                                                                                                                                                                                                                                                          ' GRV ',
                                                                                                                                                                                                                                                                                                                          ' GROVE '),
                                                                                                                                                                                                                                                                                                                  ' HOLW ',
                                                                                                                                                                                                                                                                                                                  ' HOLLOW '),
                                                                                                                                                                                                                                                                                                          ' HTS ',
                                                                                                                                                                                                                                                                                                          ' HEIGHTS '),
                                                                                                                                                                                                                                                                                                  ' ISLE ',
                                                                                                                                                                                                                                                                                                  ' ISLE '),
                                                                                                                                                                                                                                                                                          ' JCT ',
                                                                                                                                                                                                                                                                                          ' JUNCTION '),
                                                                                                                                                                                                                                                                                  ' LNDG ',
                                                                                                                                                                                                                                                                                  ' LANDING '),
                                                                                                                                                                                                                                                                          ' LK ',
                                                                                                                                                                                                                                                                          ' LAKE '),
                                                                                                                                                                                                                                                                  ' LGT ',
                                                                                                                                                                                                                                                                  ' LIGHT '),
                                                                                                                                                                                                                                                          ' MDWS ',
                                                                                                                                                                                                                                                          ' MEADOWS '),
                                                                                                                                                                                                                                                  ' MNR ',
                                                                                                                                                                                                                                                  ' MANOR '),
                                                                                                                                                                                                                                          ' MTN ',
                                                                                                                                                                                                                                          ' MOUNTAIN '),
                                                                                                                                                                                                                                  ' MTWY ',
                                                                                                                                                                                                                                  ' MOTORWAY '),
                                                                                                                                                                                                                          ' PASS ',
                                                                                                                                                                                                                          ' PASS '),
                                                                                                                                                                                                                  ' PT ',
                                                                                                                                                                                                                  ' POINT '),
                                                                                                                                                                                                          ' RADL ',
                                                                                                                                                                                                          ' RADIAL '),
                                                                                                                                                                                                  ' RCH ',
                                                                                                                                                                                                  ' REACH '),
                                                                                                                                                                                          ' RST ',
                                                                                                                                                                                          ' REST '),
                                                                                                                                                                                  ' SHRS ',
                                                                                                                                                                                  ' SHORES '),
                                                                                                                                                                          ' SPG ',
                                                                                                                                                                          ' SPRING '),
                                                                                                                                                                  ' SQ ',
                                                                                                                                                                  ' SQUARE '),
                                                                                                                                                          ' STA ',
                                                                                                                                                          ' STATION '),
                                                                                                                                                  ' TRCE ',
                                                                                                                                                  ' TRACE '),
                                                                                                                                          ' TRL ',
                                                                                                                                          ' TRAIL '),
                                                                                                                                  ' TRFY ',
                                                                                                                                  ' TRAFFICWAY '),
                                                                                                                          ' TUNN ',
                                                                                                                          ' TUNNEL '),
                                                                                                                  ' VLY ',
                                                                                                                  ' VALLEY '),
                                                                                                          ' VW ',
                                                                                                          ' VIEW '),
                                                                                                  ' XING ',
                                                                                                  ' CROSSING '),
                                                                                          ' S ', ' SOUTH '), ' N ',
                                                                                  ' NORTH '), ' W ', ' WEST '), ' E ',
                                                                  ' EAST '), ' SE ', ' SOUTHEAST '), ' NE ',
                                                  ' NORTHEAST '),
                                          ' SW ', ' SOUTHWEST '), ' NW ', ' NORTHWEST ')   AS efx_eng_address,
                          REGEXP_SUBSTR(efx_address, '^[0-9]+')                            AS efx_eng_street_num,
                          UPPER(efx_city)                                                  AS efx_eng_city,
                          LPAD(TRIM(efx_zipcode), 5, '0')                                  AS efx_eng_zipcode,
                          SUBSTRING(LPAD(TRIM(efx_zipcode), 5, '0'), 1, 3)                 AS efx_eng_zipcode_threedigits,
                          LPAD(TRIM(efx_zip4), 4, '0')                                     AS efx_eng_zip4,

                          -- Company Phone and Fax Numbers
                          REPLACE(TRIM(efx_phone), ' ', '')                                AS efx_eng_phone,
                          SUBSTRING(TRIM(efx_phone), LENGTH(TRIM(efx_phone)) - 9, 3)       AS efx_eng_phone_areacode,
                          SUBSTRING(TRIM(efx_phone), LENGTH(TRIM(efx_phone)) - 6, 3)       AS efx_eng_phone_centraloffice,
                          SUBSTRING(TRIM(efx_phone), LENGTH(TRIM(efx_phone)) - 3, 4)       AS efx_eng_phone_linenumber,
                          REPLACE(TRIM(efx_faxphone), ' ', '')                             AS efx_eng_fax,
                          SUBSTRING(TRIM(efx_faxphone), LENGTH(TRIM(efx_faxphone)) - 9, 3) AS efx_eng_fax_areacode,
                          SUBSTRING(TRIM(efx_faxphone), LENGTH(TRIM(efx_faxphone)) - 6, 3) AS
                                                                                              efx_eng_fax_centraloffice,
                          SUBSTRING(TRIM(efx_faxphone), LENGTH(TRIM(efx_faxphone)) - 3, 4) AS
                                                                                              efx_eng_fax_linenumber,

                          -- Company Contact Information
                          UPPER(REGEXP_SUBSTR(efx_contct, '^[0-9]+'))                      AS efx_eng_contact,
                          UPPER(REGEXP_SUBSTR(efx_lastnam, '^[0-9]+'))                     AS efx_eng_contact_lastname,
                          UPPER(REGEXP_SUBSTR(efx_fstnam, '^[0-9]+'))                      AS efx_eng_contact_firstname,
                          UPPER(efx_email)                                                 AS efx_eng_email,
                          REGEXP_SUBSTR(efx_ceoname, '^[^ ]+')                             AS efx_eng_ceo_firstname,
                          REGEXP_SUBSTR(efx_ceoname, '[^ ]+$')                             AS efx_eng_ceo_lastname,
                          REGEXP_SUBSTR(efx_cioname, '^[^ ]+')                             AS efx_eng_cio_firstname,
                          REGEXP_SUBSTR(efx_cioname, '[^ ]+$')                             AS efx_eng_cio_lastname,
                          REGEXP_SUBSTR(efx_cfoname, '^[^ ]+')                             AS efx_eng_cfo_firstname,
                          REGEXP_SUBSTR(efx_cfoname, '[^ ]+$')                             AS efx_eng_cfo_lastname
                      FROM warehouse.equifax_us_raw
                          INNER JOIN latest_year_mon
                                  ON equifax_us_raw.efx_id = latest_year_mon.efx_id
                              AND TO_DATE(equifax_us_raw.yr || '-' || equifax_us_raw.mon || '-01', 'YYYY-MM-DD') =
                                  max_date
        )
    SELECT
        bd.efx_id,
        bd.efx_name,
        bd.efx_legal_name,
        bd.efx_address,
        bd.efx_city,
        bd.efx_state,
        bd.efx_zipcode,
        bd.efx_zip4,
        bd.efx_phone,
        bd.efx_faxphone,
        bd.efx_contct,
        bd.efx_lastnam,
        bd.efx_fstnam,
        bd.efx_email,
        bd.efx_ceoname,
        bd.efx_cioname,
        bd.efx_cfoname,
        bd.efx_web,
        bd.efx_yrest,
        bd.efx_eng_companyname,
        bd.efx_eng_companyname_firstletter,
        bd.efx_eng_legalname,
        bd.efx_eng_legalname_firstletter,
        bd.efx_eng_website,
        bd.efx_eng_yearestablished,
        bd.efx_eng_address,
        bd.efx_eng_street_num,
        bd.efx_eng_city,
        bd.efx_eng_zipcode,
        bd.efx_eng_zipcode_threedigits,
        bd.efx_eng_zip4,
        bd.efx_eng_phone,
        bd.efx_eng_phone_areacode,
        bd.efx_eng_phone_centraloffice,
        bd.efx_eng_phone_linenumber,
        bd.efx_eng_fax,
        bd.efx_eng_fax_areacode,
        bd.efx_eng_fax_centraloffice,
        bd.efx_eng_fax_linenumber,
        bd.efx_eng_contact,
        bd.efx_eng_contact_lastname,
        bd.efx_eng_contact_firstname,
        bd.efx_eng_email,
        bd.efx_eng_ceo_firstname,
        bd.efx_eng_ceo_lastname,
        bd.efx_eng_cio_firstname,
        bd.efx_eng_cio_lastname,
        bd.efx_eng_cfo_firstname,
        bd.efx_eng_cfo_lastname,
        TO_DATE(yr || '-' || mon || '-01', 'YYYY-MM-DD') AS efx_date,
        UPPER(efx_state)                                 AS efx_eng_state

    FROM base_data AS bd;

    GRANT ALL ON TABLE warehouse.equifax_us_standardized TO GROUP worth_ds;
END
$$
