CREATE OR REPLACE PROCEDURE public.sp_recreate_smb_pr_verification_cs()
    LANGUAGE plpgsql
AS

$$
BEGIN

    DROP TABLE IF EXISTS datascience.smb_pr_verification_cs;

    CREATE TABLE datascience.smb_pr_verification_cs DISTKEY (business_id) AS
    WITH
        latest_scores AS (SELECT
                              customer_id,
                              business_id,
                              score_id,
                              created_at,
                              weighted_score_100 / 100                                                           AS score_prob,
                              weighted_score_850                                                                 AS score_worth,
                              ROW_NUMBER() OVER (PARTITION BY customer_id, business_id ORDER BY created_at DESC) AS rn
                          FROM rds_manual_score_public.data_current_scores AS cs
                              JOIN
                          rds_manual_score_public.business_scores AS bs
                                      ON cs.score_id = bs.id
        ),
        score_components AS (SELECT
                                 bs.business_id,
                                 bs.score_worth AS worth_score,
                                 bs.score_worth
                                     -
                                 SUM(CASE WHEN cat.label = 'Financial Trends' THEN sf.weighted_score_850 ELSE 0 END)
                                     - SUM(CASE WHEN cat.label = 'Public Records' THEN sf.weighted_score_850 ELSE 0 END)
                                     -
                                 SUM(CASE WHEN cat.label = 'Business Operations' THEN sf.weighted_score_850 ELSE 0 END)
                                     -
                                 SUM(CASE WHEN cat.label = 'Company Profile' THEN sf.weighted_score_850 ELSE 0 END)
                                     - SUM(CASE
                                               WHEN cat.label = 'Performance Measures' THEN sf.weighted_score_850
                                               ELSE 0
                                           END) AS score_base_value,
                                 SUM(CASE
                                         WHEN cat.label = 'Financial Trends' THEN sf.weighted_score_850
                                         ELSE 0
                                     END)       AS score_financial_trends,
                                 SUM(CASE
                                         WHEN cat.label = 'Public Records' THEN sf.weighted_score_850
                                         ELSE 0
                                     END)       AS score_public_records,
                                 SUM(CASE
                                         WHEN cat.label = 'Business Operations' THEN sf.weighted_score_850
                                         ELSE 0
                                     END)       AS score_business_operations,
                                 SUM(CASE
                                         WHEN cat.label = 'Company Profile' THEN sf.weighted_score_850
                                         ELSE 0
                                     END)       AS score_company_profile,
                                 SUM(CASE
                                         WHEN cat.label = 'Performance Measures' THEN sf.weighted_score_850
                                         ELSE 0
                                     END)       AS score_performance_measures
                             FROM rds_manual_score_public.business_score_factors AS sf
                                 JOIN
                             latest_scores AS bs
                                         ON sf.score_id = bs.score_id
                                 JOIN
                             rds_manual_score_public.score_categories AS cat
                                         ON sf.category_id = cat.id
                                 JOIN
                             rds_manual_score_public.score_category_factors AS fac
                                         ON sf.factor_id = fac.id
                             WHERE sf.version = 2.2
                             GROUP BY
                                 bs.business_id,
                                 bs.score_worth
        )

    SELECT DISTINCT
        smb.business_id,
        smb.latest_requested_at,
        smb.customer_unique_identifier,
        smb.company_name,
        smb.company_dba,
        smb.tax_id,
        smb.company_address,
        smb.company_address_2,
        smb.company_city,
        smb.company_state,
        smb.company_postalcode,
        smb.annual_income,
        smb.rn,
        smb.efx_id,
        smb.efx_match_confidence,
        smb.efx_name,
        smb.efx_legal_name,
        smb.efx_address,
        smb.efx_city,
        smb.efx_state,
        smb.efx_statec,
        smb.efx_zipcode,
        smb.efx_zip4,
        smb.efx_lat,
        smb.efx_lon,
        smb.efx_geoprec,
        smb.efx_region,
        smb.efx_ctryisocd,
        smb.efx_ctrynum,
        smb.efx_ctryname,
        smb.efx_countynm,
        smb.efx_county,
        smb.efx_cmsa,
        smb.efx_cmsadesc,
        smb.efx_soho,
        smb.efx_biz,
        smb.efx_res,
        smb.efx_cmra,
        smb.efx_congress,
        smb.efx_secadr,
        smb.efx_seccty,
        smb.efx_secstat,
        smb.efx_statec2,
        smb.efx_seczip,
        smb.efx_seczip4,
        smb.efx_seclat,
        smb.efx_seclon,
        smb.efx_secgeoprec,
        smb.efx_secregion,
        smb.efx_secctryisocd,
        smb.efx_secctrynum,
        smb.efx_secctryname,
        smb.efx_ctrytelcd,
        smb.efx_phone,
        smb.efx_faxphone,
        smb.efx_contct,
        smb.efx_titlecd,
        smb.efx_titledesc,
        smb.efx_lastnam,
        smb.efx_fstnam,
        smb.efx_email,
        smb.efx_ceoname,
        smb.efx_ceotitledesc,
        smb.efx_cioname,
        smb.efx_ciotitledesc,
        smb.efx_cfoname,
        smb.efx_cfotitledesc,
        smb.efx_gender,
        smb.efx_ethnicity,
        smb.efx_mbe,
        smb.efx_wbe,
        smb.efx_vet,
        smb.efx_bussize,
        smb.efx_gov,
        smb.efx_fgov,
        smb.efx_nonprofit,
        smb.efx_edu,
        smb.efx_busstat,
        smb.efx_busstatcd,
        smb.efx_web,
        smb.efx_yrest,
        smb.efx_corpempcnt,
        smb.efx_locempcnt,
        smb.efx_corpempcd,
        smb.efx_locempcd,
        smb.efx_corpamount,
        smb.efx_corpamountcd,
        smb.efx_corpamounttp,
        smb.efx_corpamountprec,
        smb.efx_locamount,
        smb.efx_locamountcd,
        smb.efx_locamounttp,
        smb.efx_locamountprec,
        smb.efx_public,
        smb.efx_stkexc,
        smb.efx_tcksym,
        smb.efx_primsic,
        smb.efx_secsic1,
        smb.efx_secsic2,
        smb.efx_secsic3,
        smb.efx_secsic4,
        smb.efx_primsicdesc,
        smb.efx_secsicdesc1,
        smb.efx_secsicdesc2,
        smb.efx_secsicdesc3,
        smb.efx_secsicdesc4,
        smb.efx_primnaicscode,
        smb.efx_secnaics1,
        smb.efx_secnaics2,
        smb.efx_secnaics3,
        smb.efx_secnaics4,
        smb.efx_primnaicsdesc,
        smb.efx_secnaicsdesc1,
        smb.efx_secnaicsdesc2,
        smb.efx_secnaicsdesc3,
        smb.efx_secnaicsdesc4,
        smb.efx_legsubnumall,
        smb.efx_legsubnameall,
        smb.efx_legsubaddressall,
        smb.efx_legsubcityall,
        smb.efx_legsubstateall,
        smb.efx_legsubzipcodeall,
        smb.efx_legsubzip4all,
        smb.efx_legsubcountyall,
        smb.efx_legsubctryisocdall,
        smb.efx_legsubctrynumall,
        smb.efx_legsubctrynameall,
        smb.efx_legdomultnumall,
        smb.efx_legdomultnameall,
        smb.efx_legdomultaddressall,
        smb.efx_legdomultcityall,
        smb.efx_legdomultstateall,
        smb.efx_legdomultzipcodeall,
        smb.efx_legdomultzip4all,
        smb.efx_legdomultcountyall,
        smb.efx_legdomultctryisocdall,
        smb.efx_legdomultctrynumall,
        smb.efx_legdomultctrynameall,
        smb.efx_legultnumall,
        smb.efx_legultnameall,
        smb.efx_legultaddressall,
        smb.efx_legultcityall,
        smb.efx_legultstateall,
        smb.efx_legultzipcodeall,
        smb.efx_legultzip4all,
        smb.efx_legultcountyall,
        smb.efx_legultctryisocdall,
        smb.efx_legultctrynumall,
        smb.efx_legultctrynameall,
        smb.efx_legultparentind,
        smb.efx_legparentind,
        smb.efx_leglinkedind,
        smb.efx_afflultnumall,
        smb.efx_afflultnameall,
        smb.efx_afflultaddressall,
        smb.efx_afflultcityall,
        smb.efx_afflultstateall,
        smb.efx_afflultzipcodeall,
        smb.efx_afflultzip4all,
        smb.efx_affultcountyall,
        smb.efx_afflultctryisocdall,
        smb.efx_afflultctrynumall,
        smb.efx_afflultctrynameall,
        smb.efx_affllinkedind,
        smb.efx_franchise,
        smb.efx_afflultparentind,
        smb.efx_afflparentind,
        smb.efx_foreign,
        smb.efx_failrate,
        smb.efx_faillevel,
        smb.efx_failreason1,
        smb.efx_failreason2,
        smb.efx_failreason3,
        smb.efx_failreason4,
        smb.efx_creditscore,
        smb.efx_creditclass,
        smb.efx_creditperc,
        smb.efx_creditreason1,
        smb.efx_creditreason2,
        smb.efx_creditreason3,
        smb.efx_creditreason4,
        smb.efx_bankruptcy,
        smb.efx_dead,
        smb.efx_deaddt,
        smb.efx_mrkt_telever,
        smb.efx_mrkt_telescore,
        smb.efx_mrkt_totalscore,
        smb.efx_mrkt_totalind,
        smb.efx_mrkt_vacant,
        smb.efx_mrkt_seasonal,
        smb.efx_extract_date,
        smb.efx_date_updated,
        smb.currentcty_4_avg,
        smb.currentst_4_avg,
        smb."12monthpriorcty_4_avg",
        smb."12monthpriorst_4_avg",
        smb.efx_merchant_id,
        smb.efx_project_id,
        smb.twelvemonthpriorcty_4_avg,
        smb.twelvemonthpriorst_4_avg,
        smb.efx_mwbe,
        smb.efx_sdb,
        smb.efx_hubzone,
        smb.efx_dbe,
        smb.efx_dvet,
        smb.efx_8a,
        smb.efx_8aexpdt,
        smb.efx_dis,
        smb.efx_sbe,
        smb.efx_hbcu,
        smb.efx_gaylesbian,
        smb.efx_wsbe,
        smb.efx_vsbe,
        smb.efx_dvsbe,
        smb.efx_mwbestatus,
        smb.efx_nmsdc,
        smb.efx_wbenc,
        smb.efx_ca_puc,
        smb.efx_tx_hub,
        smb.efx_tx_hubcertnum,
        smb.efx_gsax,
        smb.efx_caltrans,
        smb.efx_mi,
        smb.efx_anc,
        smb.efx_cert1,
        smb.efx_cert2,
        smb.efx_cert3,
        smb.efx_cert4,
        smb.efx_cert5,
        smb.efx_cert6,
        smb.efx_cert7,
        smb.efx_cert8,
        smb.efx_cert9,
        smb.efx_cert10,
        smb.efx_certdesc1,
        smb.efx_certdesc2,
        smb.efx_certdesc3,
        smb.efx_certdesc4,
        smb.efx_certdesc5,
        smb.efx_certdesc6,
        smb.efx_certdesc7,
        smb.efx_certdesc8,
        smb.efx_certdesc9,
        smb.efx_certdesc10,
        smb.efx_certsrc1,
        smb.efx_certsrc2,
        smb.efx_certsrc3,
        smb.efx_certsrc4,
        smb.efx_certsrc5,
        smb.efx_certsrc6,
        smb.efx_certsrc7,
        smb.efx_certsrc8,
        smb.efx_certsrc9,
        smb.efx_certsrc10,
        smb.efx_certlev1,
        smb.efx_certlev2,
        smb.efx_certlev3,
        smb.efx_certlev4,
        smb.efx_certlev5,
        smb.efx_certlev6,
        smb.efx_certlev7,
        smb.efx_certlev8,
        smb.efx_certlev9,
        smb.efx_certlev10,
        smb.efx_certnum1,
        smb.efx_certnum2,
        smb.efx_certnum3,
        smb.efx_certnum4,
        smb.efx_certnum5,
        smb.efx_certnum6,
        smb.efx_certnum7,
        smb.efx_certnum8,
        smb.efx_certnum9,
        smb.efx_certnum10,
        smb.efx_certexp1,
        smb.efx_certexp2,
        smb.efx_certexp3,
        smb.efx_certexp4,
        smb.efx_certexp5,
        smb.efx_certexp6,
        smb.efx_certexp7,
        smb.efx_certexp8,
        smb.efx_certexp9,
        smb.efx_certexp10,
        smb.efx_legentityparentnum,
        smb.efx_legentityparentname,
        smb.efx_legentitysubsidiaryind,
        smb.efx_legentityind,
        smb.efx_cancreditscorecds,
        smb.efx_cancreditrejcdcds,
        smb.efx_cancreditreason3cds,
        smb.efx_cancreditreason4cds,
        smb.efx_cancreditscorebfrs,
        smb.efx_cancreditrejcdbfrs,
        smb.efx_cancreditreason1bfrs,
        smb.efx_cancreditreason2bfrs,
        smb.efx_cancreditdate,
        smb.efx_affldomultnumall,
        smb.efx_affldomultnameall,
        smb.efx_affldomultaddressall,
        smb.efx_affldomultcityall,
        smb.efx_affldomultstateall,
        smb.efx_affldomultzipcodeall,
        smb.efx_affldomultzip4all,
        smb.efx_affldomultcountyall,
        smb.efx_affldomultctryisocdall,
        smb.efx_affldomultctrynumall,
        smb.efx_affldomultctrynameall,
        smb.efx_lbe,
        smb.efx_gov1057,
        smb.efx_merctype,
--         smb.efxbma_1m_ind_2c_past_due_count,
--         smb.efxbma_1m_ind_2pc_past_due_count,
--         smb.efxbma_1m_ind_3c_past_due_count,
--         smb.efxbma_1m_ind_3pc_past_due_count,
--         smb.efxbma_1m_ind_4pc_past_due_count,
--         smb.efxbma_1m_ind_tr_count,
--         smb.efxbma_1m_ind_tr_total_bal,
--         smb.efxbma_1m_ind_worst_payment_status,
--         smb.efxbma_1m_nfin_1c_past_due_count,
--         smb.efxbma_1m_nfin_1pc_past_due_count,
--         smb.efxbma_1m_nfin_2c_past_due_count,
--         smb.efxbma_1m_nfin_2pc_past_due_count,
--         smb.efxbma_1m_nfin_3c_past_due_count,
--         smb.efxbma_1m_nfin_3pc_past_due_count,
--         smb.efxbma_1m_nfin_4pc_past_due_count,
--         smb.efxbma_1m_nfin_chargeoff_tr_count,
--         smb.efxbma_1m_nfin_closed_acc_count,
--         smb.efxbma_1m_nfin_curr_credit_lim,
--         smb.efxbma_1m_nfin_open_acc_count,
--         smb.efxbma_1m_nfin_orig_credit_lim,
--         smb.efxbma_1m_nfin_past_due_amount,
--         smb.efxbma_1m_nfin_payment_index,
--         smb.efxbma_1m_nfin_per_satisfactory_acc,
--         smb.efxbma_1m_nfin_satisfactory_tr_count,
--         smb.efxbma_1m_nfin_total_chargeoff_amt,
--         smb.efxbma_1m_nfin_total_util,
--         smb.efxbma_1m_nfin_tr_count,
--         smb.efxbma_1m_nfin_tr_total_bal,
--         smb.efxbma_1m_nfin_worst_payment_status,
--         smb.efxbma_1m_serv_tr_count,
--         smb.efxbma_1m_serv_tr_total_bal,
--         smb.efxbma_1m_tel_1c_past_due_count,
--         smb.efxbma_1m_tel_1pc_past_due_count,
--         smb.efxbma_1m_tel_2c_past_due_count,
--         smb.efxbma_1m_tel_2pc_past_due_count,
--         smb.efxbma_1m_tel_3c_past_due_count,
--         smb.efxbma_1m_tel_3pc_past_due_count,
--         smb.efxbma_1m_tel_4pc_past_due_count,
--         smb.efxbma_1m_tel_tr_count,
--         smb.efxbma_1m_tel_tr_total_bal,
--         smb.efxbma_1m_tel_worst_payment_status,
--         smb.efxbma_1m_util_1c_past_due_count,
--         smb.efxbma_1m_util_1pc_past_due_count,
--         smb.efxbma_1m_util_2c_past_due_count,
--         smb.efxbma_1m_util_2pc_past_due_count,
--         smb.efxbma_1m_util_3c_past_due_count,
--         smb.efxbma_1m_util_3pc_past_due_count,
--         smb.efxbma_1m_util_4pc_past_due_count,
--         smb.efxbma_1m_util_tr_count,
--         smb.efxbma_1m_util_tr_total_bal,
--         smb.efxbma_1m_util_worst_payment_status,
--         smb.efxbma_3m_ind_1c_past_due_count,
--         smb.efxbma_3m_ind_1pc_past_due_count,
--         smb.efxbma_3m_ind_2c_past_due_count,
--         smb.efxbma_3m_ind_2pc_past_due_count,
--         smb.efxbma_3m_ind_3c_past_due_count,
--         smb.efxbma_3m_ind_3pc_past_due_count,
--         smb.efxbma_3m_ind_4pc_past_due_count,
--         smb.efxbma_3m_ind_tr_count,
--         smb.efxbma_3m_ind_tr_high_bal,
--         smb.efxbma_3m_ind_tr_wb_count,
--         smb.efxbma_3m_ind_worst_payment_status,
--         smb.efxbma_3m_nfin_1c_past_due_amount,
--         smb.efxbma_3m_nfin_1c_past_due_count,
--         smb.efxbma_3m_nfin_1pc_past_due_count,
--         smb.efxbma_3m_nfin_2c_past_due_amount,
--         smb.efxbma_3m_nfin_2c_past_due_count,
--         smb.efxbma_3m_nfin_2pc_past_due_count,
--         smb.efxbma_3m_nfin_3c_past_due_amount,
--         smb.efxbma_3m_nfin_3c_past_due_count,
--         smb.efxbma_3m_nfin_3pc_past_due_count,
--         smb.efxbma_3m_nfin_4pc_past_due_amount,
--         smb.efxbma_3m_nfin_4pc_past_due_count,
--         smb.efxbma_3m_nfin_chargeoff_tr_count,
--         smb.efxbma_3m_nfin_high_credit_lim,
--         smb.efxbma_3m_nfin_new_acc_count,
--         smb.efxbma_3m_nfin_orig_credit_lim,
--         smb.efxbma_3m_nfin_past_due_amount,
--         smb.efxbma_3m_nfin_per_4pc_pd_to_totbal,
--         smb.efxbma_3m_nfin_per_coff_to_tot_acc,
--         smb.efxbma_3m_nfin_per_pd_to_totbal,
--         smb.efxbma_3m_nfin_per_satisfactory_acc,
--         smb.efxbma_3m_nfin_ratio_num_nondel_to_acc,
--         smb.efxbma_3m_nfin_satisfactory_tr_count,
--         smb.efxbma_3m_nfin_total_chargeoff_amt,
--         smb.efxbma_3m_nfin_total_util,
--         smb.efxbma_3m_nfin_tr_count,
--         smb.efxbma_3m_nfin_tr_high_bal,
--         smb.efxbma_3m_nfin_tr_wb_count,
--         smb.efxbma_3m_nfin_worst_payment_status,
--         smb.efxbma_3m_serv_past_due_amount,
--         smb.efxbma_3m_serv_tr_count,
--         smb.efxbma_3m_serv_tr_high_bal,
--         smb.efxbma_3m_serv_tr_wb_count,
--         smb.efxbma_3m_tel_1c_past_due_count,
--         smb.efxbma_3m_tel_1pc_past_due_count,
--         smb.efxbma_3m_tel_2c_past_due_count,
--         smb.efxbma_3m_tel_2pc_past_due_count,
--         smb.efxbma_3m_tel_3c_past_due_count,
--         smb.efxbma_3m_tel_3pc_past_due_count,
--         smb.efxbma_3m_tel_4pc_past_due_count,
--         smb.efxbma_3m_tel_tr_count,
--         smb.efxbma_3m_tel_tr_high_bal,
--         smb.efxbma_3m_tel_tr_wb_count,
--         smb.efxbma_3m_tel_worst_payment_status,
--         smb.efxbma_3m_util_1c_past_due_count,
--         smb.efxbma_3m_util_1pc_past_due_count,
--         smb.efxbma_3m_util_2c_past_due_count,
--         smb.efxbma_3m_util_2pc_past_due_count,
--         smb.efxbma_3m_util_3c_past_due_count,
--         smb.efxbma_3m_util_3pc_past_due_count,
--         smb.efxbma_3m_util_4pc_past_due_count,
--         smb.efxbma_3m_util_tr_count,
--         smb.efxbma_3m_util_tr_high_bal,
--         smb.efxbma_3m_util_tr_wb_count,
--         smb.efxbma_3m_util_worst_payment_status,
--         smb.efxbma_12m_ind_1c_past_due_count,
--         smb.efxbma_12m_ind_1pc_past_due_count,
--         smb.efxbma_12m_ind_2c_past_due_count,
--         smb.efxbma_12m_ind_2pc_past_due_count,
--         smb.efxbma_12m_ind_3c_past_due_count,
--         smb.efxbma_12m_ind_3pc_past_due_count,
--         smb.efxbma_12m_ind_4pc_past_due_count,
--         smb.efxbma_12m_ind_tr_count,
--         smb.efxbma_12m_ind_tr_high_bal,
--         smb.efxbma_12m_ind_worst_payment_status,
--         smb.efxbma_12m_nfin_1c_past_due_amount,
--         smb.efxbma_12m_nfin_1c_past_due_count,
--         smb.efxbma_12m_nfin_1pc_past_due_count,
--         smb.efxbma_12m_nfin_2c_past_due_amount,
--         smb.efxbma_12m_nfin_2c_past_due_count,
--         smb.efxbma_12m_nfin_2pc_past_due_count,
--         smb.efxbma_12m_nfin_3c_past_due_amount,
--         smb.efxbma_12m_nfin_3c_past_due_count,
--         smb.efxbma_12m_nfin_3pc_past_due_count,
--         smb.efxbma_12m_nfin_4pc_past_due_amount,
--         smb.efxbma_12m_nfin_4pc_past_due_count,
--         smb.efxbma_12m_nfin_chargeoff_tr_count,
--         smb.efxbma_12m_nfin_high_credit_lim,
--         smb.efxbma_12m_nfin_orig_credit_lim,
--         smb.efxbma_12m_nfin_past_due_amount,
--         smb.efxbma_12m_nfin_per_4pc_pd_to_totbal,
--         smb.efxbma_12m_nfin_per_coff_to_tot_acc,
--         smb.efxbma_12m_nfin_per_pd_to_totbal,
--         smb.efxbma_12m_nfin_per_satisfactory_acc,
--         smb.efxbma_12m_nfin_satisfactory_tr_count,
--         smb.efxbma_12m_nfin_total_chargeoff_amt,
--         smb.efxbma_12m_nfin_total_util,
--         smb.efxbma_12m_nfin_tr_count,
--         smb.efxbma_12m_nfin_tr_high_bal,
--         smb.efxbma_12m_nfin_worst_payment_status,
--         smb.efxbma_12m_serv_tr_count,
--         smb.efxbma_12m_serv_tr_high_bal,
--         smb.efxbma_12m_tel_1c_past_due_count,
--         smb.efxbma_12m_tel_1pc_past_due_count,
--         smb.efxbma_12m_tel_2c_past_due_count,
--         smb.efxbma_12m_tel_2pc_past_due_count,
--         smb.efxbma_12m_tel_3c_past_due_count,
--         smb.efxbma_12m_tel_3pc_past_due_count,
--         smb.efxbma_12m_tel_4pc_past_due_count,
--         smb.efxbma_12m_tel_tr_count,
--         smb.efxbma_12m_tel_tr_high_bal,
--         smb.efxbma_12m_tel_worst_payment_status,
--         smb.efxbma_12m_util_1c_past_due_count,
--         smb.efxbma_12m_util_1pc_past_due_count,
--         smb.efxbma_12m_util_2c_past_due_count,
--         smb.efxbma_12m_util_2pc_past_due_count,
--         smb.efxbma_12m_util_3c_past_due_count,
--         smb.efxbma_12m_util_3pc_past_due_count,
--         smb.efxbma_12m_util_4pc_past_due_count,
--         smb.efxbma_12m_util_tr_count,
--         smb.efxbma_12m_util_tr_high_bal,
--         smb.efxbma_12m_util_worst_payment_status,
--         smb.efxbma_24m_ind_1c_past_due_count,
--         smb.efxbma_24m_ind_1pc_past_due_count,
--         smb.efxbma_24m_ind_2c_past_due_count,
--         smb.efxbma_24m_ind_2pc_past_due_count,
--         smb.efxbma_24m_ind_3c_past_due_count,
--         smb.efxbma_24m_ind_3pc_past_due_count,
--         smb.efxbma_24m_ind_4pc_past_due_count,
--         smb.efxbma_24m_ind_tr_count,
--         smb.efxbma_24m_ind_tr_high_bal,
--         smb.efxbma_24m_ind_worst_payment_status,
--         smb.efxbma_24m_nfin_1c_past_due_amount,
--         smb.efxbma_24m_nfin_1c_past_due_count,
--         smb.efxbma_24m_nfin_1pc_past_due_count,
--         smb.efxbma_24m_nfin_2c_past_due_amount,
--         smb.efxbma_24m_nfin_2c_past_due_count,
--         smb.efxbma_24m_nfin_2pc_past_due_count,
--         smb.efxbma_24m_nfin_3c_past_due_amount,
--         smb.efxbma_24m_nfin_3c_past_due_count,
--         smb.efxbma_24m_nfin_3pc_past_due_count,
--         smb.efxbma_24m_nfin_4pc_past_due_amount,
--         smb.efxbma_24m_nfin_4pc_past_due_count,
--         smb.efxbma_24m_nfin_chargeoff_tr_count,
--         smb.efxbma_24m_nfin_high_credit_lim,
--         smb.efxbma_24m_nfin_orig_credit_lim,
--         smb.efxbma_24m_nfin_past_due_amount,
--         smb.efxbma_24m_nfin_per_4pc_pd_to_totbal,
--         smb.efxbma_24m_nfin_per_coff_to_tot_acc,
--         smb.efxbma_24m_nfin_per_pd_to_totbal,
--         smb.efxbma_24m_nfin_per_satisfactory_acc,
--         smb.efxbma_24m_nfin_satisfactory_tr_count,
--         smb.efxbma_24m_nfin_total_chargeoff_amt,
--         smb.efxbma_24m_nfin_total_util,
--         smb.efxbma_24m_nfin_tr_count,
--         smb.efxbma_24m_nfin_tr_high_bal,
--         smb.efxbma_24m_nfin_worst_payment_status,
--         smb.efxbma_24m_serv_tr_count,
--         smb.efxbma_24m_serv_tr_high_bal,
--         smb.efxbma_24m_tel_1c_past_due_count,
--         smb.efxbma_24m_tel_1pc_past_due_count,
--         smb.efxbma_24m_tel_2c_past_due_count,
--         smb.efxbma_24m_tel_2pc_past_due_count,
--         smb.efxbma_24m_tel_3c_past_due_count,
--         smb.efxbma_24m_tel_3pc_past_due_count,
--         smb.efxbma_24m_tel_4pc_past_due_count,
--         smb.efxbma_24m_tel_tr_count,
--         smb.efxbma_24m_tel_tr_high_bal,
--         smb.efxbma_24m_tel_worst_payment_status,
--         smb.efxbma_24m_util_1c_past_due_count,
--         smb.efxbma_24m_util_1pc_past_due_count,
--         smb.efxbma_24m_util_2c_past_due_count,
--         smb.efxbma_24m_util_2pc_past_due_count,
--         smb.efxbma_24m_util_3c_past_due_count,
--         smb.efxbma_24m_util_3pc_past_due_count,
--         smb.efxbma_24m_util_4pc_past_due_count,
--         smb.efxbma_24m_util_tr_count,
--         smb.efxbma_24m_util_tr_high_bal,
--         smb.efxbma_24m_util_worst_payment_status,
--         smb.efxbma_pubrec_age_bkp,
--         smb.efxbma_pubrec_age_judg,
--         smb.efxbma_pubrec_age_lien,
--         smb.efxbma_pubrec_age_pr,
--         smb.efxbma_pubrec_bkp_ind,
--         smb.efxbma_pubrec_judg_ind,
--         smb.efxbma_pubrec_lien_ind,
--         smb.efxbma_pubrec_lien_judg_ind,
--         smb.efxbma_pubrec_max_liab_rep_judg,
--         smb.efxbma_pubrec_max_liab_rep_lien,
--         smb.efxbma_pubrec_status_fi,
--         smb.efxbma_pubrec_status_fi_ju,
--         smb.efxbma_pubrec_status_ju,
--         smb.efxbma_pubrec_sum_lien_all_judg,
--         smb.efxbma_pubrec_total_cur_liab_judg,
--         smb.efxbma_pubrec_total_cur_liab_judg_all,
--         smb.efxbma_pubrec_total_cur_liab_lien,
--         smb.efxbma_pubrec_total_cur_liab_lien_all,
--         smb.efxbma_pubrec_total_cur_liab_lien_judg,
--         smb.efxbma_pubrec_total_judg,
--         smb.efxbma_pubrec_total_lien,
--         smb.efxbma_pubrec_total_lien_judg,
--         smb.efxbma_1m_ind_1c_past_due_count,
--         smb.efxbma_1m_ind_1pc_past_due_count,
--         smb.efxbma_extract_date,
        smb.mid,
        smb.vid,
        smb.zi_c_location_id,
        smb.zi_c_company_id,
        smb.zi_c_is_hq,
        smb.zi_es_ecid,
        smb.zi_es_location_id,
        smb.zi_c_tier_grade,
        smb.zi_c_name,
        smb.zi_c_name_display,
        smb.zi_c_legal_entity_type,
        smb.zi_c_url,
        smb.zi_c_street,
        smb.zi_c_street_2,
        smb.zi_c_city,
        smb.zi_c_state,
        smb.zi_c_zip,
        smb.zi_c_country,
        smb.zi_c_cbsa_name,
        smb.zi_c_county,
        smb.zi_c_latitude,
        smb.zi_c_longitude,
        smb.zi_c_verified_address,
        smb.zi_c_employee_range,
        smb.zi_c_employees,
        smb.zi_c_revenue_range,
        smb.zi_c_revenue,
        smb.zi_c_phone,
        smb.zi_c_fax,
        smb.zi_c_industry_primary,
        smb.zi_c_sub_industry_primary,
        smb.zi_c_industries,
        smb.zi_c_sub_industries,
        smb.zi_es_industry,
        smb.zi_es_industries_top3,
        smb.zi_c_naics2,
        smb.zi_c_naics4,
        smb.zi_c_naics6,
        smb.zi_c_naics_top3,
        smb.zi_c_sic2,
        smb.zi_c_sic3,
        smb.zi_c_sic4,
        smb.zi_c_sic_top3,
        smb.zi_c_estimated_age,
        smb.zi_c_year_founded,
        smb.zi_c_is_b2b,
        smb.zi_c_is_b2c,
        smb.zi_es_hq_ecid,
        smb.zi_es_hq_location_id,
        smb.zi_c_company_name,
        smb.zi_c_company_url,
        smb.zi_c_company_street,
        smb.zi_c_company_street_2,
        smb.zi_c_company_city,
        smb.zi_c_company_state,
        smb.zi_c_company_zip,
        smb.zi_c_company_country,
        smb.zi_c_company_cbsa_name,
        smb.zi_c_company_county,
        smb.zi_c_company_latitude,
        smb.zi_c_company_longitude,
        smb.zi_c_company_verified_address,
        smb.zi_c_company_employee_range,
        smb.zi_c_company_employees,
        smb.zi_c_company_revenue_range,
        smb.zi_c_company_revenue,
        smb.zi_c_company_phone,
        smb.zi_c_company_fax,
        smb.zi_c_linkedin_url,
        smb.zi_c_facebook_url,
        smb.zi_c_twitter_url,
        smb.zi_c_yelp_url,
        smb.zi_c_domain_rank,
        smb.zi_c_keywords,
        smb.zi_c_top_keywords,
        smb.zi_c_num_keywords,
        smb.zi_c_employee_growth_1yr,
        smb.zi_c_employee_growth_2yr,
        smb.zi_es_growth,
        smb.zi_es_employee_growth,
        smb.zi_es_revenue_growth,
        smb.zi_es_percent_employee_growth,
        smb.zi_es_percent_revenue_growth,
        smb.zi_c_name_confidence_score,
        smb.zi_c_url_confidence_score,
        smb.zi_c_address_confidence_score,
        smb.zi_c_phone_confidence_score,
        smb.zi_c_employees_confidence_score,
        smb.zi_c_revenue_confidence_score,
        smb.zi_es_industry_confidence_score,
        smb.zi_c_naics_confidence_score,
        smb.zi_c_sic_confidence_score,
        smb.zi_es_industries_top3_confidence_scores,
        smb.zi_c_naics_top3_confidence_scores,
        smb.zi_c_sic_top3_confidence_scores,
        smb.zi_c_ids_merged,
        smb.zi_c_names_other,
        smb.zi_c_url_status,
        smb.zi_c_urls_alt,
        smb.zi_c_url_last_updated,
        smb.zi_c_inactive_flag,
        smb.zi_c_ein,
        smb.zi_c_is_small_business,
        smb.zi_c_is_public,
        smb.zi_c_ticker,
        smb.zi_c_tickers_alt,
        smb.zi_c_has_mobile_app,
        smb.zi_c_currency_code,
        smb.zi_c_num_locations,
        smb.zi_c_hr_contacts,
        smb.zi_c_sales_contacts,
        smb.zi_c_marketing_contacts,
        smb.zi_c_finance_contacts,
        smb.zi_c_c_suite_contacts,
        smb.zi_c_engineering_contacts,
        smb.zi_c_it_contacts,
        smb.zi_c_operations_contacts,
        smb.zi_c_legal_contacts,
        smb.zi_c_medical_contacts,
        smb.zi_c_tech_ids,
        smb.zi_c_latest_funding_age,
        smb.zi_c_num_of_investors,
        smb.zi_c_investor_names,
        smb.zi_c_funding_strength,
        smb.zi_c_funding_type,
        smb.zi_c_total_funding_amount,
        smb.zi_c_latest_funding_amount,
        smb.zi_c_latest_funding_date,
        smb.zi_c_num_funding_rounds,
        smb.zi_c_is_fortune_100,
        smb.zi_c_is_fortune_500,
        smb.zi_c_is_s_and_p_500,
        smb.zi_c_last_updated_date,
        smb.zi_c_release_date,
        smb.oc_match_confidence,
        smb.company_number,
        smb.jurisdiction_code,
        smb.name,
        smb.normalised_name,
        smb.company_type,
        smb.nonprofit,
        smb.current_status,
        smb.incorporation_date,
        smb.dissolution_date,
        smb.branch,
        smb.business_number,
        smb.current_alternative_legal_name,
        smb.current_alternative_legal_name_language,
        smb.home_jurisdiction_text,
        smb.native_company_number,
        smb.previous_names,
        smb.retrieved_at,
        smb.registry_url,
        smb.restricted_for_marketing,
        smb.inactive,
        smb.accounts_next_due,
        smb.accounts_reference_date,
        smb.accounts_last_made_up_date,
        smb.annual_return_next_due,
        smb.annual_return_last_made_up_date,
        smb.has_been_liquidated,
        smb.has_insolvency_history,
        smb.has_charges,
        smb.number_of_employees,
        smb."registered_address.street_address",
        smb."registered_address.locality",
        smb."registered_address.region",
        smb."registered_address.postal_code",
        smb."registered_address.country",
        smb."registered_address.in_full",
        smb.home_jurisdiction_code,
        smb.home_jurisdiction_company_number,
        smb.industry_code_uids,
        smb.latest_accounts_date,
        smb.latest_accounts_cash,
        smb.latest_accounts_assets,
        smb.latest_accounts_liabilities,
        smb.officer_1_name,
        smb.officer_1_title,
        smb.officer_2_name,
        smb.officer_2_title,
        smb.max_rating_past_6_months,
        smb.min_rating_all_time,
        smb.count_of_merchant_pending_partnership_tradelines_past_6_mo,
        smb.count_of_complaints_containing_alert_words_past_3_months,
        smb.count_of_delinquent_closed_merchant_partnerships_past_12_m,
        smb.count_of_address_line_1_past_24_months,
        smb.days_since_earliest_complaint_past_12_months,
        smb.count_non_delinquent_closures_past_12_months,
        smb.percent_of_other_resolved_status_all_time,
        smb.count_of_suspended_partner_merchant_partnerships_past_6_mo,
        smb.corporate_filing_filing_date_all_time,
        smb.percent_of_complaints_containing_alert_words_past_3_months,
        smb.count_of_reviews_source_a_past_1_months,
        smb.percent_of_reviews_source_a_past_3_months,
        smb.days_between_earliest_and_latest_complaint_past_6_months,
        smb.total_amount_of_liens_10_most_recent_all_time,
        smb.number_of_personal_chapter_7_bankruptcies_all_time,
        smb.state_of_the_professional_license_all_time,
        smb.count_of_zip5_past_24_months,
        smb.percent_of_reviews_source_b_past_3_months,
        smb.count_of_all_reviews_past_6_months,
        smb.count_of_merchant_open_partnership_tradelines_past_12_mont,
        smb.count_of_answered_resolved_status_past_6_months,
        smb.closed_merchant_partnership_tradeline_hit_flag_past_1_mont,
        smb.count_non_delinquent_closures_all_time,
        smb.count_of_reviews_source_j_past_3_months,
        smb.count_of_unique_reviewers_past_6_months,
        smb.merchant_partnership_tradelines_with_at_least_a_2__all_tim,
        smb.count_of_unanswered_resolved_status_past_12_months,
        smb.count_of_reviews_source_b_past_3_months,
        smb.count_of_closed_partner_merchant_partnerships_past_12_mont,
        smb.most_recent_judgement_amount_all_time,
        smb.days_since_last_seen_past_24_months,
        smb.count_of_merchant_inactive_partnership_tradelines_all_time,
        smb.year_principal_died_all_time,
        smb.percent_of_reviews_source_j_past_3_months,
        smb.count_of_complaint_containing_alert_words_all_time,
        smb.count_of_merchant_partnership_tradelines_in_good_s_past_3,
        smb.count_of_complaints_past_1_months,
        smb.percent_of_answered_resolved_status_past_12_months,
        smb.count_of_duplicate_reviewers_all_time,
        smb.percent_of_answered_resolved_status_all_time,
        smb.kyb_address_hit_flag_past_6_months,
        smb.percent_60_quintile_of_rating_all_time,
        smb.count_of_source_a_unable_to_locate_business_resolv_past_6,
        smb.kyb_address_hit_flag_all_time,
        smb.count_of_reviews_source_e_past_6_months,
        smb.count_of_total_reviewers_all_time,
        smb.percent_of_other_resolved_status_past_12_months,
        smb.employers_last_seen_date_all_time,
        smb.percent_of_0_or_1_star_ratings_all_time,
        smb.days_between_earliest_and_latest_close_date_for_me_past_6,
        smb.percent_of_reviews_source_g_past_1_months,
        smb.days_since_latest_complaint_past_6_months,
        smb.count_of_duplicate_reviewers_past_3_months,
        smb.median_rating_past_1_months,
        smb.count_of_merchant_closures_in_first_2_months_all_time,
        smb.number_of_relatives_on_watch_list_all_time,
        smb.number_of_known_relatives_all_time,
        smb.count_of_complaints_containing_alert_words_past_12_months,
        smb.most_recent_bankruptcy_filing_date_all_time,
        smb.days_between_first_seen_and_last_seen_past_24_months,
        smb.count_of_merchant_inactive_partnership_tradelines_past_1_m,
        smb.days_since_latest_complaint_past_1_months,
        smb.count_of_merchant_closures_in_first_3_months_all_time,
        smb.count_of_all_reviews_past_3_months,
        smb.number_of_watch_lists_principal_appears_on_all_time,
        smb.count_of_reviews_source_g_past_1_months,
        smb.count_of_closed_out_of_business_partner_merchant_p_past_1,
        smb.days_between_earliest_and_latest_update_past_24_months,
        smb.count_of_0_or_1_star_ratings_past_6_months,
        smb.count_of_unique_zip5_past_24_months,
        smb.count_of_states_past_6_months,
        smb.percent_60_quintile_of_rating_past_6_months,
        smb.merchant_partnership_tradeline_hit_flag_past_3_months,
        smb.count_of_source_a_unable_to_locate_business_resolv_all_tim,
        smb.count_of_merchant_closures_in_first_12_months_all_time,
        smb.days_since_latest_merchant_partnership_tradeline_o_past_12,
        smb.most_recent_judgement_filing_date_all_time,
        smb.days_between_earliest_and_latest_update_all_time,
        smb.days_between_earliest_and_latest_merchant_partners_past_6,
        smb.percent_of_2_star_ratings_all_time,
        smb.public_data_hit_flag_past_6_months,
        smb.days_since_latest_close_date_for_merchant_partners_past_12,
        smb.count_of_reviews_source_e_past_1_months,
        smb.count_of_declined_partner_merchant_partnerships_all_time,
        smb.corporate_filing_registration_type_all_time,
        smb.days_since_latest_update_past_24_months,
        smb.days_since_first_seen_past_12_months,
        smb.percent_of_3_star_ratings_past_6_months,
        smb.closed_merchant_partnership_tradeline_hit_flag_all_time,
        smb.count_of_closed_performance_partner_merchant_partn_past_6,
        smb.count_of_merchant_partnerships_in_bad_standing_past_6_mont,
        smb.count_of_complaint_containing_alert_words_past_1_months,
        smb.days_since_last_seen_past_6_months,
        smb.count_of_cities_past_6_months,
        smb.count_of_zip5_all_time,
        smb.count_non_delinquent_closures_past_3_months,
        smb.percent_of_other_resolved_status_past_1_months,
        smb.count_of_source_a_unable_to_locate_business_resolv_past_1,
        smb.is_business_on_a_watch_list_all_time,
        smb.is_deceased_all_time,
        smb.count_of_merchant_open_partnership_tradelines_past_1_month,
        smb.percent_of_2_star_ratings_past_1_months,
        smb.days_between_earliest_and_latest_complaint_past_3_months,
        smb.percent_of_answered_resolved_status_past_3_months,
        smb.number_of_judgement_filings_all_time,
        smb.days_since_latest_update_all_time,
        smb.most_recent_ucc_filing_expiration_date_all_time,
        smb.percent_of_reviews_source_j_past_1_months,
        smb.bankruptcy_status_date_all_time,
        smb.percent_of_reviews_source_e_past_1_months,
        smb.count_of_merchant_closures_in_first_1_month_all_time,
        smb.days_between_earliest_and_latest_complaint_past_1_months,
        smb.count_of_2_star_ratings_past_1_months,
        smb.days_since_earliest_update_past_12_months,
        smb.count_of_decline_status_merchant_partnerships_past_3_month,
        smb.percent_of_resolved_resolved_status_past_1_months,
        smb.days_since_earliest_merchant_partnership_tradeline_all_tim,
        smb.count_of_probation_partner_merchant_partnerships_past_3_mo,
        smb.percent_of_reviews_source_i_past_6_months,
        smb.count_of_reviews_source_a_past_3_months,
        smb.most_recent_business_lien_filing_date_all_time,
        smb.max_rating_past_1_months,
        smb.count_of_unique_reviewers_all_time,
        smb.days_since_earliest_review_all_time,
        smb.count_of_other_resolved_status_past_3_months,
        smb.count_of_unique_cities_past_24_months,
        smb.percent_80_quintile_of_rating_past_6_months,
        smb.closed_merchant_partnership_tradeline_hit_flag_past_12_mon,
        smb.count_of_unique_lenders_for_merchant_level_partner_past_6,
        smb.percent_of_reviews_containing_alert_words_all_time,
        smb.count_of_total_reviewers_past_3_months,
        smb.percent_of_resolved_resolved_status_all_time,
        smb.count_of_addresses_all_time,
        smb.days_since_earliest_update_all_time,
        smb.percent_of_reviews_containing_alert_words_past_6_months,
        smb.percent_of_reviews_source_h_past_6_months,
        smb.count_of_reviews_source_h_past_6_months,
        smb.count_of_unique_cities_past_6_months,
        smb.count_of_closed_fraud_partner_merchant_partnership_past_3,
        smb.days_since_latest_update_past_12_months,
        smb.days_between_earliest_and_latest_close_date_for_me_past_12,
        smb.count_of_closed_other_partner_merchant_partnership_past_6,
        smb.most_recent_report_date_of_judgement_filing_all_time,
        smb.percent_of_reviews_source_e_past_6_months,
        smb.count_of_other_resolved_status_all_time,
        smb.count_of_unique_cities_all_time,
        smb.percent_of_unresolved_resolved_status_all_time,
        smb.count_of_complaints_containing_alert_words_all_time,
        smb.count_of_unique_address_line_1_past_12_months,
        smb.count_of_closed_fraud_partner_merchant_partnership_past_6,
        smb.days_since_latest_merchant_partnership_tradeline_o_past_1,
        smb.count_of_unresolved_resolved_status_past_1_months,
        smb.count_of_probation_partner_merchant_partnerships_past_6_mo,
        smb.count_of_0_or_1_star_ratings_all_time,
        smb.percent_of_5_star_ratings_past_3_months,
        smb.employers_business_name_all_time,
        smb.median_rating_past_6_months,
        smb.percent_of_resolved_resolved_status_past_6_months,
        smb.days_since_latest_merchant_partnership_tradeline_o_past_6,
        smb.count_of_reviews_containing_alert_words_past_3_months,
        smb.count_of_address_line_1_past_6_months,
        smb.count_of_reviews_source_i_past_1_months,
        smb.most_recent_judgement_status_all_time,
        smb.percent_of_0_or_1_star_ratings_past_3_months,
        smb.count_of_zip5_past_12_months,
        smb.count_of_merchant_pending_partnership_tradelines_past_12_m,
        smb.count_of_reviews_containing_alert_words_past_6_months,
        smb.kyb_address_hit_flag_past_24_months,
        smb.number_of_known_associates_all_time,
        smb.count_of_0_or_1_star_ratings_past_3_months,
        smb.days_since_latest_review_past_3_months,
        smb.days_since_last_seen_past_12_months,
        smb.count_of_3_star_ratings_past_1_months,
        smb.days_since_earliest_update_past_24_months,
        smb.percent_of_reviews_source_a_past_1_months,
        smb.count_of_2_star_ratings_past_6_months,
        smb.percent_of_answered_resolved_status_past_6_months,
        smb.percent_of_reviews_containing_alert_words_past_1_months,
        smb.percent_of_reviews_source_i_all_time,
        smb.percent_of_unanswered_resolved_status_past_6_months,
        smb.standard_deviation_of_rating_past_6_months,
        smb.percent_of_5_star_ratings_past_6_months,
        smb.count_of_total_reviewers_past_6_months,
        smb.percent_of_reviews_source_i_past_3_months,
        smb.days_since_latest_close_date_for_merchant_partners_past_1,
        smb.percent_of_resolved_resolved_status_past_12_months,
        smb.variance_of_rating_past_3_months,
        smb.count_of_answered_resolved_status_all_time,
        smb.count_of_4_star_ratings_past_1_months,
        smb.days_since_latest_merchant_partnership_tradeline_o_past_3,
        smb.percent_of_reviews_source_h_all_time,
        smb.count_of_cities_past_24_months,
        smb.count_of_complaints_past_12_months,
        smb.percent_of_unanswered_resolved_status_past_3_months,
        smb.days_since_latest_update_past_6_months,
        smb.count_of_merchant_partnerships_in_bad_standing_past_3_mont,
        smb.median_rating_past_3_months,
        smb.days_since_earliest_close_date_for_merchant_partne_past_6,
        smb.count_of_resolved_resolved_status_past_12_months,
        smb.percent_of_complaints_containing_alert_words_past_6_months,
        smb.variance_of_rating_past_1_months,
        smb.days_since_latest_merchant_partnership_tradeline_o_all_tim,
        smb.days_between_earliest_and_latest_complaint_all_time,
        smb.count_of_source_a_unable_to_locate_business_resolv_past_3,
        smb.count_of_3_star_ratings_past_3_months,
        smb.corporate_filing_incorporation_state_all_time,
        smb.percent_of_reviews_source_a_past_6_months,
        smb.count_of_merchant_partnership_tradelines_in_good_s_past_12,
        smb.count_of_reviews_source_g_all_time,
        smb.percent_of_4_star_ratings_all_time,
        smb.percent_of_3_star_ratings_past_1_months,
        smb.days_since_earliest_complaint_past_1_months,
        smb.count_of_delinquent_closed_merchant_partnerships_all_time,
        smb.kyb_address_hit_flag_past_12_months,
        smb.percent_of_0_or_1_star_ratings_past_1_months,
        smb.count_of_total_reviewers_past_1_months,
        smb.percent_of_source_a_unable_to_locate_business_resolved_s_past_1,
        smb.percent_of_reviews_source_g_all_time,
        smb.count_of_2_star_ratings_all_time,
        smb.count_of_reviews_source_h_all_time,
        smb.count_of_closed_out_of_business_partner_merchant_p_past_6,
        smb.count_of_merchant_pending_partnership_tradelines_all_time,
        smb.count_of_unique_lenders_for_merchant_level_partner_past_12,
        smb.percent_of_reviews_source_i_past_1_months,
        smb.count_of_complaints_containing_alert_words_past_6_months,
        smb.corporate_filing_business_name_all_time,
        smb.days_between_earliest_and_latest_review_past_3_months,
        smb.count_of_closed_performance_partner_merchant_partn_past_3,
        smb.count_of_merchant_partnership_tradelines_in_good_s_all_tim,
        smb.most_recent_business_lien_status_date_all_time,
        smb.days_since_earliest_close_date_for_merchant_partne_past_12,
        smb.percent_40_quintile_of_rating_past_1_months,
        smb.public_data_hit_flag_all_time,
        smb.count_of_decline_status_merchant_partnerships_past_6_month,
        smb.number_of_personal_chapter_13_bankruptcies_all_time,
        smb.percent_of_3_star_ratings_all_time,
        smb.count_of_reviews_source_e_all_time,
        smb.days_since_earliest_merchant_partnership_tradeline_past_3,
        smb.count_of_unique_lenders_for_merchant_level_partner_all_tim,
        smb.percent_40_quintile_of_rating_past_6_months,
        smb.count_of_closed_compliance_partner_merchant_partne_all_tim,
        smb.complaint_data_source_a_hit_flag_all_time,
        smb.percent_of_reviews_source_h_past_1_months,
        smb.count_of_merchant_unknown_partnership_tradelines_past_6_mo,
        smb.count_of_unresolved_resolved_status_past_12_months,
        smb.count_of_unique_reviewers_past_1_months,
        smb.count_of_closed_partner_merchant_partnerships_all_time,
        smb.number_of_bankruptices_all_time,
        smb.percent_of_other_resolved_status_past_3_months,
        smb.count_of_complaints_past_3_months,
        smb.count_of_unanswered_resolved_status_past_3_months,
        smb.count_of_merchant_unknown_partnership_tradelines_all_time,
        smb.count_of_unique_reviewers_past_3_months,
        smb.most_recent_ucc_filing_date_all_time,
        smb.count_of_merchant_open_partnership_tradelines_past_3_month,
        smb.days_since_earliest_close_date_for_merchant_partne_all_tim,
        smb.complaint_data_source_a_hit_flag_past_6_months,
        smb.min_rating_past_6_months,
        smb.percent_20_quintile_of_rating_past_3_months,
        smb.percent_of_unresolved_resolved_status_past_1_months,
        smb.days_between_first_seen_and_last_seen_past_6_months,
        smb.count_of_closed_underwriting_partner_merchant_part_past_6,
        smb.count_of_closed_out_of_business_partner_merchant_p_past_3,
        smb.count_of_answered_resolved_status_past_3_months,
        smb.count_of_merchant_partnership_tradelines_in_good_s_past_1,
        smb.percent_80_quintile_of_rating_past_1_months,
        smb.count_of_reviews_source_i_all_time,
        smb.count_of_states_all_time,
        smb.license_type_on_the_professional_license_all_time,
        smb.count_of_closed_performance_partner_merchant_partn_past_1,
        smb.count_of_unique_lenders_for_merchant_level_partner_past_1,
        smb.percent_of_reviews_source_e_all_time,
        smb.count_of_suspended_partner_merchant_partnerships_past_1_mo,
        smb.count_of_reviews_source_j_past_1_months,
        smb.number_of_watch_lists_business_appears_on_all_time,
        smb.days_between_first_seen_and_last_seen_past_12_months,
        smb.average_rating_past_3_months,
        smb.count_of_closed_performance_partner_merchant_partn_all_tim,
        smb.count_of_closed_compliance_partner_merchant_partne_past_6,
        smb.count_of_reviews_source_h_past_1_months,
        smb.count_of_closed_underwriting_partner_merchant_part_past_1,
        smb.days_between_earliest_and_latest_merchant_partners_past_12,
        smb.count_of_resolved_resolved_status_all_time,
        smb.count_of_decline_status_merchant_partnerships_past_12_mont,
        smb.count_of_addresses_past_24_months,
        smb.standard_deviation_of_rating_past_3_months,
        smb.count_of_merchant_closures_in_first_6_months_all_time,
        smb.count_of_merchant_partnership_tradelines_in_good_s_past_6,
        smb.max_rating_all_time,
        smb.percent_of_reviews_source_g_past_6_months,
        smb.most_recent_bankruptcy_discharge_closure_date_all_time,
        smb.percent_of_reviews_containing_alert_words_past_3_months,
        smb.percent_of_4_star_ratings_past_3_months,
        smb.days_since_latest_close_date_for_merchant_partners_past_6,
        smb.count_of_answered_resolved_status_past_1_months,
        smb.count_of_closed_performance_partner_merchant_partn_past_12,
        smb.merchant_partnership_tradeline_hit_flag_past_6_months,
        smb.count_of_merchant_partnerships_in_bad_standing_past_12_mon,
        smb.public_data_hit_flag_past_3_months,
        smb.most_recent_bankruptcy_status_all_time,
        smb.standard_deviation_of_rating_past_1_months,
        smb.perc_of_source_a_unable_to_locate_business_resolved_past_12,
        smb.count_non_delinquent_closures_past_1_months,
        smb.count_of_unresolved_resolved_status_all_time,
        smb.percent_of_reviews_source_a_all_time,
        smb.days_between_earliest_and_latest_review_past_6_months,
        smb.days_since_earliest_merchant_partnership_tradeline_past_12,
        smb.count_of_reviews_source_b_past_1_months,
        smb.count_of_unique_states_past_24_months,
        smb.days_between_earliest_and_latest_update_past_6_months,
        smb.count_of_merchant_pending_partnership_tradelines_past_1_mo,
        smb.count_of_complaints_containing_alert_words_past_1_months,
        smb.corporate_filing_corporation_type_all_time,
        smb.min_rating_past_3_months,
        smb.count_of_other_resolved_status_past_1_months,
        smb.count_of_merchant_inactive_partnership_tradelines_past_12,
        smb.is_principal_on_a_watch_list_all_time,
        smb.days_between_earliest_and_latest_close_date_for_me_past_1,
        smb.days_since_earliest_complaint_all_time,
        smb.count_of_suspended_partner_merchant_partnerships_past_12_m,
        smb.count_of_unique_states_past_12_months,
        smb.percent_of_5_star_ratings_all_time,
        smb.days_between_earliest_and_latest_close_date_for_me_past_3,
        smb.count_of_merchant_unknown_partnership_tradelines_past_12_m,
        smb.count_of_answered_resolved_status_past_12_months,
        smb.percent_of_reviews_source_b_past_6_months,
        smb.days_since_first_seen_past_6_months,
        smb.count_of_5_star_ratings_past_3_months,
        smb.count_of_complaint_containing_alert_words_past_3_months,
        smb.count_of_unique_states_all_time,
        smb.count_of_cities_past_12_months,
        smb.count_of_merchant_pending_partnership_tradelines_past_3_mo,
        smb.percent_of_reviews_source_b_all_time,
        smb.count_of_unique_address_line_1_past_6_months,
        smb.merchant_partnership_tradeline_hit_flag_all_time,
        smb.percent_40_quintile_of_rating_past_3_months,
        smb.count_of_resolved_resolved_status_past_1_months,
        smb.max_rating_past_3_months,
        smb.count_of_unique_states_past_6_months,
        smb.percent_of_2_star_ratings_past_3_months,
        smb.percent_of_unresolved_resolved_status_past_6_months,
        smb.was_most_recent_bankruptcy_voluntary_all_time,
        smb.days_since_last_seen_all_time,
        smb.count_of_probation_partner_merchant_partnerships_past_12_m,
        smb.days_between_earliest_and_latest_update_past_12_months,
        smb.days_since_latest_close_date_for_merchant_partners_all_tim,
        smb.count_of_unanswered_resolved_status_past_6_months,
        smb.percent_of_unanswered_resolved_status_past_12_months,
        smb.most_recent_business_lien_status_all_time,
        smb.count_of_duplicate_reviewers_past_1_months,
        smb.count_of_zip5_past_6_months,
        smb.percent_of_unresolved_resolved_status_past_12_months,
        smb.days_since_latest_review_past_1_months,
        smb.most_recent_ucc_filing_type_all_time,
        smb.count_of_unresolved_resolved_status_past_3_months,
        smb.count_of_closed_partner_merchant_partnerships_past_3_month,
        smb.count_of_complaint_containing_alert_words_past_12_months,
        smb.days_since_earliest_close_date_for_merchant_partne_past_3,
        smb.days_since_earliest_complaint_past_3_months,
        smb.count_of_closed_compliance_partner_merchant_partne_past_12,
        smb.percent_of_answered_resolved_status_past_1_months,
        smb.average_rating_all_time,
        smb.count_of_states_past_12_months,
        smb.count_of_unique_address_line_1_past_24_months,
        smb.count_of_4_star_ratings_past_6_months,
        smb.complaint_data_source_a_hit_flag_past_3_months,
        smb.min_rating_past_1_months,
        smb.count_of_closed_other_partner_merchant_partnership_past_3,
        smb.count_of_closed_underwriting_partner_merchant_part_past_3,
        smb.count_of_declined_partner_merchant_partnerships_past_12_mo,
        smb.count_of_declined_partner_merchant_partnerships_past_1_mon,
        smb.percent_of_complaints_containing_alert_words_past_1_months,
        smb.count_of_decline_status_merchant_partnerships_past_1_month,
        smb.days_since_earliest_close_date_for_merchant_partne_past_1,
        smb.count_of_closed_fraud_partner_merchant_partnership_all_tim,
        smb.count_non_delinquent_closures_past_6_months,
        smb.date_deceased_information_reported_to_verdata_all_time,
        smb.complaint_data_source_a_hit_flag_past_1_months,
        smb.days_since_earliest_review_past_3_months,
        smb.count_of_resolved_resolved_status_past_6_months,
        smb.count_of_closed_fraud_partner_merchant_partnership_past_1,
        smb.count_of_declined_partner_merchant_partnerships_past_6_mon,
        smb.percent_of_2_star_ratings_past_6_months,
        smb.count_of_4_star_ratings_all_time,
        smb.count_of_2_star_ratings_past_3_months,
        smb.merchant_partnership_tradelines_with_at_least_a_1__all_tim,
        smb.percent_of_reviews_source_j_all_time,
        smb.count_of_merchant_open_partnership_tradelines_all_time,
        smb.merchant_partnership_tradeline_hit_flag_past_1_months,
        smb.count_of_cities_all_time,
        smb.count_of_reviews_source_a_past_6_months,
        smb.percent_of_0_or_1_star_ratings_past_6_months,
        smb.count_of_reviews_source_g_past_6_months,
        smb.days_since_latest_review_past_6_months,
        smb.percent_80_quintile_of_rating_past_3_months,
        smb.individual_bankruptcy_filing_date_all_time,
        smb.days_between_earliest_and_latest_review_past_1_months,
        smb.percent_of_4_star_ratings_past_6_months,
        smb.count_of_address_line_1_all_time,
        smb.most_recent_judgement_status_date_all_time,
        smb.count_of_reviews_source_b_all_time,
        smb.closed_merchant_partnership_tradeline_hit_flag_past_3_mont,
        smb.count_of_delinquent_closed_merchant_partnerships_past_1_mo,
        smb.count_of_merchant_unknown_partnership_tradelines_past_3_mo,
        smb.count_of_address_line_1_past_12_months,
        smb.days_between_earliest_and_latest_merchant_partners_past_1,
        smb.days_between_earliest_and_latest_close_date_for_me_all_tim,
        smb.days_between_earliest_and_latest_merchant_partners_past_3,
        smb.count_of_decline_status_merchant_partnerships_all_time,
        smb.public_data_hit_flag_past_1_months,
        smb.percent_of_unanswered_resolved_status_past_1_months,
        smb.count_of_unique_zip5_past_6_months,
        smb.count_of_all_reviews_all_time,
        smb.count_of_closed_partner_merchant_partnerships_past_1_month,
        smb.count_of_reviews_source_j_past_6_months,
        smb.count_of_reviews_source_h_past_3_months,
        smb.complaint_data_source_a_hit_flag_past_12_months,
        smb.count_of_other_resolved_status_past_12_months,
        smb.percent_of_3_star_ratings_past_3_months,
        smb.count_of_closed_partner_merchant_partnerships_past_6_month,
        smb.count_of_unanswered_resolved_status_all_time,
        smb.average_rating_past_6_months,
        smb.count_of_complaint_containing_alert_words_past_6_months,
        smb.variance_of_rating_past_6_months,
        smb.count_of_merchant_inactive_partnership_tradelines_past_6_m,
        smb.count_of_unique_lenders_for_merchant_level_partner_past_3,
        smb.variance_of_rating_all_time,
        smb.count_of_reviews_source_g_past_3_months,
        smb.count_of_closed_other_partner_merchant_partnership_past_1,
        smb.count_of_reviews_source_a_all_time,
        smb.count_of_complaints_past_6_months,
        smb.count_of_reviews_source_j_all_time,
        smb.count_of_addresses_past_6_months,
        smb.count_of_3_star_ratings_past_6_months,
        smb.median_rating_all_time,
        smb.days_since_earliest_review_past_6_months,
        smb.count_of_reviews_source_i_past_3_months,
        smb.days_since_earliest_merchant_partnership_tradeline_past_1,
        smb.count_of_0_or_1_star_ratings_past_1_months,
        smb.standard_deviation_of_rating_all_time,
        smb.count_of_probation_partner_merchant_partnerships_all_time,
        smb.count_of_closed_compliance_partner_merchant_partne_past_3,
        smb.days_since_earliest_complaint_past_6_months,
        smb.count_of_merchant_partnerships_in_bad_standing_past_1_mont,
        smb.count_of_merchant_open_partnership_tradelines_past_6_month,
        smb.days_between_first_seen_and_last_seen_all_time,
        smb.percent_60_quintile_of_rating_past_1_months,
        smb.percent_20_quintile_of_rating_past_1_months,
        smb.days_since_latest_review_all_time,
        smb.number_of_business_liens_all_time,
        smb.count_of_merchant_closures_in_first_18_months_all_time,
        smb.count_of_unique_zip5_all_time,
        smb.count_of_other_resolved_status_past_6_months,
        smb.percent_of_reviews_source_g_past_3_months,
        smb.count_of_closed_fraud_partner_merchant_partnership_past_12,
        smb.count_of_suspended_partner_merchant_partnerships_all_time,
        smb.count_of_reviews_containing_alert_words_all_time,
        smb.total_amount_of_judgements_10_most_recent_all_time,
        smb.count_of_declined_partner_merchant_partnerships_past_3_mon,
        smb.total_voluntary_bankruptcies_all_time,
        smb.count_of_5_star_ratings_past_1_months,
        smb.days_between_earliest_and_latest_merchant_partners_all_tim,
        smb.count_of_states_past_24_months,
        smb.days_since_earliest_merchant_partnership_tradeline_past_6,
        smb.count_of_5_star_ratings_all_time,
        smb.count_of_unique_zip5_past_12_months,
        smb.most_recent_report_date_of_lien_filing_all_time,
        smb.total_number_of_judgements_that_the_individual_has_all_tim,
        smb.count_of_unanswered_resolved_status_past_1_months,
        smb.count_of_reviews_source_b_past_6_months,
        smb.count_of_unresolved_resolved_status_past_6_months,
        smb.days_since_earliest_update_past_6_months,
        smb.percent_of_other_resolved_status_past_6_months,
        smb.days_since_first_seen_all_time,
        smb.percent_of_source_a_unable_to_locate_business_resolved_s_past_3,
        smb.count_of_closed_other_partner_merchant_partnership_all_tim,
        smb.count_of_closed_other_partner_merchant_partnership_past_12,
        smb.count_of_closed_compliance_partner_merchant_partne_past_1,
        smb.count_of_merchant_partnerships_in_bad_standing_all_time,
        smb.merchant_partnership_tradelines_with_at_least_a_3__all_tim,
        smb.percent_20_quintile_of_rating_all_time,
        smb.count_of_merchant_inactive_partnership_tradelines_past_3_m,
        smb.days_since_latest_complaint_past_3_months,
        smb.count_of_4_star_ratings_past_3_months,
        smb.number_of_liens_the_individual_has_had_against_the_all_tim,
        smb.count_of_5_star_ratings_past_6_months,
        smb.number_of_associates_on_watch_list_all_time,
        smb.percent_of_reviews_source_j_past_6_months,
        smb.percent_of_reviews_source_b_past_1_months,
        smb.count_of_reviews_containing_alert_words_past_1_months,
        smb.percent_of_5_star_ratings_past_1_months,
        smb.percent_of_source_a_unable_to_locate_business_resolved_all_tim,
        smb.count_of_all_reviews_past_1_months,
        smb.corporate_filing_secretary_of_state_status_date_all_time,
        smb.average_rating_past_1_months,
        smb.merchant_partnership_tradeline_hit_flag_past_12_months,
        smb.closed_merchant_partnership_tradeline_hit_flag_past_6_mont,
        smb.percent_of_4_star_ratings_past_1_months,
        smb.count_of_closed_underwriting_partner_merchant_part_past_12,
        smb.days_since_earliest_review_past_1_months,
        smb.corporate_filing_secretary_of_state_status_all_time,
        smb.most_recent_bankruptcy_chapter_all_time,
        smb.percent_of_source_a_unable_to_locate_business_resolved_s_past_6,
        smb.count_of_unique_address_line_1_all_time,
        smb.percent_of_complaints_containing_alert_words_all_time,
        smb.count_of_complaints_all_time,
        smb.count_of_closed_out_of_business_partner_merchant_p_all_tim,
        smb.count_of_unique_cities_past_12_months,
        smb.percent_of_complaints_containing_alert_words_past_12_months,
        smb.percent_60_quintile_of_rating_past_3_months,
        smb.days_since_latest_complaint_all_time,
        smb.days_between_earliest_and_latest_complaint_past_12_months,
        smb.days_since_latest_complaint_past_12_months,
        smb.days_since_first_seen_past_24_months,
        smb.days_between_earliest_and_latest_review_all_time,
        smb.count_of_probation_partner_merchant_partnerships_past_1_mo,
        smb.count_of_closed_out_of_business_partner_merchant_p_past_12,
        smb.percent_of_reviews_source_h_past_3_months,
        smb.percent_of_reviews_source_e_past_3_months,
        smb.count_of_reviews_source_i_past_6_months,
        smb.percent_80_quintile_of_rating_all_time,
        smb.count_of_merchant_unknown_partnership_tradelines_past_1_mo,
        smb.count_of_duplicate_reviewers_past_6_months,
        smb.count_of_source_a_unable_to_locate_business_resolv_past_12,
        smb.days_since_latest_close_date_for_merchant_partners_past_3,
        smb.count_of_3_star_ratings_all_time,
        smb.percent_of_unresolved_resolved_status_past_3_months,
        smb.count_of_delinquent_closed_merchant_partnerships_past_3_mo,
        smb.count_of_addresses_past_12_months,
        smb.is_license_expired_all_time,
        smb.count_of_closed_underwriting_partner_merchant_part_all_tim,
        smb.count_of_resolved_resolved_status_past_3_months,
        smb.count_of_delinquent_closed_merchant_partnerships_past_6_mo,
        smb.count_of_suspended_partner_merchant_partnerships_past_3_mo,
        smb.count_of_reviews_source_e_past_3_months,
        smb.percent_of_resolved_resolved_status_past_3_months,
        smb.percent_of_unanswered_resolved_status_all_time,
        smb.md_officer_1_name,
        smb.md_officer_1_title,
        smb.md_officer_2_name,
        smb.md_officer_2_title,
        bcm.created_at,
        smb.zi_match_confidence,
        vfj.business_entity_verification_id,
        vfj.formation_date AS corporate_filling_file_date,
        vfj.name_verification,
        vfj.address_verification,
        vfj.tin_verification,
        vfj.watchlist_verification,
        vfj.sos_domestic_verification,
        vfj.sos_match_verification,
        vfj.sos_active_verification,
        sc.worth_score,
        sc.score_base_value,
        sc.score_financial_trends,
        sc.score_public_records,
        sc.score_business_operations,
        sc.score_company_profile,
        sc.score_performance_measures,
        customer_id
    FROM datascience.smb_zi_oc_efx_combined AS smb
        LEFT JOIN
    clients.verification_results AS vfj
                USING (business_id)
        LEFT JOIN
    score_components AS sc
                USING (business_id)
        LEFT JOIN
    rds_cases_public.rel_business_customer_monitoring AS bcm
                USING (business_id)
    QUALIFY ROW_NUMBER() OVER (PARTITION BY customer_id, business_id ORDER BY created_at DESC) = 1;

END;
$$
