CREATE OR REPLACE PROCEDURE public.sp_truncate_and_insert_smb_zi_oc_efx_combined_recreate()
    LANGUAGE plpgsql
AS

$$
BEGIN

    CALL public.sp_truncate_and_insert_efx_matches_custom_inc_ml();
    CALL public.sp_truncate_and_insert_zoominfo_matches_custom_inc_ml();
    CALL public.sp_truncate_and_insert_oc_matches_custom_inc_ml();
    CALL public.sp_create_equifax_latest_tables();
    DROP TABLE IF EXISTS warehouse.oc_companies_latest;
    CREATE TABLE warehouse.oc_companies_latest AS
    SELECT
        *
    FROM open_corporate.companies
    WHERE company_number IN (SELECT company_number FROM datascience.oc_matches_custom_inc_ml);
    -- Step 11: https://worth-ai.atlassian.net/browse/INFRA-65
    DROP TABLE IF EXISTS datascience.smb_zi_oc_efx_combined;


    CREATE TABLE datascience.smb_zi_oc_efx_combined DISTKEY ( business_id )
                                                    INTERLEAVED SORTKEY (business_id) AS
    WITH

        efx_cte AS (SELECT
                        business_id,
                        mds.efx_id,
                        CASE
                            WHEN lk.efx_probability IS NOT NULL THEN lk.efx_probability
                            WHEN lk.similarity_index IS NOT NULL AND lk.similarity_index / 55.0 >= 0.8
                                THEN lk.similarity_index / 55.0
                            ELSE 0
                        END AS efx_match_confidence,
                        mds.efx_name,
                        mds.efx_legal_name,
                        mds.efx_address,
                        mds.efx_city,
                        mds.efx_state,
                        mds.efx_statec,
                        mds.efx_zipcode,
                        mds.efx_zip4,
                        mds.efx_lat,
                        mds.efx_lon,
                        mds.efx_geoprec,
                        mds.efx_region,
                        mds.efx_ctryisocd,
                        mds.efx_ctrynum,
                        mds.efx_ctryname,
                        mds.efx_countynm,
                        mds.efx_county,
                        mds.efx_cmsa,
                        mds.efx_cmsadesc,
                        mds.efx_soho,
                        mds.efx_biz,
                        mds.efx_res,
                        mds.efx_cmra,
                        mds.efx_congress,
                        mds.efx_secadr,
                        mds.efx_seccty,
                        mds.efx_secstat,
                        mds.efx_statec2,
                        mds.efx_seczip,
                        mds.efx_seczip4,
                        mds.efx_seclat,
                        mds.efx_seclon,
                        mds.efx_secgeoprec,
                        mds.efx_secregion,
                        mds.efx_secctryisocd,
                        mds.efx_secctrynum,
                        mds.efx_secctryname,
                        mds.efx_ctrytelcd,
                        mds.efx_phone,
                        mds.efx_faxphone,
                        mds.efx_contct,
                        mds.efx_titlecd,
                        mds.efx_titledesc,
                        mds.efx_lastnam,
                        mds.efx_fstnam,
                        mds.efx_email,
                        mds.efx_ceoname,
                        mds.efx_ceotitledesc,
                        mds.efx_cioname,
                        mds.efx_ciotitledesc,
                        mds.efx_cfoname,
                        mds.efx_cfotitledesc,
                        mds.efx_gender,
                        mds.efx_ethnicity,
                        mds.efx_mbe,
                        mds.efx_wbe,
                        mds.efx_vet,
                        mds.efx_bussize,
                        mds.efx_gov,
                        mds.efx_fgov,
                        mds.efx_nonprofit,
                        mds.efx_edu,
                        mds.efx_busstat,
                        mds.efx_busstatcd,
                        mds.efx_web,
                        mds.efx_yrest,
                        mds.efx_corpempcnt,
                        mds.efx_locempcnt,
                        mds.efx_corpempcd,
                        mds.efx_locempcd,
                        mds.efx_corpamount,
                        mds.efx_corpamountcd,
                        mds.efx_corpamounttp,
                        mds.efx_corpamountprec,
                        mds.efx_locamount,
                        mds.efx_locamountcd,
                        mds.efx_locamounttp,
                        mds.efx_locamountprec,
                        mds.efx_public,
                        mds.efx_stkexc,
                        mds.efx_tcksym,
                        mds.efx_primsic,
                        mds.efx_secsic1,
                        mds.efx_secsic2,
                        mds.efx_secsic3,
                        mds.efx_secsic4,
                        mds.efx_primsicdesc,
                        mds.efx_secsicdesc1,
                        mds.efx_secsicdesc2,
                        mds.efx_secsicdesc3,
                        mds.efx_secsicdesc4,
                        mds.efx_primnaicscode,
                        mds.efx_secnaics1,
                        mds.efx_secnaics2,
                        mds.efx_secnaics3,
                        mds.efx_secnaics4,
                        mds.efx_primnaicsdesc,
                        mds.efx_secnaicsdesc1,
                        mds.efx_secnaicsdesc2,
                        mds.efx_secnaicsdesc3,
                        mds.efx_secnaicsdesc4,
                        mds.efx_legsubnumall,
                        mds.efx_legsubnameall,
                        mds.efx_legsubaddressall,
                        mds.efx_legsubcityall,
                        mds.efx_legsubstateall,
                        mds.efx_legsubzipcodeall,
                        mds.efx_legsubzip4all,
                        mds.efx_legsubcountyall,
                        mds.efx_legsubctryisocdall,
                        mds.efx_legsubctrynumall,
                        mds.efx_legsubctrynameall,
                        mds.efx_legdomultnumall,
                        mds.efx_legdomultnameall,
                        mds.efx_legdomultaddressall,
                        mds.efx_legdomultcityall,
                        mds.efx_legdomultstateall,
                        mds.efx_legdomultzipcodeall,
                        mds.efx_legdomultzip4all,
                        mds.efx_legdomultcountyall,
                        mds.efx_legdomultctryisocdall,
                        mds.efx_legdomultctrynumall,
                        mds.efx_legdomultctrynameall,
                        mds.efx_legultnumall,
                        mds.efx_legultnameall,
                        mds.efx_legultaddressall,
                        mds.efx_legultcityall,
                        mds.efx_legultstateall,
                        mds.efx_legultzipcodeall,
                        mds.efx_legultzip4all,
                        mds.efx_legultcountyall,
                        mds.efx_legultctryisocdall,
                        mds.efx_legultctrynumall,
                        mds.efx_legultctrynameall,
                        mds.efx_legultparentind,
                        mds.efx_legparentind,
                        mds.efx_leglinkedind,
                        mds.efx_afflultnumall,
                        mds.efx_afflultnameall,
                        mds.efx_afflultaddressall,
                        mds.efx_afflultcityall,
                        mds.efx_afflultstateall,
                        mds.efx_afflultzipcodeall,
                        mds.efx_afflultzip4all,
                        mds.efx_affultcountyall,
                        mds.efx_afflultctryisocdall,
                        mds.efx_afflultctrynumall,
                        mds.efx_afflultctrynameall,
                        mds.efx_affllinkedind,
                        mds.efx_franchise,
                        mds.efx_afflultparentind,
                        mds.efx_afflparentind,
                        mds.efx_foreign,
                        mds.efx_failrate,
                        mds.efx_faillevel,
                        mds.efx_failreason1,
                        mds.efx_failreason2,
                        mds.efx_failreason3,
                        mds.efx_failreason4,
                        mds.efx_creditscore,
                        mds.efx_creditclass,
                        mds.efx_creditperc,
                        mds.efx_creditreason1,
                        mds.efx_creditreason2,
                        mds.efx_creditreason3,
                        mds.efx_creditreason4,
                        mds.efx_bankruptcy,
                        mds.efx_dead,
                        mds.efx_deaddt,
                        mds.efx_mrkt_telever,
                        mds.efx_mrkt_telescore,
                        mds.efx_mrkt_totalscore,
                        mds.efx_mrkt_totalind,
                        mds.efx_mrkt_vacant,
                        mds.efx_mrkt_seasonal,
                        mds.efx_extract_date,
                        mds.efx_date_updated,
                        mds.currentcty_4_avg,
                        mds.currentst_4_avg,
                        mds."12monthpriorcty_4_avg",
                        mds."12monthpriorst_4_avg",
                        mds.efx_merchant_id,
                        mds.efx_project_id,
                        mds.twelvemonthpriorcty_4_avg,
                        mds.twelvemonthpriorst_4_avg,
                        mds.efx_mwbe,
                        mds.efx_sdb,
                        mds.efx_hubzone,
                        mds.efx_dbe,
                        mds.efx_dvet,
                        mds.efx_8a,
                        mds.efx_8aexpdt,
                        mds.efx_dis,
                        mds.efx_sbe,
                        mds.efx_hbcu,
                        mds.efx_gaylesbian,
                        mds.efx_wsbe,
                        mds.efx_vsbe,
                        mds.efx_dvsbe,
                        mds.efx_mwbestatus,
                        mds.efx_nmsdc,
                        mds.efx_wbenc,
                        mds.efx_ca_puc,
                        mds.efx_tx_hub,
                        mds.efx_tx_hubcertnum,
                        mds.efx_gsax,
                        mds.efx_caltrans,
                        mds.efx_mi,
                        mds.efx_anc,
                        mds.efx_cert1,
                        mds.efx_cert2,
                        mds.efx_cert3,
                        mds.efx_cert4,
                        mds.efx_cert5,
                        mds.efx_cert6,
                        mds.efx_cert7,
                        mds.efx_cert8,
                        mds.efx_cert9,
                        mds.efx_cert10,
                        mds.efx_certdesc1,
                        mds.efx_certdesc2,
                        mds.efx_certdesc3,
                        mds.efx_certdesc4,
                        mds.efx_certdesc5,
                        mds.efx_certdesc6,
                        mds.efx_certdesc7,
                        mds.efx_certdesc8,
                        mds.efx_certdesc9,
                        mds.efx_certdesc10,
                        mds.efx_certsrc1,
                        mds.efx_certsrc2,
                        mds.efx_certsrc3,
                        mds.efx_certsrc4,
                        mds.efx_certsrc5,
                        mds.efx_certsrc6,
                        mds.efx_certsrc7,
                        mds.efx_certsrc8,
                        mds.efx_certsrc9,
                        mds.efx_certsrc10,
                        mds.efx_certlev1,
                        mds.efx_certlev2,
                        mds.efx_certlev3,
                        mds.efx_certlev4,
                        mds.efx_certlev5,
                        mds.efx_certlev6,
                        mds.efx_certlev7,
                        mds.efx_certlev8,
                        mds.efx_certlev9,
                        mds.efx_certlev10,
                        mds.efx_certnum1,
                        mds.efx_certnum2,
                        mds.efx_certnum3,
                        mds.efx_certnum4,
                        mds.efx_certnum5,
                        mds.efx_certnum6,
                        mds.efx_certnum7,
                        mds.efx_certnum8,
                        mds.efx_certnum9,
                        mds.efx_certnum10,
                        mds.efx_certexp1,
                        mds.efx_certexp2,
                        mds.efx_certexp3,
                        mds.efx_certexp4,
                        mds.efx_certexp5,
                        mds.efx_certexp6,
                        mds.efx_certexp7,
                        mds.efx_certexp8,
                        mds.efx_certexp9,
                        mds.efx_certexp10,
                        mds.efx_legentityparentnum,
                        mds.efx_legentityparentname,
                        mds.efx_legentitysubsidiaryind,
                        mds.efx_legentityind,
                        mds.efx_cancreditscorecds,
                        mds.efx_cancreditrejcdcds,
                        mds.efx_cancreditreason3cds,
                        mds.efx_cancreditreason4cds,
                        mds.efx_cancreditscorebfrs,
                        mds.efx_cancreditrejcdbfrs,
                        mds.efx_cancreditreason1bfrs,
                        mds.efx_cancreditreason2bfrs,
                        mds.efx_cancreditdate,
                        mds.efx_affldomultnumall,
                        mds.efx_affldomultnameall,
                        mds.efx_affldomultaddressall,
                        mds.efx_affldomultcityall,
                        mds.efx_affldomultstateall,
                        mds.efx_affldomultzipcodeall,
                        mds.efx_affldomultzip4all,
                        mds.efx_affldomultcountyall,
                        mds.efx_affldomultctryisocdall,
                        mds.efx_affldomultctrynumall,
                        mds.efx_affldomultctrynameall,
                        mds.efx_lbe,
                        mds.efx_gov1057,
                        mds.efx_merctype
                    -- bma.efxbma_1m_ind_2c_past_due_count,
                    -- bma.efxbma_1m_ind_2pc_past_due_count,
                    -- bma.efxbma_1m_ind_3c_past_due_count,
                    -- bma.efxbma_1m_ind_3pc_past_due_count,
                    -- bma.efxbma_1m_ind_4pc_past_due_count,
                    -- bma.efxbma_1m_ind_tr_count,
                    -- bma.efxbma_1m_ind_tr_total_bal,
                    -- bma.efxbma_1m_ind_worst_payment_status,
                    -- bma.efxbma_1m_nfin_1c_past_due_count,
                    -- bma.efxbma_1m_nfin_1pc_past_due_count,
                    -- bma.efxbma_1m_nfin_2c_past_due_count,
                    -- bma.efxbma_1m_nfin_2pc_past_due_count,
                    -- bma.efxbma_1m_nfin_3c_past_due_count,
                    -- bma.efxbma_1m_nfin_3pc_past_due_count,
                    -- bma.efxbma_1m_nfin_4pc_past_due_count,
                    -- bma.efxbma_1m_nfin_chargeoff_tr_count,
                    -- bma.efxbma_1m_nfin_closed_acc_count,
                    -- bma.efxbma_1m_nfin_curr_credit_lim,
                    -- bma.efxbma_1m_nfin_open_acc_count,
                    -- bma.efxbma_1m_nfin_orig_credit_lim,
                    -- bma.efxbma_1m_nfin_past_due_amount,
                    -- bma.efxbma_1m_nfin_payment_index,
                    -- bma.efxbma_1m_nfin_per_satisfactory_acc,
                    -- bma.efxbma_1m_nfin_satisfactory_tr_count,
                    -- bma.efxbma_1m_nfin_total_chargeoff_amt,
                    -- bma.efxbma_1m_nfin_total_util,
                    -- bma.efxbma_1m_nfin_tr_count,
                    -- bma.efxbma_1m_nfin_tr_total_bal,
                    -- bma.efxbma_1m_nfin_worst_payment_status,
                    -- bma.efxbma_1m_serv_tr_count,
                    -- bma.efxbma_1m_serv_tr_total_bal,
                    -- bma.efxbma_1m_tel_1c_past_due_count,
                    -- bma.efxbma_1m_tel_1pc_past_due_count,
                    -- bma.efxbma_1m_tel_2c_past_due_count,
                    -- bma.efxbma_1m_tel_2pc_past_due_count,
                    -- bma.efxbma_1m_tel_3c_past_due_count,
                    -- bma.efxbma_1m_tel_3pc_past_due_count,
                    -- bma.efxbma_1m_tel_4pc_past_due_count,
                    -- bma.efxbma_1m_tel_tr_count,
                    -- bma.efxbma_1m_tel_tr_total_bal,
                    -- bma.efxbma_1m_tel_worst_payment_status,
                    -- bma.efxbma_1m_util_1c_past_due_count,
                    -- bma.efxbma_1m_util_1pc_past_due_count,
                    -- bma.efxbma_1m_util_2c_past_due_count,
                    -- bma.efxbma_1m_util_2pc_past_due_count,
                    -- bma.efxbma_1m_util_3c_past_due_count,
                    -- bma.efxbma_1m_util_3pc_past_due_count,
                    -- bma.efxbma_1m_util_4pc_past_due_count,
                    -- bma.efxbma_1m_util_tr_count,
                    -- bma.efxbma_1m_util_tr_total_bal,
                    -- bma.efxbma_1m_util_worst_payment_status,
                    -- bma.efxbma_3m_ind_1c_past_due_count,
                    -- bma.efxbma_3m_ind_1pc_past_due_count,
                    -- bma.efxbma_3m_ind_2c_past_due_count,
                    -- bma.efxbma_3m_ind_2pc_past_due_count,
                    -- bma.efxbma_3m_ind_3c_past_due_count,
                    -- bma.efxbma_3m_ind_3pc_past_due_count,
                    -- bma.efxbma_3m_ind_4pc_past_due_count,
                    -- bma.efxbma_3m_ind_tr_count,
                    -- bma.efxbma_3m_ind_tr_high_bal,
                    -- bma.efxbma_3m_ind_tr_wb_count,
                    -- bma.efxbma_3m_ind_worst_payment_status,
                    -- bma.efxbma_3m_nfin_1c_past_due_amount,
                    -- bma.efxbma_3m_nfin_1c_past_due_count,
                    -- bma.efxbma_3m_nfin_1pc_past_due_count,
                    -- bma.efxbma_3m_nfin_2c_past_due_amount,
                    -- bma.efxbma_3m_nfin_2c_past_due_count,
                    -- bma.efxbma_3m_nfin_2pc_past_due_count,
                    -- bma.efxbma_3m_nfin_3c_past_due_amount,
                    -- bma.efxbma_3m_nfin_3c_past_due_count,
                    -- bma.efxbma_3m_nfin_3pc_past_due_count,
                    -- bma.efxbma_3m_nfin_4pc_past_due_amount,
                    -- bma.efxbma_3m_nfin_4pc_past_due_count,
                    -- bma.efxbma_3m_nfin_chargeoff_tr_count,
                    -- bma.efxbma_3m_nfin_high_credit_lim,
                    -- bma.efxbma_3m_nfin_new_acc_count,
                    -- bma.efxbma_3m_nfin_orig_credit_lim,
                    -- bma.efxbma_3m_nfin_past_due_amount,
                    -- bma.efxbma_3m_nfin_per_4pc_pd_to_totbal,
                    -- bma.efxbma_3m_nfin_per_coff_to_tot_acc,
                    -- bma.efxbma_3m_nfin_per_pd_to_totbal,
                    -- bma.efxbma_3m_nfin_per_satisfactory_acc,
                    -- bma.efxbma_3m_nfin_ratio_num_nondel_to_acc,
                    -- bma.efxbma_3m_nfin_satisfactory_tr_count,
                    -- bma.efxbma_3m_nfin_total_chargeoff_amt,
                    -- bma.efxbma_3m_nfin_total_util,
                    -- bma.efxbma_3m_nfin_tr_count,
                    -- bma.efxbma_3m_nfin_tr_high_bal,
                    -- bma.efxbma_3m_nfin_tr_wb_count,
                    -- bma.efxbma_3m_nfin_worst_payment_status,
                    -- bma.efxbma_3m_serv_past_due_amount,
                    -- bma.efxbma_3m_serv_tr_count,
                    -- bma.efxbma_3m_serv_tr_high_bal,
                    -- bma.efxbma_3m_serv_tr_wb_count,
                    -- bma.efxbma_3m_tel_1c_past_due_count,
                    -- bma.efxbma_3m_tel_1pc_past_due_count,
                    -- bma.efxbma_3m_tel_2c_past_due_count,
                    -- bma.efxbma_3m_tel_2pc_past_due_count,
                    -- bma.efxbma_3m_tel_3c_past_due_count,
                    -- bma.efxbma_3m_tel_3pc_past_due_count,
                    -- bma.efxbma_3m_tel_4pc_past_due_count,
                    -- bma.efxbma_3m_tel_tr_count,
                    -- bma.efxbma_3m_tel_tr_high_bal,
                    -- bma.efxbma_3m_tel_tr_wb_count,
                    -- bma.efxbma_3m_tel_worst_payment_status,
                    -- bma.efxbma_3m_util_1c_past_due_count,
                    -- bma.efxbma_3m_util_1pc_past_due_count,
                    -- bma.efxbma_3m_util_2c_past_due_count,
                    -- bma.efxbma_3m_util_2pc_past_due_count,
                    -- bma.efxbma_3m_util_3c_past_due_count,
                    -- bma.efxbma_3m_util_3pc_past_due_count,
                    -- bma.efxbma_3m_util_4pc_past_due_count,
                    -- bma.efxbma_3m_util_tr_count,
                    -- bma.efxbma_3m_util_tr_high_bal,
                    -- bma.efxbma_3m_util_tr_wb_count,
                    -- bma.efxbma_3m_util_worst_payment_status,
                    -- bma.efxbma_12m_ind_1c_past_due_count,
                    -- bma.efxbma_12m_ind_1pc_past_due_count,
                    -- bma.efxbma_12m_ind_2c_past_due_count,
                    -- bma.efxbma_12m_ind_2pc_past_due_count,
                    -- bma.efxbma_12m_ind_3c_past_due_count,
                    -- bma.efxbma_12m_ind_3pc_past_due_count,
                    -- bma.efxbma_12m_ind_4pc_past_due_count,
                    -- bma.efxbma_12m_ind_tr_count,
                    -- bma.efxbma_12m_ind_tr_high_bal,
                    -- bma.efxbma_12m_ind_worst_payment_status,
                    -- bma.efxbma_12m_nfin_1c_past_due_amount,
                    -- bma.efxbma_12m_nfin_1c_past_due_count,
                    -- bma.efxbma_12m_nfin_1pc_past_due_count,
                    -- bma.efxbma_12m_nfin_2c_past_due_amount,
                    -- bma.efxbma_12m_nfin_2c_past_due_count,
                    -- bma.efxbma_12m_nfin_2pc_past_due_count,
                    -- bma.efxbma_12m_nfin_3c_past_due_amount,
                    -- bma.efxbma_12m_nfin_3c_past_due_count,
                    -- bma.efxbma_12m_nfin_3pc_past_due_count,
                    -- bma.efxbma_12m_nfin_4pc_past_due_amount,
                    -- bma.efxbma_12m_nfin_4pc_past_due_count,
                    -- bma.efxbma_12m_nfin_chargeoff_tr_count,
                    -- bma.efxbma_12m_nfin_high_credit_lim,
                    -- bma.efxbma_12m_nfin_orig_credit_lim,
                    -- bma.efxbma_12m_nfin_past_due_amount,
                    -- bma.efxbma_12m_nfin_per_4pc_pd_to_totbal,
                    -- bma.efxbma_12m_nfin_per_coff_to_tot_acc,
                    -- bma.efxbma_12m_nfin_per_pd_to_totbal,
                    -- bma.efxbma_12m_nfin_per_satisfactory_acc,
                    -- bma.efxbma_12m_nfin_satisfactory_tr_count,
                    -- bma.efxbma_12m_nfin_total_chargeoff_amt,
                    -- bma.efxbma_12m_nfin_total_util,
                    -- bma.efxbma_12m_nfin_tr_count,
                    -- bma.efxbma_12m_nfin_tr_high_bal,
                    -- bma.efxbma_12m_nfin_worst_payment_status,
                    -- bma.efxbma_12m_serv_tr_count,
                    -- bma.efxbma_12m_serv_tr_high_bal,
                    -- bma.efxbma_12m_tel_1c_past_due_count,
                    -- bma.efxbma_12m_tel_1pc_past_due_count,
                    -- bma.efxbma_12m_tel_2c_past_due_count,
                    -- bma.efxbma_12m_tel_2pc_past_due_count,
                    -- bma.efxbma_12m_tel_3c_past_due_count,
                    -- bma.efxbma_12m_tel_3pc_past_due_count,
                    -- bma.efxbma_12m_tel_4pc_past_due_count,
                    -- bma.efxbma_12m_tel_tr_count,
                    -- bma.efxbma_12m_tel_tr_high_bal,
                    -- bma.efxbma_12m_tel_worst_payment_status,
                    -- bma.efxbma_12m_util_1c_past_due_count,
                    -- bma.efxbma_12m_util_1pc_past_due_count,
                    -- bma.efxbma_12m_util_2c_past_due_count,
                    -- bma.efxbma_12m_util_2pc_past_due_count,
                    -- bma.efxbma_12m_util_3c_past_due_count,
                    -- bma.efxbma_12m_util_3pc_past_due_count,
                    -- bma.efxbma_12m_util_4pc_past_due_count,
                    -- bma.efxbma_12m_util_tr_count,
                    -- bma.efxbma_12m_util_tr_high_bal,
                    -- bma.efxbma_12m_util_worst_payment_status,
                    -- bma.efxbma_24m_ind_1c_past_due_count,
                    -- bma.efxbma_24m_ind_1pc_past_due_count,
                    -- bma.efxbma_24m_ind_2c_past_due_count,
                    -- bma.efxbma_24m_ind_2pc_past_due_count,
                    -- bma.efxbma_24m_ind_3c_past_due_count,
                    -- bma.efxbma_24m_ind_3pc_past_due_count,
                    -- bma.efxbma_24m_ind_4pc_past_due_count,
                    -- bma.efxbma_24m_ind_tr_count,
                    -- bma.efxbma_24m_ind_tr_high_bal,
                    -- bma.efxbma_24m_ind_worst_payment_status,
                    -- bma.efxbma_24m_nfin_1c_past_due_amount,
                    -- bma.efxbma_24m_nfin_1c_past_due_count,
                    -- bma.efxbma_24m_nfin_1pc_past_due_count,
                    -- bma.efxbma_24m_nfin_2c_past_due_amount,
                    -- bma.efxbma_24m_nfin_2c_past_due_count,
                    -- bma.efxbma_24m_nfin_2pc_past_due_count,
                    -- bma.efxbma_24m_nfin_3c_past_due_amount,
                    -- bma.efxbma_24m_nfin_3c_past_due_count,
                    -- bma.efxbma_24m_nfin_3pc_past_due_count,
                    -- bma.efxbma_24m_nfin_4pc_past_due_amount,
                    -- bma.efxbma_24m_nfin_4pc_past_due_count,
                    -- bma.efxbma_24m_nfin_chargeoff_tr_count,
                    -- bma.efxbma_24m_nfin_high_credit_lim,
                    -- bma.efxbma_24m_nfin_orig_credit_lim,
                    -- bma.efxbma_24m_nfin_past_due_amount,
                    -- bma.efxbma_24m_nfin_per_4pc_pd_to_totbal,
                    -- bma.efxbma_24m_nfin_per_coff_to_tot_acc,
                    -- bma.efxbma_24m_nfin_per_pd_to_totbal,
                    -- bma.efxbma_24m_nfin_per_satisfactory_acc,
                    -- bma.efxbma_24m_nfin_satisfactory_tr_count,
                    -- bma.efxbma_24m_nfin_total_chargeoff_amt,
                    -- bma.efxbma_24m_nfin_total_util,
                    -- bma.efxbma_24m_nfin_tr_count,
                    -- bma.efxbma_24m_nfin_tr_high_bal,
                    -- bma.efxbma_24m_nfin_worst_payment_status,
                    -- bma.efxbma_24m_serv_tr_count,
                    -- bma.efxbma_24m_serv_tr_high_bal,
                    -- bma.efxbma_24m_tel_1c_past_due_count,
                    -- bma.efxbma_24m_tel_1pc_past_due_count,
                    -- bma.efxbma_24m_tel_2c_past_due_count,
                    -- bma.efxbma_24m_tel_2pc_past_due_count,
                    -- bma.efxbma_24m_tel_3c_past_due_count,
                    -- bma.efxbma_24m_tel_3pc_past_due_count,
                    -- bma.efxbma_24m_tel_4pc_past_due_count,
                    -- bma.efxbma_24m_tel_tr_count,
                    -- bma.efxbma_24m_tel_tr_high_bal,
                    -- bma.efxbma_24m_tel_worst_payment_status,
                    -- bma.efxbma_24m_util_1c_past_due_count,
                    -- bma.efxbma_24m_util_1pc_past_due_count,
                    -- bma.efxbma_24m_util_2c_past_due_count,
                    -- bma.efxbma_24m_util_2pc_past_due_count,
                    -- bma.efxbma_24m_util_3c_past_due_count,
                    -- bma.efxbma_24m_util_3pc_past_due_count,
                    -- bma.efxbma_24m_util_4pc_past_due_count,
                    -- bma.efxbma_24m_util_tr_count,
                    -- bma.efxbma_24m_util_tr_high_bal,
                    -- bma.efxbma_24m_util_worst_payment_status,
                    -- bma.efxbma_pubrec_age_bkp,
                    -- bma.efxbma_pubrec_age_judg,
                    -- bma.efxbma_pubrec_age_lien,
                    -- bma.efxbma_pubrec_age_pr,
                    -- bma.efxbma_pubrec_bkp_ind,
                    -- bma.efxbma_pubrec_judg_ind,
                    -- bma.efxbma_pubrec_lien_ind,
                    -- bma.efxbma_pubrec_lien_judg_ind,
                    -- bma.efxbma_pubrec_max_liab_rep_judg,
                    -- bma.efxbma_pubrec_max_liab_rep_lien,
                    -- bma.efxbma_pubrec_status_fi,
                    -- bma.efxbma_pubrec_status_fi_ju,
                    -- bma.efxbma_pubrec_status_ju,
                    -- bma.efxbma_pubrec_sum_lien_all_judg,
                    -- bma.efxbma_pubrec_total_cur_liab_judg,
                    -- bma.efxbma_pubrec_total_cur_liab_judg_all,
                    -- bma.efxbma_pubrec_total_cur_liab_lien,
                    -- bma.efxbma_pubrec_total_cur_liab_lien_all,
                    -- bma.efxbma_pubrec_total_cur_liab_lien_judg,
                    -- bma.efxbma_pubrec_total_judg,
                    -- bma.efxbma_pubrec_total_lien,
                    -- bma.efxbma_pubrec_total_lien_judg,
                    -- bma.efxbma_1m_ind_1c_past_due_count,
                    -- bma.efxbma_1m_ind_1pc_past_due_count,
                    -- bma.efxbma_extract_date
                    FROM datascience.efx_matches_custom_inc_ml lk
                        LEFT JOIN warehouse.equifax_us_latest AS mds
                                USING (efx_id)
            -- LEFT JOIN warehouse.equifax_bma_latest AS bma
            --         USING (efx_id)
        ),
        zi_cte AS (SELECT
                       business_id,
                       zi_c_location_id,
                       zi_c_company_id,
                       zi_es_location_id,
                       CASE
                           WHEN zi_probability IS NOT NULL THEN zi_probability
                           WHEN similarity_index IS NOT NULL AND similarity_index / 55.0 >= 0.8
                               THEN similarity_index / 55.0
                           ELSE 0
                       END AS zi_match_confidence
                   FROM datascience.zoominfo_matches_custom_inc_ml
        ),
        oc_cte AS (SELECT
                       business_id,
                       company_number,
                       jurisdiction_code,
                       CASE
                           WHEN oc_probability IS NOT NULL THEN oc_probability
                           WHEN similarity_index / 55.0 >= 0.8 THEN similarity_index / 55.0
                           ELSE 0
                       END AS oc_match_confidence
                   FROM datascience.oc_matches_custom_inc_ml
        ),
        zcs_cte AS (SELECT
                        *
                    FROM zoominfo.comp_standard_global
                    WHERE zi_c_country = 'United States'
                      AND (zi_c_company_id, zi_es_location_id, zi_c_location_id) IN
                          (SELECT
                               zi_c_company_id,
                               zi_es_location_id,
                               zi_c_location_id
                           FROM zi_cte
                          )
        ),
        oco_cte AS (SELECT
                        company_number,
                        jurisdiction_code,
                        MAX(CASE WHEN rn = 1 THEN name ELSE NULL END)  AS officer_1_name,
                        MAX(CASE WHEN rn = 1 THEN title ELSE NULL END) AS officer_1_title,
                        MAX(CASE WHEN rn = 2 THEN name ELSE NULL END)  AS officer_2_name,
                        MAX(CASE WHEN rn = 2 THEN title ELSE NULL END) AS officer_2_title
                    FROM (SELECT
                              company_number,
                              jurisdiction_code,
                              UPPER(name)                                                           AS name,
                              UPPER(CASE
                                        WHEN TRIM(title) IS NOT NULL AND TRIM(title) != '' THEN title
                                        ELSE position
                                    END)                                                            AS title,
                              ROW_NUMBER()
                              OVER (PARTITION BY company_number, jurisdiction_code ORDER BY id ASC) AS rn
                          FROM open_corporate.officers
                    ) t1
                    GROUP BY
                        company_number,
                        jurisdiction_code
        ),
        bep_cte AS (SELECT
                        business_id,
                        MAX(CASE WHEN rn = 1 THEN name ELSE NULL END)  AS md_officer_1_name,
                        MAX(CASE WHEN rn = 1 THEN title ELSE NULL END) AS md_officer_1_title,
                        MAX(CASE WHEN rn = 2 THEN name ELSE NULL END)  AS md_officer_2_name,
                        MAX(CASE WHEN rn = 2 THEN title ELSE NULL END) AS md_officer_2_title
                    FROM (SELECT
                              business_id,
                              UPPER(bep.name)                                                      AS name,
                              UPPER(SPLIT_PART(REPLACE(REPLACE(REPLACE(bep.titles, '{', ''), '}', ''), '"', ''), ',',
                                               1))                                                 AS title,
                              ROW_NUMBER() OVER (PARTITION BY business_id ORDER BY bep.created_at) AS rn
                          FROM rds_integration_data.business_entity_people bep
                              JOIN rds_integration_data.business_entity_verification bev
                                      ON bep.business_entity_verification_id = bev.id
                    ) bep
                    GROUP BY
                        business_id
        )
    SELECT
        smb.business_id,
        smb.latest_requested_at,
        smb.external_id                                                    AS customer_unique_identifier,
        COALESCE(data_businesses.name, smb.company_name)                   AS company_name,
        smb.company_dba,
        COALESCE(ver.beas_address_line_1, smb.company_address)             AS company_address,
        COALESCE(ver.beas_address_line_2, smb.company_address_2)           AS company_address_2,
        COALESCE(ver.beas_city, smb.company_city)                          AS company_city,
        COALESCE(ver.beas_state, smb.company_state)                        AS company_state,
        COALESCE(ver.beas_postal_code, smb.company_postalcode)             AS company_postalcode,
        smb.tax_id,
        smb.annual_income,
        ROW_NUMBER() OVER (PARTITION BY smb.business_id ORDER BY RANDOM()) AS rn,
        mds.efx_id,
        mds.efx_match_confidence,
        mds.efx_name,
        mds.efx_legal_name,
        mds.efx_address,
        mds.efx_city,
        mds.efx_state,
        mds.efx_statec,
        mds.efx_zipcode,
        mds.efx_zip4,
        mds.efx_lat,
        mds.efx_lon,
        mds.efx_geoprec,
        mds.efx_region,
        mds.efx_ctryisocd,
        mds.efx_ctrynum,
        mds.efx_ctryname,
        mds.efx_countynm,
        mds.efx_county,
        mds.efx_cmsa,
        mds.efx_cmsadesc,
        mds.efx_soho,
        mds.efx_biz,
        mds.efx_res,
        mds.efx_cmra,
        mds.efx_congress,
        mds.efx_secadr,
        mds.efx_seccty,
        mds.efx_secstat,
        mds.efx_statec2,
        mds.efx_seczip,
        mds.efx_seczip4,
        mds.efx_seclat,
        mds.efx_seclon,
        mds.efx_secgeoprec,
        mds.efx_secregion,
        mds.efx_secctryisocd,
        mds.efx_secctrynum,
        mds.efx_secctryname,
        mds.efx_ctrytelcd,
        mds.efx_phone,
        mds.efx_faxphone,
        mds.efx_contct,
        mds.efx_titlecd,
        mds.efx_titledesc,
        mds.efx_lastnam,
        mds.efx_fstnam,
        mds.efx_email,
        mds.efx_ceoname,
        mds.efx_ceotitledesc,
        mds.efx_cioname,
        mds.efx_ciotitledesc,
        mds.efx_cfoname,
        mds.efx_cfotitledesc,
        mds.efx_gender,
        mds.efx_ethnicity,
        mds.efx_mbe,
        mds.efx_wbe,
        mds.efx_vet,
        mds.efx_bussize,
        mds.efx_gov,
        mds.efx_fgov,
        mds.efx_nonprofit,
        mds.efx_edu,
        mds.efx_busstat,
        mds.efx_busstatcd,
        mds.efx_web,
        mds.efx_yrest,
        mds.efx_corpempcnt,
        mds.efx_locempcnt,
        mds.efx_corpempcd,
        mds.efx_locempcd,
        mds.efx_corpamount,
        mds.efx_corpamountcd,
        mds.efx_corpamounttp,
        mds.efx_corpamountprec,
        mds.efx_locamount,
        mds.efx_locamountcd,
        mds.efx_locamounttp,
        mds.efx_locamountprec,
        mds.efx_public,
        mds.efx_stkexc,
        mds.efx_tcksym,
        mds.efx_primsic,
        mds.efx_secsic1,
        mds.efx_secsic2,
        mds.efx_secsic3,
        mds.efx_secsic4,
        mds.efx_primsicdesc,
        mds.efx_secsicdesc1,
        mds.efx_secsicdesc2,
        mds.efx_secsicdesc3,
        mds.efx_secsicdesc4,
        mds.efx_primnaicscode,
        mds.efx_secnaics1,
        mds.efx_secnaics2,
        mds.efx_secnaics3,
        mds.efx_secnaics4,
        mds.efx_primnaicsdesc,
        mds.efx_secnaicsdesc1,
        mds.efx_secnaicsdesc2,
        mds.efx_secnaicsdesc3,
        mds.efx_secnaicsdesc4,
        mds.efx_legsubnumall,
        mds.efx_legsubnameall,
        mds.efx_legsubaddressall,
        mds.efx_legsubcityall,
        mds.efx_legsubstateall,
        mds.efx_legsubzipcodeall,
        mds.efx_legsubzip4all,
        mds.efx_legsubcountyall,
        mds.efx_legsubctryisocdall,
        mds.efx_legsubctrynumall,
        mds.efx_legsubctrynameall,
        mds.efx_legdomultnumall,
        mds.efx_legdomultnameall,
        mds.efx_legdomultaddressall,
        mds.efx_legdomultcityall,
        mds.efx_legdomultstateall,
        mds.efx_legdomultzipcodeall,
        mds.efx_legdomultzip4all,
        mds.efx_legdomultcountyall,
        mds.efx_legdomultctryisocdall,
        mds.efx_legdomultctrynumall,
        mds.efx_legdomultctrynameall,
        mds.efx_legultnumall,
        mds.efx_legultnameall,
        mds.efx_legultaddressall,
        mds.efx_legultcityall,
        mds.efx_legultstateall,
        mds.efx_legultzipcodeall,
        mds.efx_legultzip4all,
        mds.efx_legultcountyall,
        mds.efx_legultctryisocdall,
        mds.efx_legultctrynumall,
        mds.efx_legultctrynameall,
        mds.efx_legultparentind,
        mds.efx_legparentind,
        mds.efx_leglinkedind,
        mds.efx_afflultnumall,
        mds.efx_afflultnameall,
        mds.efx_afflultaddressall,
        mds.efx_afflultcityall,
        mds.efx_afflultstateall,
        mds.efx_afflultzipcodeall,
        mds.efx_afflultzip4all,
        mds.efx_affultcountyall,
        mds.efx_afflultctryisocdall,
        mds.efx_afflultctrynumall,
        mds.efx_afflultctrynameall,
        mds.efx_affllinkedind,
        mds.efx_franchise,
        mds.efx_afflultparentind,
        mds.efx_afflparentind,
        mds.efx_foreign,
        mds.efx_failrate,
        mds.efx_faillevel,
        mds.efx_failreason1,
        mds.efx_failreason2,
        mds.efx_failreason3,
        mds.efx_failreason4,
        mds.efx_creditscore,
        mds.efx_creditclass,
        mds.efx_creditperc,
        mds.efx_creditreason1,
        mds.efx_creditreason2,
        mds.efx_creditreason3,
        mds.efx_creditreason4,
        mds.efx_bankruptcy,
        mds.efx_dead,
        mds.efx_deaddt,
        mds.efx_mrkt_telever,
        mds.efx_mrkt_telescore,
        mds.efx_mrkt_totalscore,
        mds.efx_mrkt_totalind,
        mds.efx_mrkt_vacant,
        mds.efx_mrkt_seasonal,
        mds.efx_extract_date,
        mds.efx_date_updated,
        mds.currentcty_4_avg,
        mds.currentst_4_avg,
        mds."12monthpriorcty_4_avg",
        mds."12monthpriorst_4_avg",
        mds.efx_merchant_id,
        mds.efx_project_id,
        mds.twelvemonthpriorcty_4_avg,
        mds.twelvemonthpriorst_4_avg,
        mds.efx_mwbe,
        mds.efx_sdb,
        mds.efx_hubzone,
        mds.efx_dbe,
        mds.efx_dvet,
        mds.efx_8a,
        mds.efx_8aexpdt,
        mds.efx_dis,
        mds.efx_sbe,
        mds.efx_hbcu,
        mds.efx_gaylesbian,
        mds.efx_wsbe,
        mds.efx_vsbe,
        mds.efx_dvsbe,
        mds.efx_mwbestatus,
        mds.efx_nmsdc,
        mds.efx_wbenc,
        mds.efx_ca_puc,
        mds.efx_tx_hub,
        mds.efx_tx_hubcertnum,
        mds.efx_gsax,
        mds.efx_caltrans,
        mds.efx_mi,
        mds.efx_anc,
        mds.efx_cert1,
        mds.efx_cert2,
        mds.efx_cert3,
        mds.efx_cert4,
        mds.efx_cert5,
        mds.efx_cert6,
        mds.efx_cert7,
        mds.efx_cert8,
        mds.efx_cert9,
        mds.efx_cert10,
        mds.efx_certdesc1,
        mds.efx_certdesc2,
        mds.efx_certdesc3,
        mds.efx_certdesc4,
        mds.efx_certdesc5,
        mds.efx_certdesc6,
        mds.efx_certdesc7,
        mds.efx_certdesc8,
        mds.efx_certdesc9,
        mds.efx_certdesc10,
        mds.efx_certsrc1,
        mds.efx_certsrc2,
        mds.efx_certsrc3,
        mds.efx_certsrc4,
        mds.efx_certsrc5,
        mds.efx_certsrc6,
        mds.efx_certsrc7,
        mds.efx_certsrc8,
        mds.efx_certsrc9,
        mds.efx_certsrc10,
        mds.efx_certlev1,
        mds.efx_certlev2,
        mds.efx_certlev3,
        mds.efx_certlev4,
        mds.efx_certlev5,
        mds.efx_certlev6,
        mds.efx_certlev7,
        mds.efx_certlev8,
        mds.efx_certlev9,
        mds.efx_certlev10,
        mds.efx_certnum1,
        mds.efx_certnum2,
        mds.efx_certnum3,
        mds.efx_certnum4,
        mds.efx_certnum5,
        mds.efx_certnum6,
        mds.efx_certnum7,
        mds.efx_certnum8,
        mds.efx_certnum9,
        mds.efx_certnum10,
        mds.efx_certexp1,
        mds.efx_certexp2,
        mds.efx_certexp3,
        mds.efx_certexp4,
        mds.efx_certexp5,
        mds.efx_certexp6,
        mds.efx_certexp7,
        mds.efx_certexp8,
        mds.efx_certexp9,
        mds.efx_certexp10,
        mds.efx_legentityparentnum,
        mds.efx_legentityparentname,
        mds.efx_legentitysubsidiaryind,
        mds.efx_legentityind,
        mds.efx_cancreditscorecds,
        mds.efx_cancreditrejcdcds,
        mds.efx_cancreditreason3cds,
        mds.efx_cancreditreason4cds,
        mds.efx_cancreditscorebfrs,
        mds.efx_cancreditrejcdbfrs,
        mds.efx_cancreditreason1bfrs,
        mds.efx_cancreditreason2bfrs,
        mds.efx_cancreditdate,
        mds.efx_affldomultnumall,
        mds.efx_affldomultnameall,
        mds.efx_affldomultaddressall,
        mds.efx_affldomultcityall,
        mds.efx_affldomultstateall,
        mds.efx_affldomultzipcodeall,
        mds.efx_affldomultzip4all,
        mds.efx_affldomultcountyall,
        mds.efx_affldomultctryisocdall,
        mds.efx_affldomultctrynumall,
        mds.efx_affldomultctrynameall,
        mds.efx_lbe,
        mds.efx_gov1057,
        mds.efx_merctype,
        -- mds.efxbma_1m_ind_2c_past_due_count,
        -- mds.efxbma_1m_ind_2pc_past_due_count,
        -- mds.efxbma_1m_ind_3c_past_due_count,
        -- mds.efxbma_1m_ind_3pc_past_due_count,
        -- mds.efxbma_1m_ind_4pc_past_due_count,
        -- mds.efxbma_1m_ind_tr_count,
        -- mds.efxbma_1m_ind_tr_total_bal,
        -- mds.efxbma_1m_ind_worst_payment_status,
        -- mds.efxbma_1m_nfin_1c_past_due_count,
        -- mds.efxbma_1m_nfin_1pc_past_due_count,
        -- mds.efxbma_1m_nfin_2c_past_due_count,
        -- mds.efxbma_1m_nfin_2pc_past_due_count,
        -- mds.efxbma_1m_nfin_3c_past_due_count,
        -- mds.efxbma_1m_nfin_3pc_past_due_count,
        -- mds.efxbma_1m_nfin_4pc_past_due_count,
        -- mds.efxbma_1m_nfin_chargeoff_tr_count,
        -- mds.efxbma_1m_nfin_closed_acc_count,
        -- mds.efxbma_1m_nfin_curr_credit_lim,
        -- mds.efxbma_1m_nfin_open_acc_count,
        -- mds.efxbma_1m_nfin_orig_credit_lim,
        -- mds.efxbma_1m_nfin_past_due_amount,
        -- mds.efxbma_1m_nfin_payment_index,
        -- mds.efxbma_1m_nfin_per_satisfactory_acc,
        -- mds.efxbma_1m_nfin_satisfactory_tr_count,
        -- mds.efxbma_1m_nfin_total_chargeoff_amt,
        -- mds.efxbma_1m_nfin_total_util,
        -- mds.efxbma_1m_nfin_tr_count,
        -- mds.efxbma_1m_nfin_tr_total_bal,
        -- mds.efxbma_1m_nfin_worst_payment_status,
        -- mds.efxbma_1m_serv_tr_count,
        -- mds.efxbma_1m_serv_tr_total_bal,
        -- mds.efxbma_1m_tel_1c_past_due_count,
        -- mds.efxbma_1m_tel_1pc_past_due_count,
        -- mds.efxbma_1m_tel_2c_past_due_count,
        -- mds.efxbma_1m_tel_2pc_past_due_count,
        -- mds.efxbma_1m_tel_3c_past_due_count,
        -- mds.efxbma_1m_tel_3pc_past_due_count,
        -- mds.efxbma_1m_tel_4pc_past_due_count,
        -- mds.efxbma_1m_tel_tr_count,
        -- mds.efxbma_1m_tel_tr_total_bal,
        -- mds.efxbma_1m_tel_worst_payment_status,
        -- mds.efxbma_1m_util_1c_past_due_count,
        -- mds.efxbma_1m_util_1pc_past_due_count,
        -- mds.efxbma_1m_util_2c_past_due_count,
        -- mds.efxbma_1m_util_2pc_past_due_count,
        -- mds.efxbma_1m_util_3c_past_due_count,
        -- mds.efxbma_1m_util_3pc_past_due_count,
        -- mds.efxbma_1m_util_4pc_past_due_count,
        -- mds.efxbma_1m_util_tr_count,
        -- mds.efxbma_1m_util_tr_total_bal,
        -- mds.efxbma_1m_util_worst_payment_status,
        -- mds.efxbma_3m_ind_1c_past_due_count,
        -- mds.efxbma_3m_ind_1pc_past_due_count,
        -- mds.efxbma_3m_ind_2c_past_due_count,
        -- mds.efxbma_3m_ind_2pc_past_due_count,
        -- mds.efxbma_3m_ind_3c_past_due_count,
        -- mds.efxbma_3m_ind_3pc_past_due_count,
        -- mds.efxbma_3m_ind_4pc_past_due_count,
        -- mds.efxbma_3m_ind_tr_count,
        -- mds.efxbma_3m_ind_tr_high_bal,
        -- mds.efxbma_3m_ind_tr_wb_count,
        -- mds.efxbma_3m_ind_worst_payment_status,
        -- mds.efxbma_3m_nfin_1c_past_due_amount,
        -- mds.efxbma_3m_nfin_1c_past_due_count,
        -- mds.efxbma_3m_nfin_1pc_past_due_count,
        -- mds.efxbma_3m_nfin_2c_past_due_amount,
        -- mds.efxbma_3m_nfin_2c_past_due_count,
        -- mds.efxbma_3m_nfin_2pc_past_due_count,
        -- mds.efxbma_3m_nfin_3c_past_due_amount,
        -- mds.efxbma_3m_nfin_3c_past_due_count,
        -- mds.efxbma_3m_nfin_3pc_past_due_count,
        -- mds.efxbma_3m_nfin_4pc_past_due_amount,
        -- mds.efxbma_3m_nfin_4pc_past_due_count,
        -- mds.efxbma_3m_nfin_chargeoff_tr_count,
        -- mds.efxbma_3m_nfin_high_credit_lim,
        -- mds.efxbma_3m_nfin_new_acc_count,
        -- mds.efxbma_3m_nfin_orig_credit_lim,
        -- mds.efxbma_3m_nfin_past_due_amount,
        -- mds.efxbma_3m_nfin_per_4pc_pd_to_totbal,
        -- mds.efxbma_3m_nfin_per_coff_to_tot_acc,
        -- mds.efxbma_3m_nfin_per_pd_to_totbal,
        -- mds.efxbma_3m_nfin_per_satisfactory_acc,
        -- mds.efxbma_3m_nfin_ratio_num_nondel_to_acc,
        -- mds.efxbma_3m_nfin_satisfactory_tr_count,
        -- mds.efxbma_3m_nfin_total_chargeoff_amt,
        -- mds.efxbma_3m_nfin_total_util,
        -- mds.efxbma_3m_nfin_tr_count,
        -- mds.efxbma_3m_nfin_tr_high_bal,
        -- mds.efxbma_3m_nfin_tr_wb_count,
        -- mds.efxbma_3m_nfin_worst_payment_status,
        -- mds.efxbma_3m_serv_past_due_amount,
        -- mds.efxbma_3m_serv_tr_count,
        -- mds.efxbma_3m_serv_tr_high_bal,
        -- mds.efxbma_3m_serv_tr_wb_count,
        -- mds.efxbma_3m_tel_1c_past_due_count,
        -- mds.efxbma_3m_tel_1pc_past_due_count,
        -- mds.efxbma_3m_tel_2c_past_due_count,
        -- mds.efxbma_3m_tel_2pc_past_due_count,
        -- mds.efxbma_3m_tel_3c_past_due_count,
        -- mds.efxbma_3m_tel_3pc_past_due_count,
        -- mds.efxbma_3m_tel_4pc_past_due_count,
        -- mds.efxbma_3m_tel_tr_count,
        -- mds.efxbma_3m_tel_tr_high_bal,
        -- mds.efxbma_3m_tel_tr_wb_count,
        -- mds.efxbma_3m_tel_worst_payment_status,
        -- mds.efxbma_3m_util_1c_past_due_count,
        -- mds.efxbma_3m_util_1pc_past_due_count,
        -- mds.efxbma_3m_util_2c_past_due_count,
        -- mds.efxbma_3m_util_2pc_past_due_count,
        -- mds.efxbma_3m_util_3c_past_due_count,
        -- mds.efxbma_3m_util_3pc_past_due_count,
        -- mds.efxbma_3m_util_4pc_past_due_count,
        -- mds.efxbma_3m_util_tr_count,
        -- mds.efxbma_3m_util_tr_high_bal,
        -- mds.efxbma_3m_util_tr_wb_count,
        -- mds.efxbma_3m_util_worst_payment_status,
        -- mds.efxbma_12m_ind_1c_past_due_count,
        -- mds.efxbma_12m_ind_1pc_past_due_count,
        -- mds.efxbma_12m_ind_2c_past_due_count,
        -- mds.efxbma_12m_ind_2pc_past_due_count,
        -- mds.efxbma_12m_ind_3c_past_due_count,
        -- mds.efxbma_12m_ind_3pc_past_due_count,
        -- mds.efxbma_12m_ind_4pc_past_due_count,
        -- mds.efxbma_12m_ind_tr_count,
        -- mds.efxbma_12m_ind_tr_high_bal,
        -- mds.efxbma_12m_ind_worst_payment_status,
        -- mds.efxbma_12m_nfin_1c_past_due_amount,
        -- mds.efxbma_12m_nfin_1c_past_due_count,
        -- mds.efxbma_12m_nfin_1pc_past_due_count,
        -- mds.efxbma_12m_nfin_2c_past_due_amount,
        -- mds.efxbma_12m_nfin_2c_past_due_count,
        -- mds.efxbma_12m_nfin_2pc_past_due_count,
        -- mds.efxbma_12m_nfin_3c_past_due_amount,
        -- mds.efxbma_12m_nfin_3c_past_due_count,
        -- mds.efxbma_12m_nfin_3pc_past_due_count,
        -- mds.efxbma_12m_nfin_4pc_past_due_amount,
        -- mds.efxbma_12m_nfin_4pc_past_due_count,
        -- mds.efxbma_12m_nfin_chargeoff_tr_count,
        -- mds.efxbma_12m_nfin_high_credit_lim,
        -- mds.efxbma_12m_nfin_orig_credit_lim,
        -- mds.efxbma_12m_nfin_past_due_amount,
        -- mds.efxbma_12m_nfin_per_4pc_pd_to_totbal,
        -- mds.efxbma_12m_nfin_per_coff_to_tot_acc,
        -- mds.efxbma_12m_nfin_per_pd_to_totbal,
        -- mds.efxbma_12m_nfin_per_satisfactory_acc,
        -- mds.efxbma_12m_nfin_satisfactory_tr_count,
        -- mds.efxbma_12m_nfin_total_chargeoff_amt,
        -- mds.efxbma_12m_nfin_total_util,
        -- mds.efxbma_12m_nfin_tr_count,
        -- mds.efxbma_12m_nfin_tr_high_bal,
        -- mds.efxbma_12m_nfin_worst_payment_status,
        -- mds.efxbma_12m_serv_tr_count,
        -- mds.efxbma_12m_serv_tr_high_bal,
        -- mds.efxbma_12m_tel_1c_past_due_count,
        -- mds.efxbma_12m_tel_1pc_past_due_count,
        -- mds.efxbma_12m_tel_2c_past_due_count,
        -- mds.efxbma_12m_tel_2pc_past_due_count,
        -- mds.efxbma_12m_tel_3c_past_due_count,
        -- mds.efxbma_12m_tel_3pc_past_due_count,
        -- mds.efxbma_12m_tel_4pc_past_due_count,
        -- mds.efxbma_12m_tel_tr_count,
        -- mds.efxbma_12m_tel_tr_high_bal,
        -- mds.efxbma_12m_tel_worst_payment_status,
        -- mds.efxbma_12m_util_1c_past_due_count,
        -- mds.efxbma_12m_util_1pc_past_due_count,
        -- mds.efxbma_12m_util_2c_past_due_count,
        -- mds.efxbma_12m_util_2pc_past_due_count,
        -- mds.efxbma_12m_util_3c_past_due_count,
        -- mds.efxbma_12m_util_3pc_past_due_count,
        -- mds.efxbma_12m_util_4pc_past_due_count,
        -- mds.efxbma_12m_util_tr_count,
        -- mds.efxbma_12m_util_tr_high_bal,
        -- mds.efxbma_12m_util_worst_payment_status,
        -- mds.efxbma_24m_ind_1c_past_due_count,
        -- mds.efxbma_24m_ind_1pc_past_due_count,
        -- mds.efxbma_24m_ind_2c_past_due_count,
        -- mds.efxbma_24m_ind_2pc_past_due_count,
        -- mds.efxbma_24m_ind_3c_past_due_count,
        -- mds.efxbma_24m_ind_3pc_past_due_count,
        -- mds.efxbma_24m_ind_4pc_past_due_count,
        -- mds.efxbma_24m_ind_tr_count,
        -- mds.efxbma_24m_ind_tr_high_bal,
        -- mds.efxbma_24m_ind_worst_payment_status,
        -- mds.efxbma_24m_nfin_1c_past_due_amount,
        -- mds.efxbma_24m_nfin_1c_past_due_count,
        -- mds.efxbma_24m_nfin_1pc_past_due_count,
        -- mds.efxbma_24m_nfin_2c_past_due_amount,
        -- mds.efxbma_24m_nfin_2c_past_due_count,
        -- mds.efxbma_24m_nfin_2pc_past_due_count,
        -- mds.efxbma_24m_nfin_3c_past_due_amount,
        -- mds.efxbma_24m_nfin_3c_past_due_count,
        -- mds.efxbma_24m_nfin_3pc_past_due_count,
        -- mds.efxbma_24m_nfin_4pc_past_due_amount,
        -- mds.efxbma_24m_nfin_4pc_past_due_count,
        -- mds.efxbma_24m_nfin_chargeoff_tr_count,
        -- mds.efxbma_24m_nfin_high_credit_lim,
        -- mds.efxbma_24m_nfin_orig_credit_lim,
        -- mds.efxbma_24m_nfin_past_due_amount,
        -- mds.efxbma_24m_nfin_per_4pc_pd_to_totbal,
        -- mds.efxbma_24m_nfin_per_coff_to_tot_acc,
        -- mds.efxbma_24m_nfin_per_pd_to_totbal,
        -- mds.efxbma_24m_nfin_per_satisfactory_acc,
        -- mds.efxbma_24m_nfin_satisfactory_tr_count,
        -- mds.efxbma_24m_nfin_total_chargeoff_amt,
        -- mds.efxbma_24m_nfin_total_util,
        -- mds.efxbma_24m_nfin_tr_count,
        -- mds.efxbma_24m_nfin_tr_high_bal,
        -- mds.efxbma_24m_nfin_worst_payment_status,
        -- mds.efxbma_24m_serv_tr_count,
        -- mds.efxbma_24m_serv_tr_high_bal,
        -- mds.efxbma_24m_tel_1c_past_due_count,
        -- mds.efxbma_24m_tel_1pc_past_due_count,
        -- mds.efxbma_24m_tel_2c_past_due_count,
        -- mds.efxbma_24m_tel_2pc_past_due_count,
        -- mds.efxbma_24m_tel_3c_past_due_count,
        -- mds.efxbma_24m_tel_3pc_past_due_count,
        -- mds.efxbma_24m_tel_4pc_past_due_count,
        -- mds.efxbma_24m_tel_tr_count,
        -- mds.efxbma_24m_tel_tr_high_bal,
        -- mds.efxbma_24m_tel_worst_payment_status,
        -- mds.efxbma_24m_util_1c_past_due_count,
        -- mds.efxbma_24m_util_1pc_past_due_count,
        -- mds.efxbma_24m_util_2c_past_due_count,
        -- mds.efxbma_24m_util_2pc_past_due_count,
        -- mds.efxbma_24m_util_3c_past_due_count,
        -- mds.efxbma_24m_util_3pc_past_due_count,
        -- mds.efxbma_24m_util_4pc_past_due_count,
        -- mds.efxbma_24m_util_tr_count,
        -- mds.efxbma_24m_util_tr_high_bal,
        -- mds.efxbma_24m_util_worst_payment_status,
        -- mds.efxbma_pubrec_age_bkp,
        -- mds.efxbma_pubrec_age_judg,
        -- mds.efxbma_pubrec_age_lien,
        -- mds.efxbma_pubrec_age_pr,
        -- mds.efxbma_pubrec_bkp_ind,
        -- mds.efxbma_pubrec_judg_ind,
        -- mds.efxbma_pubrec_lien_ind,
        -- mds.efxbma_pubrec_lien_judg_ind,
        -- mds.efxbma_pubrec_max_liab_rep_judg,
        -- mds.efxbma_pubrec_max_liab_rep_lien,
        -- mds.efxbma_pubrec_status_fi,
        -- mds.efxbma_pubrec_status_fi_ju,
        -- mds.efxbma_pubrec_status_ju,
        -- mds.efxbma_pubrec_sum_lien_all_judg,
        -- mds.efxbma_pubrec_total_cur_liab_judg,
        -- mds.efxbma_pubrec_total_cur_liab_judg_all,
        -- mds.efxbma_pubrec_total_cur_liab_lien,
        -- mds.efxbma_pubrec_total_cur_liab_lien_all,
        -- mds.efxbma_pubrec_total_cur_liab_lien_judg,
        -- mds.efxbma_pubrec_total_judg,
        -- mds.efxbma_pubrec_total_lien,
        -- mds.efxbma_pubrec_total_lien_judg,
        -- mds.efxbma_1m_ind_1c_past_due_count,
        -- mds.efxbma_1m_ind_1pc_past_due_count,
        -- mds.efxbma_extract_date,
        zcs.zi_c_location_id,
        zcs.zi_c_company_id,
        zcs.zi_c_is_hq,
        zcs.zi_es_ecid,
        zcs.zi_es_location_id,
        zcs.zi_c_tier_grade,
        zcs.zi_c_name,
        zcs.zi_c_name_display,
        zcs.zi_c_legal_entity_type,
        zcs.zi_c_url,
        zcs.zi_c_street,
        zcs.zi_c_street_2,
        zcs.zi_c_city,
        zcs.zi_c_state,
        zcs.zi_c_zip,
        zcs.zi_c_country,
        zcs.zi_c_cbsa_name,
        zcs.zi_c_county,
        zcs.zi_c_latitude,
        zcs.zi_c_longitude,
        zcs.zi_c_verified_address,
        zcs.zi_c_employee_range,
        zcs.zi_c_employees,
        zcs.zi_c_revenue_range,
        zcs.zi_c_revenue,
        zcs.zi_c_phone,
        zcs.zi_c_fax,
        zcs.zi_c_industry_primary,
        zcs.zi_c_sub_industry_primary,
        zcs.zi_c_industries,
        zcs.zi_c_sub_industries,
        zcs.zi_es_industry,
        zcs.zi_es_industries_top3,
        zcs.zi_c_naics2,
        zcs.zi_c_naics4,
        zcs.zi_c_naics6,
        zcs.zi_c_naics_top3,
        zcs.zi_c_sic2,
        zcs.zi_c_sic3,
        zcs.zi_c_sic4,
        zcs.zi_c_sic_top3,
        zcs.zi_c_estimated_age,
        zcs.zi_c_year_founded,
        zcs.zi_c_is_b2b,
        zcs.zi_c_is_b2c,
        zcs.zi_es_hq_ecid,
        zcs.zi_es_hq_location_id,
        zcs.zi_c_company_name,
        zcs.zi_c_company_url,
        zcs.zi_c_company_street,
        zcs.zi_c_company_street_2,
        zcs.zi_c_company_city,
        zcs.zi_c_company_state,
        zcs.zi_c_company_zip,
        zcs.zi_c_company_country,
        zcs.zi_c_company_cbsa_name,
        zcs.zi_c_company_county,
        zcs.zi_c_company_latitude,
        zcs.zi_c_company_longitude,
        zcs.zi_c_company_verified_address,
        zcs.zi_c_company_employee_range,
        zcs.zi_c_company_employees,
        zcs.zi_c_company_revenue_range,
        zcs.zi_c_company_revenue,
        zcs.zi_c_company_phone,
        zcs.zi_c_company_fax,
        zcs.zi_c_linkedin_url,
        zcs.zi_c_facebook_url,
        zcs.zi_c_twitter_url,
        zcs.zi_c_yelp_url,
        zcs.zi_c_domain_rank,
        zcs.zi_c_keywords,
        zcs.zi_c_top_keywords,
        zcs.zi_c_num_keywords,
        zcs.zi_c_employee_growth_1yr,
        zcs.zi_c_employee_growth_2yr,
        zcs.zi_es_growth,
        zcs.zi_es_employee_growth,
        zcs.zi_es_revenue_growth,
        zcs.zi_es_percent_employee_growth,
        zcs.zi_es_percent_revenue_growth,
        zcs.zi_c_name_confidence_score,
        zcs.zi_c_url_confidence_score,
        zcs.zi_c_address_confidence_score,
        zcs.zi_c_phone_confidence_score,
        zcs.zi_c_employees_confidence_score,
        zcs.zi_c_revenue_confidence_score,
        zcs.zi_es_industry_confidence_score,
        zcs.zi_c_naics_confidence_score,
        zcs.zi_c_sic_confidence_score,
        zcs.zi_es_industries_top3_confidence_scores,
        zcs.zi_c_naics_top3_confidence_scores,
        zcs.zi_c_sic_top3_confidence_scores,
        zcs.zi_c_ids_merged,
        zcs.zi_c_names_other,
        zcs.zi_c_url_status,
        zcs.zi_c_urls_alt,
        zcs.zi_c_url_last_updated,
        zcs.zi_c_inactive_flag,
        zcs.zi_c_ein,
        zcs.zi_c_is_small_business,
        zcs.zi_c_is_public,
        zcs.zi_c_ticker,
        zcs.zi_c_tickers_alt,
        zcs.zi_c_has_mobile_app,
        zcs.zi_c_currency_code,
        zcs.zi_c_num_locations,
        zcs.zi_c_hr_contacts,
        zcs.zi_c_sales_contacts,
        zcs.zi_c_marketing_contacts,
        zcs.zi_c_finance_contacts,
        zcs.zi_c_c_suite_contacts,
        zcs.zi_c_engineering_contacts,
        zcs.zi_c_it_contacts,
        zcs.zi_c_operations_contacts,
        zcs.zi_c_legal_contacts,
        zcs.zi_c_medical_contacts,
        zcs.zi_c_tech_ids,
        zcs.zi_c_latest_funding_age,
        zcs.zi_c_num_of_investors,
        zcs.zi_c_investor_names,
        zcs.zi_c_funding_strength,
        zcs.zi_c_funding_type,
        zcs.zi_c_total_funding_amount,
        zcs.zi_c_latest_funding_amount,
        zcs.zi_c_latest_funding_date,
        zcs.zi_c_num_funding_rounds,
        zcs.zi_c_is_fortune_100,
        zcs.zi_c_is_fortune_500,
        zcs.zi_c_is_s_and_p_500,
        zcs.zi_c_last_updated_date,
        zcs.zi_c_release_date,
        oc.oc_match_confidence,
        ocs.company_number,
        ocs.jurisdiction_code,
        ocs.name,
        ocs.normalised_name,
        ocs.company_type,
        ocs.nonprofit,
        ocs.current_status,
        ocs.incorporation_date,
        ocs.dissolution_date,
        ocs.branch,
        ocs.business_number,
        ocs.current_alternative_legal_name,
        ocs.current_alternative_legal_name_language,
        ocs.home_jurisdiction_text,
        ocs.native_company_number,
        ocs.previous_names,
        ocs.retrieved_at,
        ocs.registry_url,
        ocs.restricted_for_marketing,
        ocs.inactive,
        ocs.accounts_next_due,
        ocs.accounts_reference_date,
        ocs.accounts_last_made_up_date,
        ocs.annual_return_next_due,
        ocs.annual_return_last_made_up_date,
        ocs.has_been_liquidated,
        ocs.has_insolvency_history,
        ocs.has_charges,
        ocs.number_of_employees,
        ocs."registered_address.street_address",
        ocs."registered_address.locality",
        ocs."registered_address.region",
        ocs."registered_address.postal_code",
        ocs."registered_address.country",
        ocs."registered_address.in_full",
        ocs.home_jurisdiction_code,
        ocs.home_jurisdiction_company_number,
        ocs.industry_code_uids,
        ocs.latest_accounts_date,
        ocs.latest_accounts_cash,
        ocs.latest_accounts_assets,
        ocs.latest_accounts_liabilities,
        oco.officer_1_name,
        oco.officer_1_title,
        oco.officer_2_name,
        oco.officer_2_title,
        pr.vid,
        pr.max_rating_past_6_months,
        pr.min_rating_all_time,
        pr.count_of_merchant_pending_partnership_tradelines_past_6_mo,
        pr.count_of_complaints_containing_alert_words_past_3_months,
        pr.count_of_delinquent_closed_merchant_partnerships_past_12_m,
        pr.count_of_address_line_1_past_24_months,
        pr.days_since_earliest_complaint_past_12_months,
        pr.count_non_delinquent_closures_past_12_months,
        pr.percent_of_other_resolved_status_all_time,
        pr.count_of_suspended_partner_merchant_partnerships_past_6_mo,
        pr.corporate_filing_filing_date_all_time,
        pr.percent_of_complaints_containing_alert_words_past_3_months,
        pr.count_of_reviews_source_a_past_1_months,
        pr.percent_of_reviews_source_a_past_3_months,
        pr.days_between_earliest_and_latest_complaint_past_6_months,
        pr.total_amount_of_liens_10_most_recent_all_time,
        pr.number_of_personal_chapter_7_bankruptcies_all_time,
        pr.state_of_the_professional_license_all_time,
        pr.count_of_zip5_past_24_months,
        pr.percent_of_reviews_source_b_past_3_months,
        pr.count_of_all_reviews_past_6_months,
        pr.count_of_merchant_open_partnership_tradelines_past_12_mont,
        pr.count_of_answered_resolved_status_past_6_months,
        pr.closed_merchant_partnership_tradeline_hit_flag_past_1_mont,
        pr.count_non_delinquent_closures_all_time,
        pr.count_of_reviews_source_j_past_3_months,
        pr.count_of_unique_reviewers_past_6_months,
        pr.merchant_partnership_tradelines_with_at_least_a_2__all_tim,
        pr.count_of_unanswered_resolved_status_past_12_months,
        pr.count_of_reviews_source_b_past_3_months,
        pr.count_of_closed_partner_merchant_partnerships_past_12_mont,
        pr.most_recent_judgement_amount_all_time,
        pr.days_since_last_seen_past_24_months,
        pr.count_of_merchant_inactive_partnership_tradelines_all_time,
        pr.year_principal_died_all_time,
        pr.percent_of_reviews_source_j_past_3_months,
        pr.count_of_complaint_containing_alert_words_all_time,
        pr.count_of_merchant_partnership_tradelines_in_good_s_past_3,
        pr.count_of_complaints_past_1_months,
        pr.percent_of_answered_resolved_status_past_12_months,
        pr.count_of_duplicate_reviewers_all_time,
        pr.percent_of_answered_resolved_status_all_time,
        pr.kyb_address_hit_flag_past_6_months,
        pr.percent_60_quintile_of_rating_all_time,
        pr.count_of_source_a_unable_to_locate_business_resolv_past_6,
        pr.kyb_address_hit_flag_all_time,
        pr.count_of_reviews_source_e_past_6_months,
        pr.count_of_total_reviewers_all_time,
        pr.percent_of_other_resolved_status_past_12_months,
        pr.employers_last_seen_date_all_time,
        pr.percent_of_0_or_1_star_ratings_all_time,
        pr.days_between_earliest_and_latest_close_date_for_me_past_6,
        pr.percent_of_reviews_source_g_past_1_months,
        pr.days_since_latest_complaint_past_6_months,
        pr.count_of_duplicate_reviewers_past_3_months,
        pr.median_rating_past_1_months,
        pr.count_of_merchant_closures_in_first_2_months_all_time,
        pr.number_of_relatives_on_watch_list_all_time,
        pr.number_of_known_relatives_all_time,
        pr.count_of_complaints_containing_alert_words_past_12_months,
        pr.most_recent_bankruptcy_filing_date_all_time,
        pr.days_between_first_seen_and_last_seen_past_24_months,
        pr.count_of_merchant_inactive_partnership_tradelines_past_1_m,
        pr.days_since_latest_complaint_past_1_months,
        pr.count_of_merchant_closures_in_first_3_months_all_time,
        pr.count_of_all_reviews_past_3_months,
        pr.number_of_watch_lists_principal_appears_on_all_time,
        pr.count_of_reviews_source_g_past_1_months,
        pr.count_of_closed_out_of_business_partner_merchant_p_past_1,
        pr.days_between_earliest_and_latest_update_past_24_months,
        pr.count_of_0_or_1_star_ratings_past_6_months,
        pr.count_of_unique_zip5_past_24_months,
        pr.count_of_states_past_6_months,
        pr.percent_60_quintile_of_rating_past_6_months,
        pr.merchant_partnership_tradeline_hit_flag_past_3_months,
        pr.count_of_source_a_unable_to_locate_business_resolv_all_tim,
        pr.count_of_merchant_closures_in_first_12_months_all_time,
        pr.days_since_latest_merchant_partnership_tradeline_o_past_12,
        pr.most_recent_judgement_filing_date_all_time,
        pr.days_between_earliest_and_latest_update_all_time,
        pr.days_between_earliest_and_latest_merchant_partners_past_6,
        pr.percent_of_2_star_ratings_all_time,
        pr.public_data_hit_flag_past_6_months,
        pr.days_since_latest_close_date_for_merchant_partners_past_12,
        pr.count_of_reviews_source_e_past_1_months,
        pr.count_of_declined_partner_merchant_partnerships_all_time,
        pr.corporate_filing_registration_type_all_time,
        pr.days_since_latest_update_past_24_months,
        pr.days_since_first_seen_past_12_months,
        pr.percent_of_3_star_ratings_past_6_months,
        pr.closed_merchant_partnership_tradeline_hit_flag_all_time,
        pr.count_of_closed_performance_partner_merchant_partn_past_6,
        pr.count_of_merchant_partnerships_in_bad_standing_past_6_mont,
        pr.count_of_complaint_containing_alert_words_past_1_months,
        pr.days_since_last_seen_past_6_months,
        pr.count_of_cities_past_6_months,
        pr.count_of_zip5_all_time,
        pr.count_non_delinquent_closures_past_3_months,
        pr.percent_of_other_resolved_status_past_1_months,
        pr.count_of_source_a_unable_to_locate_business_resolv_past_1,
        pr.is_business_on_a_watch_list_all_time,
        pr.is_deceased_all_time,
        pr.count_of_merchant_open_partnership_tradelines_past_1_month,
        pr.percent_of_2_star_ratings_past_1_months,
        pr.days_between_earliest_and_latest_complaint_past_3_months,
        pr.percent_of_answered_resolved_status_past_3_months,
        pr.number_of_judgement_filings_all_time,
        pr.days_since_latest_update_all_time,
        pr.most_recent_ucc_filing_expiration_date_all_time,
        pr.percent_of_reviews_source_j_past_1_months,
        pr.bankruptcy_status_date_all_time,
        pr.percent_of_reviews_source_e_past_1_months,
        pr.count_of_merchant_closures_in_first_1_month_all_time,
        pr.days_between_earliest_and_latest_complaint_past_1_months,
        pr.count_of_2_star_ratings_past_1_months,
        pr.days_since_earliest_update_past_12_months,
        pr.count_of_decline_status_merchant_partnerships_past_3_month,
        pr.percent_of_resolved_resolved_status_past_1_months,
        pr.days_since_earliest_merchant_partnership_tradeline_all_tim,
        pr.count_of_probation_partner_merchant_partnerships_past_3_mo,
        pr.percent_of_reviews_source_i_past_6_months,
        pr.count_of_reviews_source_a_past_3_months,
        pr.most_recent_business_lien_filing_date_all_time,
        pr.max_rating_past_1_months,
        pr.count_of_unique_reviewers_all_time,
        pr.days_since_earliest_review_all_time,
        pr.count_of_other_resolved_status_past_3_months,
        pr.count_of_unique_cities_past_24_months,
        pr.percent_80_quintile_of_rating_past_6_months,
        pr.closed_merchant_partnership_tradeline_hit_flag_past_12_mon,
        pr.count_of_unique_lenders_for_merchant_level_partner_past_6,
        pr.percent_of_reviews_containing_alert_words_all_time,
        pr.count_of_total_reviewers_past_3_months,
        pr.percent_of_resolved_resolved_status_all_time,
        pr.count_of_addresses_all_time,
        pr.days_since_earliest_update_all_time,
        pr.percent_of_reviews_containing_alert_words_past_6_months,
        pr.percent_of_reviews_source_h_past_6_months,
        pr.count_of_reviews_source_h_past_6_months,
        pr.count_of_unique_cities_past_6_months,
        pr.count_of_closed_fraud_partner_merchant_partnership_past_3,
        pr.days_since_latest_update_past_12_months,
        pr.days_between_earliest_and_latest_close_date_for_me_past_12,
        pr.count_of_closed_other_partner_merchant_partnership_past_6,
        pr.most_recent_report_date_of_judgement_filing_all_time,
        pr.percent_of_reviews_source_e_past_6_months,
        pr.count_of_other_resolved_status_all_time,
        pr.count_of_unique_cities_all_time,
        pr.percent_of_unresolved_resolved_status_all_time,
        pr.count_of_complaints_containing_alert_words_all_time,
        pr.count_of_unique_address_line_1_past_12_months,
        pr.count_of_closed_fraud_partner_merchant_partnership_past_6,
        pr.days_since_latest_merchant_partnership_tradeline_o_past_1,
        pr.count_of_unresolved_resolved_status_past_1_months,
        pr.count_of_probation_partner_merchant_partnerships_past_6_mo,
        pr.count_of_0_or_1_star_ratings_all_time,
        pr.percent_of_5_star_ratings_past_3_months,
        pr.employers_business_name_all_time,
        pr.median_rating_past_6_months,
        pr.percent_of_resolved_resolved_status_past_6_months,
        pr.days_since_latest_merchant_partnership_tradeline_o_past_6,
        pr.count_of_reviews_containing_alert_words_past_3_months,
        pr.count_of_address_line_1_past_6_months,
        pr.count_of_reviews_source_i_past_1_months,
        pr.most_recent_judgement_status_all_time,
        pr.percent_of_0_or_1_star_ratings_past_3_months,
        pr.count_of_zip5_past_12_months,
        pr.count_of_merchant_pending_partnership_tradelines_past_12_m,
        pr.count_of_reviews_containing_alert_words_past_6_months,
        pr.kyb_address_hit_flag_past_24_months,
        pr.number_of_known_associates_all_time,
        pr.count_of_0_or_1_star_ratings_past_3_months,
        pr.days_since_latest_review_past_3_months,
        pr.days_since_last_seen_past_12_months,
        pr.count_of_3_star_ratings_past_1_months,
        pr.days_since_earliest_update_past_24_months,
        pr.percent_of_reviews_source_a_past_1_months,
        pr.count_of_2_star_ratings_past_6_months,
        pr.percent_of_answered_resolved_status_past_6_months,
        pr.percent_of_reviews_containing_alert_words_past_1_months,
        pr.percent_of_reviews_source_i_all_time,
        pr.percent_of_unanswered_resolved_status_past_6_months,
        pr.standard_deviation_of_rating_past_6_months,
        pr.percent_of_5_star_ratings_past_6_months,
        pr.count_of_total_reviewers_past_6_months,
        pr.percent_of_reviews_source_i_past_3_months,
        pr.days_since_latest_close_date_for_merchant_partners_past_1,
        pr.percent_of_resolved_resolved_status_past_12_months,
        pr.variance_of_rating_past_3_months,
        pr.count_of_answered_resolved_status_all_time,
        pr.count_of_4_star_ratings_past_1_months,
        pr.days_since_latest_merchant_partnership_tradeline_o_past_3,
        pr.percent_of_reviews_source_h_all_time,
        pr.count_of_cities_past_24_months,
        pr.count_of_complaints_past_12_months,
        pr.percent_of_unanswered_resolved_status_past_3_months,
        pr.days_since_latest_update_past_6_months,
        pr.count_of_merchant_partnerships_in_bad_standing_past_3_mont,
        pr.median_rating_past_3_months,
        pr.days_since_earliest_close_date_for_merchant_partne_past_6,
        pr.count_of_resolved_resolved_status_past_12_months,
        pr.percent_of_complaints_containing_alert_words_past_6_months,
        pr.variance_of_rating_past_1_months,
        pr.days_since_latest_merchant_partnership_tradeline_o_all_tim,
        pr.days_between_earliest_and_latest_complaint_all_time,
        pr.count_of_source_a_unable_to_locate_business_resolv_past_3,
        pr.count_of_3_star_ratings_past_3_months,
        pr.corporate_filing_incorporation_state_all_time,
        pr.percent_of_reviews_source_a_past_6_months,
        pr.count_of_merchant_partnership_tradelines_in_good_s_past_12,
        pr.count_of_reviews_source_g_all_time,
        pr.percent_of_4_star_ratings_all_time,
        pr.percent_of_3_star_ratings_past_1_months,
        pr.days_since_earliest_complaint_past_1_months,
        pr.count_of_delinquent_closed_merchant_partnerships_all_time,
        pr.kyb_address_hit_flag_past_12_months,
        pr.percent_of_0_or_1_star_ratings_past_1_months,
        pr.count_of_total_reviewers_past_1_months,
        pr.percent_of_source_a_unable_to_locate_business_resolved_s_past_1,
        pr.percent_of_reviews_source_g_all_time,
        pr.count_of_2_star_ratings_all_time,
        pr.count_of_reviews_source_h_all_time,
        pr.count_of_closed_out_of_business_partner_merchant_p_past_6,
        pr.count_of_merchant_pending_partnership_tradelines_all_time,
        pr.count_of_unique_lenders_for_merchant_level_partner_past_12,
        pr.percent_of_reviews_source_i_past_1_months,
        pr.count_of_complaints_containing_alert_words_past_6_months,
        pr.corporate_filing_business_name_all_time,
        pr.days_between_earliest_and_latest_review_past_3_months,
        pr.count_of_closed_performance_partner_merchant_partn_past_3,
        pr.count_of_merchant_partnership_tradelines_in_good_s_all_tim,
        pr.most_recent_business_lien_status_date_all_time,
        pr.days_since_earliest_close_date_for_merchant_partne_past_12,
        pr.percent_40_quintile_of_rating_past_1_months,
        pr.public_data_hit_flag_all_time,
        pr.count_of_decline_status_merchant_partnerships_past_6_month,
        pr.number_of_personal_chapter_13_bankruptcies_all_time,
        pr.percent_of_3_star_ratings_all_time,
        pr.count_of_reviews_source_e_all_time,
        pr.days_since_earliest_merchant_partnership_tradeline_past_3,
        pr.count_of_unique_lenders_for_merchant_level_partner_all_tim,
        pr.percent_40_quintile_of_rating_past_6_months,
        pr.count_of_closed_compliance_partner_merchant_partne_all_tim,
        pr.complaint_data_source_a_hit_flag_all_time,
        pr.percent_of_reviews_source_h_past_1_months,
        pr.count_of_merchant_unknown_partnership_tradelines_past_6_mo,
        pr.count_of_unresolved_resolved_status_past_12_months,
        pr.count_of_unique_reviewers_past_1_months,
        pr.count_of_closed_partner_merchant_partnerships_all_time,
        pr.number_of_bankruptices_all_time,
        pr.percent_of_other_resolved_status_past_3_months,
        pr.count_of_complaints_past_3_months,
        pr.count_of_unanswered_resolved_status_past_3_months,
        pr.count_of_merchant_unknown_partnership_tradelines_all_time,
        pr.count_of_unique_reviewers_past_3_months,
        pr.most_recent_ucc_filing_date_all_time,
        pr.count_of_merchant_open_partnership_tradelines_past_3_month,
        pr.days_since_earliest_close_date_for_merchant_partne_all_tim,
        pr.complaint_data_source_a_hit_flag_past_6_months,
        pr.min_rating_past_6_months,
        pr.percent_20_quintile_of_rating_past_3_months,
        pr.percent_of_unresolved_resolved_status_past_1_months,
        pr.days_between_first_seen_and_last_seen_past_6_months,
        pr.count_of_closed_underwriting_partner_merchant_part_past_6,
        pr.count_of_closed_out_of_business_partner_merchant_p_past_3,
        pr.count_of_answered_resolved_status_past_3_months,
        pr.count_of_merchant_partnership_tradelines_in_good_s_past_1,
        pr.percent_80_quintile_of_rating_past_1_months,
        pr.count_of_reviews_source_i_all_time,
        pr.count_of_states_all_time,
        pr.license_type_on_the_professional_license_all_time,
        pr.count_of_closed_performance_partner_merchant_partn_past_1,
        pr.count_of_unique_lenders_for_merchant_level_partner_past_1,
        pr.percent_of_reviews_source_e_all_time,
        pr.count_of_suspended_partner_merchant_partnerships_past_1_mo,
        pr.count_of_reviews_source_j_past_1_months,
        pr.number_of_watch_lists_business_appears_on_all_time,
        pr.days_between_first_seen_and_last_seen_past_12_months,
        pr.average_rating_past_3_months,
        pr.count_of_closed_performance_partner_merchant_partn_all_tim,
        pr.count_of_closed_compliance_partner_merchant_partne_past_6,
        pr.count_of_reviews_source_h_past_1_months,
        pr.count_of_closed_underwriting_partner_merchant_part_past_1,
        pr.days_between_earliest_and_latest_merchant_partners_past_12,
        pr.count_of_resolved_resolved_status_all_time,
        pr.count_of_decline_status_merchant_partnerships_past_12_mont,
        pr.count_of_addresses_past_24_months,
        pr.standard_deviation_of_rating_past_3_months,
        pr.count_of_merchant_closures_in_first_6_months_all_time,
        pr.count_of_merchant_partnership_tradelines_in_good_s_past_6,
        pr.max_rating_all_time,
        pr.percent_of_reviews_source_g_past_6_months,
        pr.most_recent_bankruptcy_discharge_closure_date_all_time,
        pr.percent_of_reviews_containing_alert_words_past_3_months,
        pr.percent_of_4_star_ratings_past_3_months,
        pr.days_since_latest_close_date_for_merchant_partners_past_6,
        pr.count_of_answered_resolved_status_past_1_months,
        pr.count_of_closed_performance_partner_merchant_partn_past_12,
        pr.merchant_partnership_tradeline_hit_flag_past_6_months,
        pr.count_of_merchant_partnerships_in_bad_standing_past_12_mon,
        pr.public_data_hit_flag_past_3_months,
        pr.most_recent_bankruptcy_status_all_time,
        pr.standard_deviation_of_rating_past_1_months,
        pr.perc_of_source_a_unable_to_locate_business_resolved_past_12,
        pr.count_non_delinquent_closures_past_1_months,
        pr.count_of_unresolved_resolved_status_all_time,
        pr.percent_of_reviews_source_a_all_time,
        pr.days_between_earliest_and_latest_review_past_6_months,
        pr.days_since_earliest_merchant_partnership_tradeline_past_12,
        pr.count_of_reviews_source_b_past_1_months,
        pr.count_of_unique_states_past_24_months,
        pr.days_between_earliest_and_latest_update_past_6_months,
        pr.count_of_merchant_pending_partnership_tradelines_past_1_mo,
        pr.count_of_complaints_containing_alert_words_past_1_months,
        pr.corporate_filing_corporation_type_all_time,
        pr.min_rating_past_3_months,
        pr.count_of_other_resolved_status_past_1_months,
        pr.count_of_merchant_inactive_partnership_tradelines_past_12,
        pr.is_principal_on_a_watch_list_all_time,
        pr.days_between_earliest_and_latest_close_date_for_me_past_1,
        pr.days_since_earliest_complaint_all_time,
        pr.count_of_suspended_partner_merchant_partnerships_past_12_m,
        pr.count_of_unique_states_past_12_months,
        pr.percent_of_5_star_ratings_all_time,
        pr.days_between_earliest_and_latest_close_date_for_me_past_3,
        pr.count_of_merchant_unknown_partnership_tradelines_past_12_m,
        pr.count_of_answered_resolved_status_past_12_months,
        pr.percent_of_reviews_source_b_past_6_months,
        pr.days_since_first_seen_past_6_months,
        pr.count_of_5_star_ratings_past_3_months,
        pr.count_of_complaint_containing_alert_words_past_3_months,
        pr.count_of_unique_states_all_time,
        pr.count_of_cities_past_12_months,
        pr.count_of_merchant_pending_partnership_tradelines_past_3_mo,
        pr.percent_of_reviews_source_b_all_time,
        pr.count_of_unique_address_line_1_past_6_months,
        pr.merchant_partnership_tradeline_hit_flag_all_time,
        pr.percent_40_quintile_of_rating_past_3_months,
        pr.count_of_resolved_resolved_status_past_1_months,
        pr.max_rating_past_3_months,
        pr.count_of_unique_states_past_6_months,
        pr.percent_of_2_star_ratings_past_3_months,
        pr.percent_of_unresolved_resolved_status_past_6_months,
        pr.was_most_recent_bankruptcy_voluntary_all_time,
        pr.days_since_last_seen_all_time,
        pr.count_of_probation_partner_merchant_partnerships_past_12_m,
        pr.days_between_earliest_and_latest_update_past_12_months,
        pr.days_since_latest_close_date_for_merchant_partners_all_tim,
        pr.count_of_unanswered_resolved_status_past_6_months,
        pr.percent_of_unanswered_resolved_status_past_12_months,
        pr.most_recent_business_lien_status_all_time,
        pr.count_of_duplicate_reviewers_past_1_months,
        pr.count_of_zip5_past_6_months,
        pr.percent_of_unresolved_resolved_status_past_12_months,
        pr.days_since_latest_review_past_1_months,
        pr.most_recent_ucc_filing_type_all_time,
        pr.count_of_unresolved_resolved_status_past_3_months,
        pr.count_of_closed_partner_merchant_partnerships_past_3_month,
        pr.count_of_complaint_containing_alert_words_past_12_months,
        pr.days_since_earliest_close_date_for_merchant_partne_past_3,
        pr.days_since_earliest_complaint_past_3_months,
        pr.count_of_closed_compliance_partner_merchant_partne_past_12,
        pr.percent_of_answered_resolved_status_past_1_months,
        pr.average_rating_all_time,
        pr.count_of_states_past_12_months,
        pr.count_of_unique_address_line_1_past_24_months,
        pr.count_of_4_star_ratings_past_6_months,
        pr.complaint_data_source_a_hit_flag_past_3_months,
        pr.min_rating_past_1_months,
        pr.count_of_closed_other_partner_merchant_partnership_past_3,
        pr.count_of_closed_underwriting_partner_merchant_part_past_3,
        pr.count_of_declined_partner_merchant_partnerships_past_12_mo,
        pr.count_of_declined_partner_merchant_partnerships_past_1_mon,
        pr.percent_of_complaints_containing_alert_words_past_1_months,
        pr.count_of_decline_status_merchant_partnerships_past_1_month,
        pr.days_since_earliest_close_date_for_merchant_partne_past_1,
        pr.count_of_closed_fraud_partner_merchant_partnership_all_tim,
        pr.count_non_delinquent_closures_past_6_months,
        pr.date_deceased_information_reported_to_verdata_all_time,
        pr.complaint_data_source_a_hit_flag_past_1_months,
        pr.days_since_earliest_review_past_3_months,
        pr.count_of_resolved_resolved_status_past_6_months,
        pr.count_of_closed_fraud_partner_merchant_partnership_past_1,
        pr.count_of_declined_partner_merchant_partnerships_past_6_mon,
        pr.percent_of_2_star_ratings_past_6_months,
        pr.count_of_4_star_ratings_all_time,
        pr.count_of_2_star_ratings_past_3_months,
        pr.merchant_partnership_tradelines_with_at_least_a_1__all_tim,
        pr.percent_of_reviews_source_j_all_time,
        pr.count_of_merchant_open_partnership_tradelines_all_time,
        pr.merchant_partnership_tradeline_hit_flag_past_1_months,
        pr.count_of_cities_all_time,
        pr.count_of_reviews_source_a_past_6_months,
        pr.percent_of_0_or_1_star_ratings_past_6_months,
        pr.count_of_reviews_source_g_past_6_months,
        pr.days_since_latest_review_past_6_months,
        pr.percent_80_quintile_of_rating_past_3_months,
        pr.individual_bankruptcy_filing_date_all_time,
        pr.days_between_earliest_and_latest_review_past_1_months,
        pr.percent_of_4_star_ratings_past_6_months,
        pr.count_of_address_line_1_all_time,
        pr.most_recent_judgement_status_date_all_time,
        pr.count_of_reviews_source_b_all_time,
        pr.closed_merchant_partnership_tradeline_hit_flag_past_3_mont,
        pr.count_of_delinquent_closed_merchant_partnerships_past_1_mo,
        pr.count_of_merchant_unknown_partnership_tradelines_past_3_mo,
        pr.count_of_address_line_1_past_12_months,
        pr.days_between_earliest_and_latest_merchant_partners_past_1,
        pr.days_between_earliest_and_latest_close_date_for_me_all_tim,
        pr.days_between_earliest_and_latest_merchant_partners_past_3,
        pr.count_of_decline_status_merchant_partnerships_all_time,
        pr.public_data_hit_flag_past_1_months,
        pr.percent_of_unanswered_resolved_status_past_1_months,
        pr.count_of_unique_zip5_past_6_months,
        pr.count_of_all_reviews_all_time,
        pr.count_of_closed_partner_merchant_partnerships_past_1_month,
        pr.count_of_reviews_source_j_past_6_months,
        pr.count_of_reviews_source_h_past_3_months,
        pr.complaint_data_source_a_hit_flag_past_12_months,
        pr.count_of_other_resolved_status_past_12_months,
        pr.percent_of_3_star_ratings_past_3_months,
        pr.count_of_closed_partner_merchant_partnerships_past_6_month,
        pr.count_of_unanswered_resolved_status_all_time,
        pr.average_rating_past_6_months,
        pr.count_of_complaint_containing_alert_words_past_6_months,
        pr.variance_of_rating_past_6_months,
        pr.count_of_merchant_inactive_partnership_tradelines_past_6_m,
        pr.count_of_unique_lenders_for_merchant_level_partner_past_3,
        pr.variance_of_rating_all_time,
        pr.count_of_reviews_source_g_past_3_months,
        pr.count_of_closed_other_partner_merchant_partnership_past_1,
        pr.count_of_reviews_source_a_all_time,
        pr.count_of_complaints_past_6_months,
        pr.count_of_reviews_source_j_all_time,
        pr.count_of_addresses_past_6_months,
        pr.count_of_3_star_ratings_past_6_months,
        pr.median_rating_all_time,
        pr.days_since_earliest_review_past_6_months,
        pr.count_of_reviews_source_i_past_3_months,
        pr.days_since_earliest_merchant_partnership_tradeline_past_1,
        pr.count_of_0_or_1_star_ratings_past_1_months,
        pr.standard_deviation_of_rating_all_time,
        pr.count_of_probation_partner_merchant_partnerships_all_time,
        pr.count_of_closed_compliance_partner_merchant_partne_past_3,
        pr.days_since_earliest_complaint_past_6_months,
        pr.count_of_merchant_partnerships_in_bad_standing_past_1_mont,
        pr.count_of_merchant_open_partnership_tradelines_past_6_month,
        pr.days_between_first_seen_and_last_seen_all_time,
        pr.percent_60_quintile_of_rating_past_1_months,
        pr.percent_20_quintile_of_rating_past_1_months,
        pr.days_since_latest_review_all_time,
        pr.number_of_business_liens_all_time,
        pr.count_of_merchant_closures_in_first_18_months_all_time,
        pr.count_of_unique_zip5_all_time,
        pr.count_of_other_resolved_status_past_6_months,
        pr.percent_of_reviews_source_g_past_3_months,
        pr.count_of_closed_fraud_partner_merchant_partnership_past_12,
        pr.count_of_suspended_partner_merchant_partnerships_all_time,
        pr.count_of_reviews_containing_alert_words_all_time,
        pr.total_amount_of_judgements_10_most_recent_all_time,
        pr.count_of_declined_partner_merchant_partnerships_past_3_mon,
        pr.total_voluntary_bankruptcies_all_time,
        pr.count_of_5_star_ratings_past_1_months,
        pr.days_between_earliest_and_latest_merchant_partners_all_tim,
        pr.count_of_states_past_24_months,
        pr.days_since_earliest_merchant_partnership_tradeline_past_6,
        pr.count_of_5_star_ratings_all_time,
        pr.count_of_unique_zip5_past_12_months,
        pr.most_recent_report_date_of_lien_filing_all_time,
        pr.total_number_of_judgements_that_the_individual_has_all_tim,
        pr.count_of_unanswered_resolved_status_past_1_months,
        pr.count_of_reviews_source_b_past_6_months,
        pr.count_of_unresolved_resolved_status_past_6_months,
        pr.days_since_earliest_update_past_6_months,
        pr.percent_of_other_resolved_status_past_6_months,
        pr.days_since_first_seen_all_time,
        pr.percent_of_source_a_unable_to_locate_business_resolved_s_past_3,
        pr.count_of_closed_other_partner_merchant_partnership_all_tim,
        pr.count_of_closed_other_partner_merchant_partnership_past_12,
        pr.count_of_closed_compliance_partner_merchant_partne_past_1,
        pr.count_of_merchant_partnerships_in_bad_standing_all_time,
        pr.merchant_partnership_tradelines_with_at_least_a_3__all_tim,
        pr.percent_20_quintile_of_rating_all_time,
        pr.count_of_merchant_inactive_partnership_tradelines_past_3_m,
        pr.days_since_latest_complaint_past_3_months,
        pr.count_of_4_star_ratings_past_3_months,
        pr.number_of_liens_the_individual_has_had_against_the_all_tim,
        pr.count_of_5_star_ratings_past_6_months,
        pr.number_of_associates_on_watch_list_all_time,
        pr.percent_of_reviews_source_j_past_6_months,
        pr.percent_of_reviews_source_b_past_1_months,
        pr.count_of_reviews_containing_alert_words_past_1_months,
        pr.percent_of_5_star_ratings_past_1_months,
        pr.percent_of_source_a_unable_to_locate_business_resolved_all_tim,
        pr.count_of_all_reviews_past_1_months,
        pr.corporate_filing_secretary_of_state_status_date_all_time,
        pr.average_rating_past_1_months,
        pr.merchant_partnership_tradeline_hit_flag_past_12_months,
        pr.closed_merchant_partnership_tradeline_hit_flag_past_6_mont,
        pr.percent_of_4_star_ratings_past_1_months,
        pr.count_of_closed_underwriting_partner_merchant_part_past_12,
        pr.days_since_earliest_review_past_1_months,
        pr.corporate_filing_secretary_of_state_status_all_time,
        pr.most_recent_bankruptcy_chapter_all_time,
        pr.percent_of_source_a_unable_to_locate_business_resolved_s_past_6,
        pr.count_of_unique_address_line_1_all_time,
        pr.percent_of_complaints_containing_alert_words_all_time,
        pr.count_of_complaints_all_time,
        pr.count_of_closed_out_of_business_partner_merchant_p_all_tim,
        pr.count_of_unique_cities_past_12_months,
        pr.percent_of_complaints_containing_alert_words_past_12_months,
        pr.percent_60_quintile_of_rating_past_3_months,
        pr.days_since_latest_complaint_all_time,
        pr.days_between_earliest_and_latest_complaint_past_12_months,
        pr.days_since_latest_complaint_past_12_months,
        pr.days_since_first_seen_past_24_months,
        pr.days_between_earliest_and_latest_review_all_time,
        pr.count_of_probation_partner_merchant_partnerships_past_1_mo,
        pr.count_of_closed_out_of_business_partner_merchant_p_past_12,
        pr.percent_of_reviews_source_h_past_3_months,
        pr.percent_of_reviews_source_e_past_3_months,
        pr.count_of_reviews_source_i_past_6_months,
        pr.percent_80_quintile_of_rating_all_time,
        pr.count_of_merchant_unknown_partnership_tradelines_past_1_mo,
        pr.count_of_duplicate_reviewers_past_6_months,
        pr.count_of_source_a_unable_to_locate_business_resolv_past_12,
        pr.days_since_latest_close_date_for_merchant_partners_past_3,
        pr.count_of_3_star_ratings_all_time,
        pr.percent_of_unresolved_resolved_status_past_3_months,
        pr.count_of_delinquent_closed_merchant_partnerships_past_3_mo,
        pr.count_of_addresses_past_12_months,
        pr.is_license_expired_all_time,
        pr.count_of_closed_underwriting_partner_merchant_part_all_tim,
        pr.count_of_resolved_resolved_status_past_3_months,
        pr.count_of_delinquent_closed_merchant_partnerships_past_6_mo,
        pr.count_of_suspended_partner_merchant_partnerships_past_3_mo,
        pr.count_of_reviews_source_e_past_3_months,
        pr.percent_of_resolved_resolved_status_past_3_months,
        pr.percent_of_unanswered_resolved_status_all_time,
        bep.md_officer_1_name,
        bep.md_officer_1_title,
        bep.md_officer_2_name,
        bep.md_officer_2_title,
        ver.name_verification,
        ver.address_verification,
        ver.tin_verification,
        ver.watchlist_verification,
        ver.sos_domestic_verification,
        ver.sos_match_verification,
        ver.sos_active_verification,
        ver.beas_full_address,
        ver.beas_address_line_1,
        ver.beas_address_line_2,
        ver.beas_city,
        ver.beas_state,
        ver.beas_postal_code,
        ver.beas_lat,
        ver.beas_long,
        ver.business_entity_verification_id                                AS mid,
        zi.zi_match_confidence
    FROM datascience.smb_standard smb
        LEFT JOIN clients.verification_results ver
                ON smb.business_id = ver.business_id
        LEFT JOIN efx_cte mds
                ON smb.business_id = mds.business_id
        LEFT JOIN zi_cte zi
                ON smb.business_id = zi.business_id
        LEFT JOIN zcs_cte zcs
                ON zi.zi_c_location_id = zcs.zi_c_location_id
            AND zi.zi_c_company_id = zcs.zi_c_company_id
            AND zi.zi_es_location_id = zcs.zi_es_location_id
        LEFT JOIN oc_cte oc
                ON smb.business_id = oc.business_id
        LEFT JOIN warehouse.oc_companies_latest ocs
                ON oc.company_number = ocs.company_number
            AND oc.jurisdiction_code = ocs.jurisdiction_code
        LEFT JOIN oco_cte oco
                ON oc.company_number = oco.company_number
            AND oc.jurisdiction_code = oco.jurisdiction_code
        LEFT JOIN datascience.verdata_aggregate pr
                ON smb.business_id = pr.business_id
        LEFT JOIN bep_cte bep
                ON smb.business_id = bep.business_id
        LEFT JOIN rds_cases_public.data_businesses
                ON data_businesses.id = smb.business_id;

END
$$
