import { hostname } from "os";
import dotenv from "dotenv";

dotenv.config({
	path: process.env.NODE_ENV === "production" ? ".env" : ".env.local"
});

// eslint-disable-next-line no-unused-vars
const parseBool = (str, valueIfEmpty = false) => {
	if (typeof str === "string" && str.length) {
		return str.toLowerCase() === "true";
	}
	return valueIfEmpty;
};

const {
	NODE_ENV,
	CONFIG_APP_PORT,
	CONFIG_HEALTH_CHECK_MODE,
	SUBDOMAIN,
	CONFIG_DB_HOST,
	CONFIG_DB_PORT,
	CONFIG_DB_USER,
	CONFIG_DB_PASSWORD,
	CONFIG_DB_NAME,
	CONFIG_DB_MAX_CONNECTIONS,
	CONFIG_EMAIL_USER,
	CONFIG_CRYPTO_SECRET_KEY,
	CONFIG_CRYPTO_IV,
	CONFIG_CASE_SERVICE_BASE_URL,
	CONFIG_INTEGRATION_SERVICE_BASE_URL,
	CONFIG_KAFKA_GROUP_ID,
	CONFIG_KAFKA_BROKERS,
	CONFIG_KAFKA_SSL_ENABLED,
	CONFIG_KAFKA_CLIENT_ID,
	CONFIG_KAFKA_SASL_USERNAME,
	CONFIG_KAFKA_SASL_PASSWORD,
	CONFIG_REDIS_URL,
	CONFIG_REDIS_HOST,
	CONFIG_REDIS_PORT,
	CONFIG_REDIS_USERNAME,
	CONFIG_REDIS_PASSWORD,
	CONFIG_REDIS_EC_CLUSTER,
	CONFIG_REDIS_DISABLE_TLS,
	CONFIG_REDIS_DISABLE_TLS_REJECT_UNAUTHORIZED,
	CONFIG_REDIS_RECONNECT_MAX_WAIT,
	CONFIG_REDIS_KEY_PREFIX,
	CONFIG_WORTH_ADMIN_USER_POOL_ID,
	CONFIG_CUSTOMER_USER_POOL_ID,
	CONFIG_APPLICANT_USER_POOL_ID,
	CONFIG_WORTH_ADMIN_CLIENT_ID,
	CONFIG_CUSTOMER_CLIENT_ID,
	CONFIG_APPLICANT_CLIENT_ID,
	CONFIG_LD_SDK_KEY,
	CONFIG_LD_INTIALIZATION_TIMEOUT,
	CONFIG_LD_TEST_FLAGS_FILE,
	CONFIG_FRONTEND_LOCAL_BASE_URLS,
	CONFIG_LOG_LEVEL,
	CONFIG_USERS_NEW,
	CONFIG_CASES,
	CONFIG_REPORTS,
	CONFIG_WEBHOOKS,
	CONFIG_INTEGRATIONS,
	CONFIG_NOTIFICATIONS,
	CONFIG_SCORES,
	CONFIG_BUSINESS,
	CONFIG_AI_SCORES,
	CONFIG_DLQTOPIC,
	CONFIG_PLAYGROUND_AI_SCORES
} = process.env;

export const envConfig = {
	ENV: NODE_ENV,
	HOSTNAME: hostname(),

	APP_PORT: parseFloat(CONFIG_APP_PORT),
	HEALTH_CHECK_MODE: parseBool(CONFIG_HEALTH_CHECK_MODE, false),
	SUBDOMAIN,
	LOG_LEVEL: CONFIG_LOG_LEVEL,
	DB_HOST: CONFIG_DB_HOST,
	DB_PORT: CONFIG_DB_PORT,
	DB_USER: CONFIG_DB_USER,
	DB_PASSWORD: CONFIG_DB_PASSWORD,
	DB_NAME: CONFIG_DB_NAME,
	DB_MAX_CONNECTIONS: CONFIG_DB_MAX_CONNECTIONS,

	EMAIL_USER: CONFIG_EMAIL_USER,

	CRYPTO_SECRET_KEY: CONFIG_CRYPTO_SECRET_KEY,
	CRYPTO_IV: CONFIG_CRYPTO_IV,

	CASE_SERVICE_BASE_URL: CONFIG_CASE_SERVICE_BASE_URL,
	INTEGRATION_SERVICE_BASE_URL: CONFIG_INTEGRATION_SERVICE_BASE_URL,

	KAFKA_GROUP_ID: CONFIG_KAFKA_GROUP_ID,
	KAFKA_BROKERS: CONFIG_KAFKA_BROKERS,
	KAFKA_SSL_ENABLED: parseBool(CONFIG_KAFKA_SSL_ENABLED, true),
	KAFKA_CLIENT_ID: CONFIG_KAFKA_CLIENT_ID,
	KAFKA_SASL_USERNAME: CONFIG_KAFKA_SASL_USERNAME,
	KAFKA_SASL_PASSWORD: CONFIG_KAFKA_SASL_PASSWORD,

	REDIS_URL: CONFIG_REDIS_URL,
	REDIS_HOST: CONFIG_REDIS_HOST,
	REDIS_PORT: CONFIG_REDIS_PORT,
	REDIS_USERNAME: CONFIG_REDIS_USERNAME,
	REDIS_PASSWORD: CONFIG_REDIS_PASSWORD,
	REDIS_EC_CLUSTER: parseBool(CONFIG_REDIS_EC_CLUSTER, true),
	REDIS_DISABLE_TLS: parseBool(CONFIG_REDIS_DISABLE_TLS, true),
	REDIS_DISABLE_TLS_REJECT_UNAUTHORIZED: parseBool(CONFIG_REDIS_DISABLE_TLS_REJECT_UNAUTHORIZED, true),
	REDIS_RECONNECT_MAX_WAIT: parseInt(CONFIG_REDIS_RECONNECT_MAX_WAIT),
	REDIS_KEY_PREFIX: CONFIG_REDIS_KEY_PREFIX || "",

	WORTH_ADMIN_USER_POOL_ID: CONFIG_WORTH_ADMIN_USER_POOL_ID,
	CUSTOMER_USER_POOL_ID: CONFIG_CUSTOMER_USER_POOL_ID,
	APPLICANT_USER_POOL_ID: CONFIG_APPLICANT_USER_POOL_ID,

	APPLICANT_CLIENT_ID: CONFIG_APPLICANT_CLIENT_ID,
	WORTH_ADMIN_CLIENT_ID: CONFIG_WORTH_ADMIN_CLIENT_ID,
	CUSTOMER_CLIENT_ID: CONFIG_CUSTOMER_CLIENT_ID,
	LD_SDK_KEY: CONFIG_LD_SDK_KEY,
	LD_INTIALIZATION_TIMEOUT: parseInt(CONFIG_LD_INTIALIZATION_TIMEOUT),
	LD_TEST_FLAGS_FILE: CONFIG_LD_TEST_FLAGS_FILE || "",

	FRONTEND_LOCAL_BASE_URLS: CONFIG_FRONTEND_LOCAL_BASE_URLS || "",

	USERS_NEW: CONFIG_USERS_NEW,
	CASES: CONFIG_CASES,
	BUSINESS: CONFIG_BUSINESS,
	SCORES: CONFIG_SCORES,
	NOTIFICATIONS: CONFIG_NOTIFICATIONS,
	INTEGRATIONS: CONFIG_INTEGRATIONS,
	WEBHOOKS: CONFIG_WEBHOOKS,
	REPORTS: CONFIG_REPORTS,
	AI_SCORES: CONFIG_AI_SCORES,
	DLQTOPIC: CONFIG_DLQTOPIC,
	PLAYGROUND_AI_SCORES: CONFIG_PLAYGROUND_AI_SCORES
};
