"""add names and addresses to table

Revision ID: 20250513115528
Revises: 20250415141017
Create Date: 2025-05-13 11:55:28

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "20250513115528"
down_revision = "20250415141017"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "match_requests", sa.Column("names", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column(
        "match_requests",
        sa.Column("addresses", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match_requests", "addresses")
    op.drop_column("match_requests", "names")
    # ### end Alembic commands ###
