"""add business id

Revision ID: 20250211130057
Revises: 20250211123118
Create Date: 2025-02-11 13:00:57

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "20250211130057"
down_revision = "20250211123118"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("match_requests", sa.Column("business_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match_requests", "business_id")
    # ### end Alembic commands ###
