"""remove payload from request

Revision ID: 20250211123118
Revises: 20250211114941
Create Date: 2025-02-11 12:31:18

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "20250211123118"
down_revision = "20250211114941"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match_requests", "request")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "match_requests",
        sa.Column(
            "request", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
