"""add export-request-table

Revision ID: 20260126154058
Revises: 20260114145457
Create Date: 2026-01-26 15:40:58

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "20260126154058"
down_revision = "20260114145457"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "export_requests",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("customer_id", sa.String(), nullable=False),
        sa.Column("export_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("bucket", sa.String(), nullable=True),
        sa.Column("s3_uri_path", sa.String(), nullable=True),
        sa.Column("record_count", sa.BigInteger(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_export_requests_completed_at"), "export_requests", ["completed_at"], unique=False
    )
    op.create_index(
        op.f("ix_export_requests_customer_id"), "export_requests", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_export_requests_export_type"), "export_requests", ["export_type"], unique=False
    )
    op.create_index(
        op.f("ix_export_requests_started_at"), "export_requests", ["started_at"], unique=False
    )
    op.create_index(op.f("ix_export_requests_status"), "export_requests", ["status"], unique=False)


def downgrade() -> None:
    op.drop_index(op.f("ix_export_requests_status"), table_name="export_requests")
    op.drop_index(op.f("ix_export_requests_started_at"), table_name="export_requests")
    op.drop_index(op.f("ix_export_requests_export_type"), table_name="export_requests")
    op.drop_index(op.f("ix_export_requests_customer_id"), table_name="export_requests")
    op.drop_index(op.f("ix_export_requests_completed_at"), table_name="export_requests")
    op.drop_table("export_requests")
