"""add fact table

Revision ID: 20250415141017
Revises: 20250211130057
Create Date: 2025-04-15 14:10:17

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "20250415141017"
down_revision = "20250211130057"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "facts",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=True),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("business_id", "name"),
        sa.UniqueConstraint("business_id", "name", name="uq_business_id_name"),
    )
    op.create_index(op.f("ix_facts_business_id"), "facts", ["business_id"], unique=False)
    op.create_index(op.f("ix_facts_name"), "facts", ["name"], unique=False)
    op.create_index(op.f("ix_facts_received_at"), "facts", ["received_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_facts_received_at"), table_name="facts")
    op.drop_index(op.f("ix_facts_name"), table_name="facts")
    op.drop_index(op.f("ix_facts_business_id"), table_name="facts")
    op.drop_table("facts")
    # ### end Alembic commands ###
