CREATE OR REPLACE PROCEDURE sp_create_equifax_latest_tables()
    LANGUAGE plpgsql
AS
$$
BEGIN
    DROP TABLE IF EXISTS warehouse.equifax_us_latest;
    CREATE TABLE warehouse.equifax_us_latest AS
    WITH
        latest_efx AS (SELECT
                           efx_id,
                           MAX(TO_DATE(yr || '-' || mon || '-01', 'YYYY-MM-DD')) AS max_date
                       FROM warehouse.equifax_us_raw
                       GROUP BY
                           efx_id

        )
    SELECT
        equifax_us_raw.efx_id,
        efx_name,
        efx_legal_name,
        efx_address,
        efx_city,
        efx_state,
        efx_statec,
        efx_zipcode,
        efx_zip4,
        efx_lat,
        efx_lon,
        efx_geoprec,
        efx_region,
        efx_ctryisocd,
        efx_ctrynum,
        efx_ctryname,
        efx_countynm,
        efx_county,
        efx_cmsa,
        efx_cmsadesc,
        efx_soho,
        efx_biz,
        efx_res,
        efx_cmra,
        efx_congress,
        efx_secadr,
        efx_seccty,
        efx_secstat,
        efx_statec2,
        efx_seczip,
        efx_seczip4,
        efx_seclat,
        efx_seclon,
        efx_secgeoprec,
        efx_secregion,
        efx_secctryisocd,
        efx_secctrynum,
        efx_secctryname,
        efx_ctrytelcd,
        efx_phone,
        efx_faxphone,
        efx_contct,
        efx_titlecd,
        efx_titledesc,
        efx_lastnam,
        efx_fstnam,
        efx_email,
        efx_ceoname,
        efx_ceotitledesc,
        efx_cioname,
        efx_ciotitledesc,
        efx_cfoname,
        efx_cfotitledesc,
        efx_gender,
        efx_ethnicity,
        efx_mbe,
        efx_wbe,
        efx_vet,
        efx_bussize,
        efx_gov,
        efx_fgov,
        efx_nonprofit,
        efx_edu,
        efx_busstat,
        efx_busstatcd,
        efx_web,
        efx_yrest,
        efx_corpempcnt,
        efx_locempcnt,
        efx_corpempcd,
        efx_locempcd,
        efx_corpamount,
        efx_corpamountcd,
        efx_corpamounttp,
        efx_corpamountprec,
        efx_locamount,
        efx_locamountcd,
        efx_locamounttp,
        efx_locamountprec,
        efx_public,
        efx_stkexc,
        efx_tcksym,
        efx_primsic,
        efx_secsic1,
        efx_secsic2,
        efx_secsic3,
        efx_secsic4,
        efx_primsicdesc,
        efx_secsicdesc1,
        efx_secsicdesc2,
        efx_secsicdesc3,
        efx_secsicdesc4,
        efx_primnaicscode,
        efx_secnaics1,
        efx_secnaics2,
        efx_secnaics3,
        efx_secnaics4,
        efx_primnaicsdesc,
        efx_secnaicsdesc1,
        efx_secnaicsdesc2,
        efx_secnaicsdesc3,
        efx_secnaicsdesc4,
        efx_legsubnumall,
        efx_legsubnameall,
        efx_legsubaddressall,
        efx_legsubcityall,
        efx_legsubstateall,
        efx_legsubzipcodeall,
        efx_legsubzip4all,
        efx_legsubcountyall,
        efx_legsubctryisocdall,
        efx_legsubctrynumall,
        efx_legsubctrynameall,
        efx_legdomultnumall,
        efx_legdomultnameall,
        efx_legdomultaddressall,
        efx_legdomultcityall,
        efx_legdomultstateall,
        efx_legdomultzipcodeall,
        efx_legdomultzip4all,
        efx_legdomultcountyall,
        efx_legdomultctryisocdall,
        efx_legdomultctrynumall,
        efx_legdomultctrynameall,
        efx_legultnumall,
        efx_legultnameall,
        efx_legultaddressall,
        efx_legultcityall,
        efx_legultstateall,
        efx_legultzipcodeall,
        efx_legultzip4all,
        efx_legultcountyall,
        efx_legultctryisocdall,
        efx_legultctrynumall,
        efx_legultctrynameall,
        efx_legultparentind,
        efx_legparentind,
        efx_leglinkedind,
        efx_afflultnumall,
        efx_afflultnameall,
        efx_afflultaddressall,
        efx_afflultcityall,
        efx_afflultstateall,
        efx_afflultzipcodeall,
        efx_afflultzip4all,
        efx_affultcountyall,
        efx_afflultctryisocdall,
        efx_afflultctrynumall,
        efx_afflultctrynameall,
        efx_affllinkedind,
        efx_franchise,
        efx_afflultparentind,
        efx_afflparentind,
        efx_foreign,
        efx_failrate,
        efx_faillevel,
        efx_failreason1,
        efx_failreason2,
        efx_failreason3,
        efx_failreason4,
        efx_creditscore,
        efx_creditclass,
        efx_creditperc,
        efx_creditreason1,
        efx_creditreason2,
        efx_creditreason3,
        efx_creditreason4,
        efx_bankruptcy,
        efx_dead,
        efx_deaddt,
        efx_mrkt_telever,
        efx_mrkt_telescore,
        efx_mrkt_totalscore,
        efx_mrkt_totalind,
        efx_mrkt_vacant,
        efx_mrkt_seasonal,
        efx_extract_date,
        efx_date_updated,
        currentcty_4_avg,
        currentst_4_avg,
        "12monthpriorcty_4_avg",
        "12monthpriorst_4_avg",
        efx_merchant_id,
        efx_project_id,
        twelvemonthpriorcty_4_avg,
        twelvemonthpriorst_4_avg,
        efx_mwbe,
        efx_sdb,
        efx_hubzone,
        efx_dbe,
        efx_dvet,
        efx_8a,
        efx_8aexpdt,
        efx_dis,
        efx_sbe,
        efx_hbcu,
        efx_gaylesbian,
        efx_wsbe,
        efx_vsbe,
        efx_dvsbe,
        efx_mwbestatus,
        efx_nmsdc,
        efx_wbenc,
        efx_ca_puc,
        efx_tx_hub,
        efx_tx_hubcertnum,
        efx_gsax,
        efx_caltrans,
        efx_mi,
        efx_anc,
        efx_cert1,
        efx_cert2,
        efx_cert3,
        efx_cert4,
        efx_cert5,
        efx_cert6,
        efx_cert7,
        efx_cert8,
        efx_cert9,
        efx_cert10,
        efx_certdesc1,
        efx_certdesc2,
        efx_certdesc3,
        efx_certdesc4,
        efx_certdesc5,
        efx_certdesc6,
        efx_certdesc7,
        efx_certdesc8,
        efx_certdesc9,
        efx_certdesc10,
        efx_certsrc1,
        efx_certsrc2,
        efx_certsrc3,
        efx_certsrc4,
        efx_certsrc5,
        efx_certsrc6,
        efx_certsrc7,
        efx_certsrc8,
        efx_certsrc9,
        efx_certsrc10,
        efx_certlev1,
        efx_certlev2,
        efx_certlev3,
        efx_certlev4,
        efx_certlev5,
        efx_certlev6,
        efx_certlev7,
        efx_certlev8,
        efx_certlev9,
        efx_certlev10,
        efx_certnum1,
        efx_certnum2,
        efx_certnum3,
        efx_certnum4,
        efx_certnum5,
        efx_certnum6,
        efx_certnum7,
        efx_certnum8,
        efx_certnum9,
        efx_certnum10,
        efx_certexp1,
        efx_certexp2,
        efx_certexp3,
        efx_certexp4,
        efx_certexp5,
        efx_certexp6,
        efx_certexp7,
        efx_certexp8,
        efx_certexp9,
        efx_certexp10,
        efx_legentityparentnum,
        efx_legentityparentname,
        efx_legentitysubsidiaryind,
        efx_legentityind,
        efx_cancreditscorecds,
        efx_cancreditrejcdcds,
        efx_cancreditreason3cds,
        efx_cancreditreason4cds,
        efx_cancreditscorebfrs,
        efx_cancreditrejcdbfrs,
        efx_cancreditreason1bfrs,
        efx_cancreditreason2bfrs,
        efx_cancreditdate,
        efx_affldomultnumall,
        efx_affldomultnameall,
        efx_affldomultaddressall,
        efx_affldomultcityall,
        efx_affldomultstateall,
        efx_affldomultzipcodeall,
        efx_affldomultzip4all,
        efx_affldomultcountyall,
        efx_affldomultctryisocdall,
        efx_affldomultctrynumall,
        efx_affldomultctrynameall,
        efx_lbe,
        efx_gov1057,
        efx_merctype,
        latest_efx.max_date
    FROM warehouse.equifax_us_raw
        INNER JOIN latest_efx
                ON equifax_us_raw.efx_id = latest_efx.efx_id
            AND
                   TO_DATE(equifax_us_raw.yr || '-' || equifax_us_raw.mon || '-01', 'YYYY-MM-DD') = latest_efx.max_date
    WHERE latest_efx.efx_id IN (SELECT efx_id FROM datascience.efx_matches_custom_inc_ml);
END;
$$;

--     DROP TABLE IF EXISTS warehouse.equifax_bma_latest;
--     CREATE TABLE warehouse.equifax_bma_latest AS
--     WITH
--         latest_efx AS (SELECT
--                            efx_id,
--                            MAX(CAST(yr AS INT))  AS yr,
--                            MAX(CAST(mon AS INT)) AS mon
--                        FROM warehouse.equifax_bma_raw
--                        GROUP BY
--                            efx_id

--         )
--     SELECT
--         equifax_bma_raw.efx_id,
--         efxbma_1m_ind_2c_past_due_count,
--         efxbma_1m_ind_2pc_past_due_count,
--         efxbma_1m_ind_3c_past_due_count,
--         efxbma_1m_ind_3pc_past_due_count,
--         efxbma_1m_ind_4pc_past_due_count,
--         efxbma_1m_ind_tr_count,
--         efxbma_1m_ind_tr_total_bal,
--         efxbma_1m_ind_worst_payment_status,
--         efxbma_1m_nfin_1c_past_due_count,
--         efxbma_1m_nfin_1pc_past_due_count,
--         efxbma_1m_nfin_2c_past_due_count,
--         efxbma_1m_nfin_2pc_past_due_count,
--         efxbma_1m_nfin_3c_past_due_count,
--         efxbma_1m_nfin_3pc_past_due_count,
--         efxbma_1m_nfin_4pc_past_due_count,
--         efxbma_1m_nfin_chargeoff_tr_count,
--         efxbma_1m_nfin_closed_acc_count,
--         efxbma_1m_nfin_curr_credit_lim,
--         efxbma_1m_nfin_open_acc_count,
--         efxbma_1m_nfin_orig_credit_lim,
--         efxbma_1m_nfin_past_due_amount,
--         efxbma_1m_nfin_payment_index,
--         efxbma_1m_nfin_per_satisfactory_acc,
--         efxbma_1m_nfin_satisfactory_tr_count,
--         efxbma_1m_nfin_total_chargeoff_amt,
--         efxbma_1m_nfin_total_util,
--         efxbma_1m_nfin_tr_count,
--         efxbma_1m_nfin_tr_total_bal,
--         efxbma_1m_nfin_worst_payment_status,
--         efxbma_1m_serv_tr_count,
--         efxbma_1m_serv_tr_total_bal,
--         efxbma_1m_tel_1c_past_due_count,
--         efxbma_1m_tel_1pc_past_due_count,
--         efxbma_1m_tel_2c_past_due_count,
--         efxbma_1m_tel_2pc_past_due_count,
--         efxbma_1m_tel_3c_past_due_count,
--         efxbma_1m_tel_3pc_past_due_count,
--         efxbma_1m_tel_4pc_past_due_count,
--         efxbma_1m_tel_tr_count,
--         efxbma_1m_tel_tr_total_bal,
--         efxbma_1m_tel_worst_payment_status,
--         efxbma_1m_util_1c_past_due_count,
--         efxbma_1m_util_1pc_past_due_count,
--         efxbma_1m_util_2c_past_due_count,
--         efxbma_1m_util_2pc_past_due_count,
--         efxbma_1m_util_3c_past_due_count,
--         efxbma_1m_util_3pc_past_due_count,
--         efxbma_1m_util_4pc_past_due_count,
--         efxbma_1m_util_tr_count,
--         efxbma_1m_util_tr_total_bal,
--         efxbma_1m_util_worst_payment_status,
--         efxbma_3m_ind_1c_past_due_count,
--         efxbma_3m_ind_1pc_past_due_count,
--         efxbma_3m_ind_2c_past_due_count,
--         efxbma_3m_ind_2pc_past_due_count,
--         efxbma_3m_ind_3c_past_due_count,
--         efxbma_3m_ind_3pc_past_due_count,
--         efxbma_3m_ind_4pc_past_due_count,
--         efxbma_3m_ind_tr_count,
--         efxbma_3m_ind_tr_high_bal,
--         efxbma_3m_ind_tr_wb_count,
--         efxbma_3m_ind_worst_payment_status,
--         efxbma_3m_nfin_1c_past_due_amount,
--         efxbma_3m_nfin_1c_past_due_count,
--         efxbma_3m_nfin_1pc_past_due_count,
--         efxbma_3m_nfin_2c_past_due_amount,
--         efxbma_3m_nfin_2c_past_due_count,
--         efxbma_3m_nfin_2pc_past_due_count,
--         efxbma_3m_nfin_3c_past_due_amount,
--         efxbma_3m_nfin_3c_past_due_count,
--         efxbma_3m_nfin_3pc_past_due_count,
--         efxbma_3m_nfin_4pc_past_due_amount,
--         efxbma_3m_nfin_4pc_past_due_count,
--         efxbma_3m_nfin_chargeoff_tr_count,
--         efxbma_3m_nfin_high_credit_lim,
--         efxbma_3m_nfin_new_acc_count,
--         efxbma_3m_nfin_orig_credit_lim,
--         efxbma_3m_nfin_past_due_amount,
--         efxbma_3m_nfin_per_4pc_pd_to_totbal,
--         efxbma_3m_nfin_per_coff_to_tot_acc,
--         efxbma_3m_nfin_per_pd_to_totbal,
--         efxbma_3m_nfin_per_satisfactory_acc,
--         efxbma_3m_nfin_ratio_num_nondel_to_acc,
--         efxbma_3m_nfin_satisfactory_tr_count,
--         efxbma_3m_nfin_total_chargeoff_amt,
--         efxbma_3m_nfin_total_util,
--         efxbma_3m_nfin_tr_count,
--         efxbma_3m_nfin_tr_high_bal,
--         efxbma_3m_nfin_tr_wb_count,
--         efxbma_3m_nfin_worst_payment_status,
--         efxbma_3m_serv_past_due_amount,
--         efxbma_3m_serv_tr_count,
--         efxbma_3m_serv_tr_high_bal,
--         efxbma_3m_serv_tr_wb_count,
--         efxbma_3m_tel_1c_past_due_count,
--         efxbma_3m_tel_1pc_past_due_count,
--         efxbma_3m_tel_2c_past_due_count,
--         efxbma_3m_tel_2pc_past_due_count,
--         efxbma_3m_tel_3c_past_due_count,
--         efxbma_3m_tel_3pc_past_due_count,
--         efxbma_3m_tel_4pc_past_due_count,
--         efxbma_3m_tel_tr_count,
--         efxbma_3m_tel_tr_high_bal,
--         efxbma_3m_tel_tr_wb_count,
--         efxbma_3m_tel_worst_payment_status,
--         efxbma_3m_util_1c_past_due_count,
--         efxbma_3m_util_1pc_past_due_count,
--         efxbma_3m_util_2c_past_due_count,
--         efxbma_3m_util_2pc_past_due_count,
--         efxbma_3m_util_3c_past_due_count,
--         efxbma_3m_util_3pc_past_due_count,
--         efxbma_3m_util_4pc_past_due_count,
--         efxbma_3m_util_tr_count,
--         efxbma_3m_util_tr_high_bal,
--         efxbma_3m_util_tr_wb_count,
--         efxbma_3m_util_worst_payment_status,
--         efxbma_12m_ind_1c_past_due_count,
--         efxbma_12m_ind_1pc_past_due_count,
--         efxbma_12m_ind_2c_past_due_count,
--         efxbma_12m_ind_2pc_past_due_count,
--         efxbma_12m_ind_3c_past_due_count,
--         efxbma_12m_ind_3pc_past_due_count,
--         efxbma_12m_ind_4pc_past_due_count,
--         efxbma_12m_ind_tr_count,
--         efxbma_12m_ind_tr_high_bal,
--         efxbma_12m_ind_worst_payment_status,
--         efxbma_12m_nfin_1c_past_due_amount,
--         efxbma_12m_nfin_1c_past_due_count,
--         efxbma_12m_nfin_1pc_past_due_count,
--         efxbma_12m_nfin_2c_past_due_amount,
--         efxbma_12m_nfin_2c_past_due_count,
--         efxbma_12m_nfin_2pc_past_due_count,
--         efxbma_12m_nfin_3c_past_due_amount,
--         efxbma_12m_nfin_3c_past_due_count,
--         efxbma_12m_nfin_3pc_past_due_count,
--         efxbma_12m_nfin_4pc_past_due_amount,
--         efxbma_12m_nfin_4pc_past_due_count,
--         efxbma_12m_nfin_chargeoff_tr_count,
--         efxbma_12m_nfin_high_credit_lim,
--         efxbma_12m_nfin_orig_credit_lim,
--         efxbma_12m_nfin_past_due_amount,
--         efxbma_12m_nfin_per_4pc_pd_to_totbal,
--         efxbma_12m_nfin_per_coff_to_tot_acc,
--         efxbma_12m_nfin_per_pd_to_totbal,
--         efxbma_12m_nfin_per_satisfactory_acc,
--         efxbma_12m_nfin_satisfactory_tr_count,
--         efxbma_12m_nfin_total_chargeoff_amt,
--         efxbma_12m_nfin_total_util,
--         efxbma_12m_nfin_tr_count,
--         efxbma_12m_nfin_tr_high_bal,
--         efxbma_12m_nfin_worst_payment_status,
--         efxbma_12m_serv_tr_count,
--         efxbma_12m_serv_tr_high_bal,
--         efxbma_12m_tel_1c_past_due_count,
--         efxbma_12m_tel_1pc_past_due_count,
--         efxbma_12m_tel_2c_past_due_count,
--         efxbma_12m_tel_2pc_past_due_count,
--         efxbma_12m_tel_3c_past_due_count,
--         efxbma_12m_tel_3pc_past_due_count,
--         efxbma_12m_tel_4pc_past_due_count,
--         efxbma_12m_tel_tr_count,
--         efxbma_12m_tel_tr_high_bal,
--         efxbma_12m_tel_worst_payment_status,
--         efxbma_12m_util_1c_past_due_count,
--         efxbma_12m_util_1pc_past_due_count,
--         efxbma_12m_util_2c_past_due_count,
--         efxbma_12m_util_2pc_past_due_count,
--         efxbma_12m_util_3c_past_due_count,
--         efxbma_12m_util_3pc_past_due_count,
--         efxbma_12m_util_4pc_past_due_count,
--         efxbma_12m_util_tr_count,
--         efxbma_12m_util_tr_high_bal,
--         efxbma_12m_util_worst_payment_status,
--         efxbma_24m_ind_1c_past_due_count,
--         efxbma_24m_ind_1pc_past_due_count,
--         efxbma_24m_ind_2c_past_due_count,
--         efxbma_24m_ind_2pc_past_due_count,
--         efxbma_24m_ind_3c_past_due_count,
--         efxbma_24m_ind_3pc_past_due_count,
--         efxbma_24m_ind_4pc_past_due_count,
--         efxbma_24m_ind_tr_count,
--         efxbma_24m_ind_tr_high_bal,
--         efxbma_24m_ind_worst_payment_status,
--         efxbma_24m_nfin_1c_past_due_amount,
--         efxbma_24m_nfin_1c_past_due_count,
--         efxbma_24m_nfin_1pc_past_due_count,
--         efxbma_24m_nfin_2c_past_due_amount,
--         efxbma_24m_nfin_2c_past_due_count,
--         efxbma_24m_nfin_2pc_past_due_count,
--         efxbma_24m_nfin_3c_past_due_amount,
--         efxbma_24m_nfin_3c_past_due_count,
--         efxbma_24m_nfin_3pc_past_due_count,
--         efxbma_24m_nfin_4pc_past_due_amount,
--         efxbma_24m_nfin_4pc_past_due_count,
--         efxbma_24m_nfin_chargeoff_tr_count,
--         efxbma_24m_nfin_high_credit_lim,
--         efxbma_24m_nfin_orig_credit_lim,
--         efxbma_24m_nfin_past_due_amount,
--         efxbma_24m_nfin_per_4pc_pd_to_totbal,
--         efxbma_24m_nfin_per_coff_to_tot_acc,
--         efxbma_24m_nfin_per_pd_to_totbal,
--         efxbma_24m_nfin_per_satisfactory_acc,
--         efxbma_24m_nfin_satisfactory_tr_count,
--         efxbma_24m_nfin_total_chargeoff_amt,
--         efxbma_24m_nfin_total_util,
--         efxbma_24m_nfin_tr_count,
--         efxbma_24m_nfin_tr_high_bal,
--         efxbma_24m_nfin_worst_payment_status,
--         efxbma_24m_serv_tr_count,
--         efxbma_24m_serv_tr_high_bal,
--         efxbma_24m_tel_1c_past_due_count,
--         efxbma_24m_tel_1pc_past_due_count,
--         efxbma_24m_tel_2c_past_due_count,
--         efxbma_24m_tel_2pc_past_due_count,
--         efxbma_24m_tel_3c_past_due_count,
--         efxbma_24m_tel_3pc_past_due_count,
--         efxbma_24m_tel_4pc_past_due_count,
--         efxbma_24m_tel_tr_count,
--         efxbma_24m_tel_tr_high_bal,
--         efxbma_24m_tel_worst_payment_status,
--         efxbma_24m_util_1c_past_due_count,
--         efxbma_24m_util_1pc_past_due_count,
--         efxbma_24m_util_2c_past_due_count,
--         efxbma_24m_util_2pc_past_due_count,
--         efxbma_24m_util_3c_past_due_count,
--         efxbma_24m_util_3pc_past_due_count,
--         efxbma_24m_util_4pc_past_due_count,
--         efxbma_24m_util_tr_count,
--         efxbma_24m_util_tr_high_bal,
--         efxbma_24m_util_worst_payment_status,
--         efxbma_pubrec_age_bkp,
--         efxbma_pubrec_age_judg,
--         efxbma_pubrec_age_lien,
--         efxbma_pubrec_age_pr,
--         efxbma_pubrec_bkp_ind,
--         efxbma_pubrec_judg_ind,
--         efxbma_pubrec_lien_ind,
--         efxbma_pubrec_lien_judg_ind,
--         efxbma_pubrec_max_liab_rep_judg,
--         efxbma_pubrec_max_liab_rep_lien,
--         efxbma_pubrec_status_fi,
--         efxbma_pubrec_status_fi_ju,
--         efxbma_pubrec_status_ju,
--         efxbma_pubrec_sum_lien_all_judg,
--         efxbma_pubrec_total_cur_liab_judg,
--         efxbma_pubrec_total_cur_liab_judg_all,
--         efxbma_pubrec_total_cur_liab_lien,
--         efxbma_pubrec_total_cur_liab_lien_all,
--         efxbma_pubrec_total_cur_liab_lien_judg,
--         efxbma_pubrec_total_judg,
--         efxbma_pubrec_total_lien,
--         efxbma_pubrec_total_lien_judg,
--         efxbma_1m_ind_1c_past_due_count,
--         efxbma_1m_ind_1pc_past_due_count,
--         efxbma_extract_date,
--         partition_0,
--         equifax_bma_raw.yr,
--         equifax_bma_raw.mon
--     FROM warehouse.equifax_bma_raw
--         INNER JOIN latest_efx
--                 ON equifax_bma_raw.efx_id = latest_efx.efx_id
--             AND CAST(equifax_bma_raw.yr AS SMALLINT) = latest_efx.yr
--             AND CAST(equifax_bma_raw.mon AS SMALLINT) = latest_efx.mon
--     WHERE latest_efx.efx_id IN (SELECT efx_id FROM datascience.efx_matches_custom_inc_ml);
-- END;
-- $$;
