import { getOrCreateConnection } from "#helpers/platformHelper";
import { logger } from "#helpers/logger";
import type { IntegrationPlatformId } from "#constants";
import type { UUID } from "crypto";
import { getTaskCodesToRun } from "./getTaskCodesToRun";
import { canExecuteConnection } from "./canExecuteConnection";
import type { ConnectionWithTasks } from "./getConnectionsAndTasks";
import { getAdapter } from "../adapters";
import { isEmpty } from "#utils";
import type { ProcessTasksForConnectionResult } from "./types";
import { getPlatform } from "./getPlatform";

/**
 * Processes tasks for a single connection: validates it, gets task codes, and processes all tasks.
 * Each adapter handles its own metadata generation and task processing.
 */
export const processTasksForConnection = async (
	business_id: string,
	conn: ConnectionWithTasks,
	requestedTaskCodes?: string[],
	/**
	 * Optional metadata override to pass to each adapter process function.
	 * By default, the metadata is generated by the adapters -- however, you can provide your own metadata via this field.
	 *
	 * WARNING: The same metadata will be passed to *all* process functions, so you must ensure it is compatible with all adapters.
	 * 			This field is generally only intended to be used for testing or debugging purposes.
	 */
	metadataOverride?: Record<string, any>,
	/**
	 * Optional score trigger ID to associate with created tasks.
	 * This enables completion tracking for rerun integrations.
	 */
	scoreTriggerId?: UUID
): Promise<ProcessTasksForConnectionResult> => {
	const tasksCreated: ProcessTasksForConnectionResult["tasksCreated"] = [];
	const errors: ProcessTasksForConnectionResult["errors"] = [];
	const { connection_id, platform_code, platform_id, task_codes } = conn;

	try {
		// Get the connection
		const dbConnection = await getOrCreateConnection(business_id as UUID, platform_id as IntegrationPlatformId);
		if (!dbConnection) {
			errors.push({
				connection_id,
				platform_code,
				error: `Could not get or create business ${business_id} - connection ${connection_id}`
			});
			return { tasksCreated, errors };
		}

		// Check if connection status allows execution
		if (!canExecuteConnection(platform_id, dbConnection.connection_status)) {
			const errorMessage = `Connection status '${dbConnection.connection_status}' does not allow execution`;
			logger.debug(
				`Skipping business ${business_id} - connection ${connection_id} for platform ${platform_code} - ${errorMessage}`
			);
			errors.push({ connection_id, platform_code, error: errorMessage });
			return { tasksCreated, errors };
		}

		// Get platform instance
		const platform = await getPlatform(dbConnection);

		// Determine which task codes to run
		const taskCodesToRun = await getTaskCodesToRun({
			connectionTaskCodes: task_codes,
			platformId: platform_id,
			requestedTaskCodes
		});

		// If no task codes were determined to run, report it
		if (taskCodesToRun.length === 0) {
			const errorMessage = requestedTaskCodes
				? `No matching task codes found. Requested: ${requestedTaskCodes.join(", ")}, Available: ${task_codes.join(", ") || "none"}`
				: `No task codes available for this connection`;
			logger.debug(
				`No task codes to run for business ${business_id} - connection ${connection_id} (platform ${platform_code}) - ${errorMessage}`
			);
			errors.push({ connection_id, platform_code, error: errorMessage });
			return { tasksCreated, errors };
		}

		// Get adapter for this platform
		const adapter = getAdapter(platform_id as IntegrationPlatformId);

		// Create and process tasks for each task code
		for (const task_code of taskCodesToRun) {
			const params = { platform, task_code, connection_id, platform_code, platform_id, business_id, scoreTriggerId };
			try {
				if (!adapter)
					throw new Error(`No adapter found for business ${business_id} - platform ${platform_code} (${platform_id})`);

				/** Check if the adapter can run */
				const canRun = await adapter.checkRunnable(params);
				if (!canRun)
					throw new Error(`Adapter ${platform_code} cannot run for business ${business_id} - task ${task_code}`);

				logger.debug(
					`Using adapter process function for business ${business_id} - platform ${platform_code} - task ${task_code} ${isEmpty(metadataOverride) ? "" : `with metadata override: ${JSON.stringify(metadataOverride)}`}`
				);

				/** Use the metadata override if provided */
				let metadata = metadataOverride;
				/** Generate metadata if no override was provided */
				if (isEmpty(metadata)) metadata = await adapter.getMetadata(business_id);

				const isValidMetadata: (metadata: any) => boolean = adapter.isValidMetadata ?? (metadata => !isEmpty(metadata));
				/** If metadata is *still* empty, throw an error */
				if (!isValidMetadata(metadata))
					throw new Error(
						`No metadata generated for business ${business_id} - platform ${platform_code} (${platform_id})`
					);

				logger.debug(
					{ metadata },
					`Metadata for business ${business_id} - platform ${platform_code} - task ${task_code}`
				);

				/** Process the task */
				const taskIds = await adapter.process({ ...params, metadata });

				taskIds.forEach(taskId => tasksCreated.push({ connection_id, platform_code, task_code, task_id: taskId }));
			} catch (error: unknown) {
				logger.error(error, `Error processing business ${business_id} - platform ${platform_code} - task ${task_code}`);
				errors.push({
					connection_id,
					platform_code,
					error: error instanceof Error ? error.message : "Unknown error"
				});
			}
		}
	} catch (error: unknown) {
		logger.error(
			error,
			`Error processing business ${business_id} - connection ${conn.connection_id} for platform ${conn.platform_code}`
		);
		errors.push({ connection_id, platform_code, error: error instanceof Error ? error.message : "Unknown error" });
	}

	return { tasksCreated, errors };
};
