import dotenv from "dotenv";
import { hostname } from "os";

dotenv.config({
	path: process.env.NODE_ENV === "production" ? ".env" : ".env.local"
});

const parseBool = (str, valueIfEmpty = false) => {
	if (typeof str === "string" && str.length) {
		return str.toLowerCase() === "true";
	}
	return valueIfEmpty;
};

/**
 * Parses a string to an integer, returning the value if empty or NaN
 * @param {string} str - The string to parse
 * @param {number} valueIfEmpty - The value to return if the string is empty or parsed integer is NaN
 * @returns {number} The parsed integer
 */
const forceInt = (str, valueIfEmpty = 0) => {
	try {
		const int = parseInt(str, 10);
		if (int == null || Number.isNaN(int) || !Number.isSafeInteger(int)) {
			throw new Error("Invalid integer");
		}
		return int;
	} catch (_) {
		return valueIfEmpty;
	}
};

const {
	NODE_ENV,
	CONFIG_APP_PORT,
	CONFIG_HEALTH_CHECK_MODE,
	SUBDOMAIN,
	DD_ENV,
	CONFIG_SERVICE_MODE,
	CONFIG_WORKER_TYPE,

	CONFIG_DB_HOST,
	CONFIG_DB_PORT,
	CONFIG_DB_USER,
	CONFIG_DB_PASSWORD,
	CONFIG_DB_NAME,
	CONFIG_DB_MAX_CONNECTIONS,
	CONFIG_CASE_BASE_URL,
	CONFIG_MANUAL_SCORE_BASE_URL,

	CONFIG_KAFKA_GROUP_ID,
	CONFIG_KAFKA_BROKERS,
	CONFIG_KAFKA_SSL_ENABLED,
	CONFIG_KAFKA_CLIENT_ID,
	CONFIG_KAFKA_SASL_USERNAME,
	CONFIG_KAFKA_SASL_PASSWORD,
	CONFIG_KAFKA_DISABLE_CONSUMER,

	CONFIG_APPLICANT_FRONTEND_BASE_URL,
	CONFIG_WORTH_ADMIN_FRONTEND_BASE_URL,
	CONFIG_CUSTOMER_ADMIN_FRONTEND_BASE_URL,
	CONFIG_FRONTEND_LOCAL_BASE_URLS,

	CONFIG_PERSONA_API_KEY,
	CONFIG_PERSONA_INQUIRY_TEMPLATE_ID,
	CONFIG_PERSONA_VERSION,

	CONFIG_AWS_APP_CLIENT_ID,
	CONFIG_AWS_COGNITO_USER_POOL_ID,
	CONFIG_WORTH_ADMIN_USER_POOL_ID,
	CONFIG_CUSTOMER_USER_POOL_ID,
	CONFIG_APPLICANT_USER_POOL_ID,
	CONFIG_AWS_COGNITO_REGION,
	CONFIG_AWS_ACCESS_KEY_ID,
	CONFIG_AWS_ACCESS_KEY_SECRET,
	CONFIG_AWS_DATA_ACCESS_KEY_ID,
	CONFIG_AWS_DATA_ACCESS_KEY_SECRET,
	CONFIG_AWS_KMS_KEY_ID,
	CONFIG_WORTH_ADMIN_CLIENT_ID,
	CONFIG_CUSTOMER_CLIENT_ID,
	CONFIG_APPLICANT_CLIENT_ID,
	CONFIG_AWS_WEBSITE_SCREENSHOT_BUCKET,

	CONFIG_PLAID_CLIENT_ID,
	CONFIG_PLAID_SECRET,
	CONFIG_PLAID_REDIRECT_URI,
	CONFIG_PLAID_ENV,
	CONFIG_PLAID_ASSETS_WEBHOOK_URL,
	CONFIG_PLAID_LINK_WEBHOOK_URL,
	CONFIG_PLAID_IDV_TEMPLATE_ID,

	CONFIG_PLAID_SANDBOX_CLIENT_ID,
	CONFIG_PLAID_SANDBOX_SECRET,
	CONFIG_PLAID_SANDBOX_ENV,
	CONFIG_PLAID_SANDBOX_IDV_TEMPLATE_ID,

	CONFIG_QUICKBOOKS_CLIENT_ID,
	CONFIG_QUICKBOOKS_SECRET,
	CONFIG_QUICKBOOKS_ENVIRONMENT,
	CONFIG_QUICKBOOKS_REDIRECT_URI,

	CONFIG_TIN_LOGIN_ID,
	CONFIG_TIN_LOGIN_PASSWORD,

	CONFIG_MIDDESK_API_KEY,
	CONFIG_MIDDESK_BASE_URL,
	CONFIG_MIDDESK_WEBHOOK_SECRET,
	CONFIG_MIDDESK_TIN_MOCK_TIMEOUT,
	CONFIG_CRYPTO_SECRET_KEY,

	CONFIG_TAX_STATUS_CLIENT_ID,
	CONFIG_TAX_STATUS_CLIENT_SECRET,
	CONFIG_TAX_STATUS_ACCESS_URL,
	CONFIG_TAX_STATUS_SCOPE,
	CONFIG_TAX_STATUS_EUID,
	CONFIG_TAX_STATUS_BASE_URL,
	CONFIG_TAX_STATUS_COMPANY_ID,
	CONFIG_TAX_STATUS_CALLBACK_URL,
	CONFIG_TAX_STATUS_SUCCESS_REDIRECT_URL,

	CONFIG_RUTTER_URL,
	CONFIG_RUTTER_CLIENT_ID,
	CONFIG_RUTTER_SECRET,
	CONFIG_RUTTER_PUBLIC_KEY,

	CONFIG_VERDATA_LENDER_ID,
	CONFIG_VERDATA_AUTHORIZATION_TOKEN,
	CONFIG_VERDATA_KEY,
	CONFIG_VERDATA_WEBHOOK_URL,
	CONFIG_AWS_S3_BUCKET_URL,

	CONFIG_EQUIFAX_BASE_URL,
	CONFIG_EQUIFAX_CLIENT_ID,
	CONFIG_EQUIFAX_CLIENT_SECRET,
	CONFIG_EQUIFAX_MEMBER_NUMBER,
	CONFIG_EQUIFAX_SECURITY_CODE,
	CONFIG_EQUIFAX_ATHENA_DB,
	CONFIG_EQUIFAX_ATHENA_S3_OUTPUT,

	CONFIG_EQUIFAX_SANDBOX_BASE_URL,
	CONFIG_EQUIFAX_SANDBOX_CLIENT_ID,
	CONFIG_EQUIFAX_SANDBOX_CLIENT_SECRET,
	CONFIG_EQUIFAX_SANDBOX_MEMBER_NUMBER,
	CONFIG_EQUIFAX_SANDBOX_SECURITY_CODE,

	CONFIG_CRYPTO_IV,
	CONFIG_AWS_SES_REGION,
	CONFIG_AWS_ASSETS_BUCKET,
	CONFIG_AWS_INTEGRATION_BUCKET,
	CONFIG_AWS_CUSTOMER_UPLOAD_BUCKET,
	CONFIG_AWS_CUSTOMER_UPLOAD_KEY_PREFIX,
	CONFIG_ECONOMICS_OBSERVATION_START_DATE,
	CONFIG_AWS_ELECTRONIC_CONSENT_BUCKET,

	CONFIG_OPEN_AI_KEY,
	CONFIG_REDIS_URL,
	CONFIG_REDIS_HOST,
	CONFIG_REDIS_PORT,
	CONFIG_REDIS_USERNAME,
	CONFIG_REDIS_PASSWORD,
	CONFIG_REDIS_EC_CLUSTER,
	CONFIG_REDIS_DISABLE_TLS,
	CONFIG_REDIS_DISABLE_TLS_REJECT_UNAUTHORIZED,
	CONFIG_REDIS_RECONNECT_MAX_WAIT,
	CONFIG_REDIS_KEY_PREFIX,
	CONFIG_REDSHIFT_CLUSTER_ID,
	CONFIG_REDSHIFT_DATABASE,
	CONFIG_REDSHIFT_USER,
	CONFIG_REDSHIFT_WORKGROUP_ARN,
	CONFIG_REDSHIFT_SECRET_ARN,
	CONFIG_REDSHIFT_WORKGROUP_NAME,
	CONFIG_BULL_MQ_FETCH_SELLER_RETRY_ATTEMPTS,
	CONFIG_BULL_MQ_FETCH_SELLER_REFETCH_TIME,
	CONFIG_BULL_MQ_SANDBOX_WORKER_COUNT,
	CONFIG_AUTH_BASE_URL,

	CONFIG_GOOGLE_MAP_API_KEY,

	CONFIG_CRYPTO_SECRET_KEY_V2,
	CONFIG_CRYPTO_IV_V2,
	CONFIG_FRED_API_KEY,
	CONFIG_GOOGLE_BUSINESS_CLIENT_ID,
	CONFIG_GOOGLE_BUSINESS_CLIENT_SECRET,
	CONFIG_GOOGLE_BUSINESS_REDIRECT_URI,
	CONFIG_LD_SDK_KEY,
	CONFIG_LD_INTIALIZATION_TIMEOUT,
	CONFIG_LD_TEST_FLAGS_FILE,
	CONFIG_SERPAPI_KEY,
	CONFIG_LOG_LEVEL,
	CONFIG_NOTIFICATION_BASE_URL,
	CONFIG_USERS_NEW,
	CONFIG_CASES,
	CONFIG_REPORTS,
	CONFIG_WEBHOOKS,
	CONFIG_INTEGRATIONS,
	CONFIG_NOTIFICATIONS,
	CONFIG_SCORES,
	CONFIG_BUSINESS,
	CONFIG_DLQTOPIC,
	CONFIG_ECONSENT_API_KEY,
	CONFIG_ELECTRONIC_CONSENT_BASE_URL,
	CONFIG_ELECTRONIC_CONSENT,
	CONFIG_MAX_CONCURRENT_QUERIES,
	CONFIG_SYNCHRONOUS_API_TIMEOUT_SECONDS,
	CONFIG_GIACT_API_ENDPOINT,
	CONFIG_GIACT_API_USERNAME,
	CONFIG_GIACT_API_PASSWORD,
	CONFIG_GIACT_SANDBOX_API_ENDPOINT,
	CONFIG_GIACT_SANDBOX_API_USERNAME,
	CONFIG_GIACT_SANDBOX_API_PASSWORD,
	CONFIG_WAREHOUSE_BASE_URL,
	CONFIG_FACTS_KAFKA_TOPIC,
	CONFIG_WAREHOUSE_KAFKA_TOPIC,
	CONFIG_ENTITY_MATCHING_REQUEST_KAFKA_TOPIC,
	CONFIG_EXPRESS_CACHE_SECONDS,
	CONFIG_MATCH_ENV,
	CONFIG_MATCH_SANDBOX_URL,
	CONFIG_MATCH_PRODUCTION_URL,
	CONFIG_MATCH_MTF_URL,
	CONFIG_TRULIOO_AUTH_API,
	CONFIG_TRULIOO_CLIENT_ID,
	CONFIG_TRULIOO_CLIENT_SECRET,
	CONFIG_TRULIOO_INITFLOW_API,
	CONFIG_TRULIOO_KYB_FLOWID,
	CONFIG_TRULIOO_PSC_FLOWID,
	CONFIG_TRULIOO_RETRIEVE_API,
	CONFIG_TRULIOO_SUBMIT_API,
	CONFIG_TRULIOO_WEBHOOK_SECRET,

	CONFIG_KYX_BASE_URL,
	CONFIG_KYX_TENANT_NAME,
	CONFIG_KYX_CLIENT_ID,
	CONFIG_KYX_CLIENT_SECRET,
	CONFIG_KYX_ENV_MODE,

	CONFIG_STRIPE_PUBLIC_KEY,
	CONFIG_STRIPE_SECRET_KEY,
	CONFIG_STRIPE_WEBHOOK_URL,
	CONFIG_VERDATA_CALLBACK_SECRET,
	CONFIG_VERDATA_SIGNATURE_MAX_AGE_SECONDS
} = process.env;

export const envConfig = {
	ENV: NODE_ENV,
	HOSTNAME: hostname(),

	APP_PORT: parseFloat(CONFIG_APP_PORT),
	HEALTH_CHECK_MODE: parseBool(CONFIG_HEALTH_CHECK_MODE, false),
	SUBDOMAIN,
	DD_ENV,
	SERVICE_MODE: CONFIG_SERVICE_MODE,
	WORKER_TYPE: CONFIG_WORKER_TYPE?.trim() || undefined,

	LOG_LEVEL: CONFIG_LOG_LEVEL,
	DB_HOST: CONFIG_DB_HOST,
	DB_PORT: CONFIG_DB_PORT,
	DB_USER: CONFIG_DB_USER,
	DB_PASSWORD: CONFIG_DB_PASSWORD,
	DB_NAME: CONFIG_DB_NAME,
	DB_MAX_CONNECTIONS: CONFIG_DB_MAX_CONNECTIONS,
	CRYPTO_SECRET_KEY: CONFIG_CRYPTO_SECRET_KEY,

	CASE_BASE_URL: CONFIG_CASE_BASE_URL,
	SCORE_BASE_URL: CONFIG_MANUAL_SCORE_BASE_URL,
	AUTH_BASE_URL: CONFIG_AUTH_BASE_URL,
	ELECTRONIC_CONSENT_BASE_URL: CONFIG_ELECTRONIC_CONSENT_BASE_URL,
	WAREHOUSE_BASE_URL: CONFIG_WAREHOUSE_BASE_URL,

	KAFKA_GROUP_ID: CONFIG_KAFKA_GROUP_ID,
	KAFKA_BROKERS: CONFIG_KAFKA_BROKERS,
	KAFKA_SSL_ENABLED: parseBool(CONFIG_KAFKA_SSL_ENABLED, true),
	KAFKA_CLIENT_ID: CONFIG_KAFKA_CLIENT_ID,
	KAFKA_SASL_USERNAME: CONFIG_KAFKA_SASL_USERNAME,
	KAFKA_SASL_PASSWORD: CONFIG_KAFKA_SASL_PASSWORD,
	KAFKA_DISABLE_CONSUMER: parseBool(CONFIG_KAFKA_DISABLE_CONSUMER, false),

	FRONTEND_LOCAL_BASE_URLS: CONFIG_FRONTEND_LOCAL_BASE_URLS,

	APPLICANT_FRONTEND_BASE_URL: CONFIG_APPLICANT_FRONTEND_BASE_URL,
	WORTH_ADMIN_FRONTEND_BASE_URL: CONFIG_WORTH_ADMIN_FRONTEND_BASE_URL,
	CUSTOMER_ADMIN_FRONTEND_BASE_URL: CONFIG_CUSTOMER_ADMIN_FRONTEND_BASE_URL,

	PERSONA_API_KEY: CONFIG_PERSONA_API_KEY,
	PERSONA_INQUIRY_TEMPLATE_ID: CONFIG_PERSONA_INQUIRY_TEMPLATE_ID,
	PERSONA_VERSION: CONFIG_PERSONA_VERSION,

	AWS_APP_CLIENT_ID: CONFIG_AWS_APP_CLIENT_ID,
	AWS_COGNITO_USER_POOL_ID: CONFIG_AWS_COGNITO_USER_POOL_ID,

	WORTH_ADMIN_USER_POOL_ID: CONFIG_WORTH_ADMIN_USER_POOL_ID,
	CUSTOMER_USER_POOL_ID: CONFIG_CUSTOMER_USER_POOL_ID,
	APPLICANT_USER_POOL_ID: CONFIG_APPLICANT_USER_POOL_ID,

	AWS_REGION: CONFIG_AWS_SES_REGION,
	AWS_SES_REGION: CONFIG_AWS_SES_REGION,
	AWS_ASSETS_BUCKET: CONFIG_AWS_ASSETS_BUCKET,
	AWS_INTEGRATION_BUCKET: CONFIG_AWS_INTEGRATION_BUCKET,
	AWS_CUSTOMER_UPLOAD_BUCKET: CONFIG_AWS_CUSTOMER_UPLOAD_BUCKET,
	AWS_CUSTOMER_UPLOAD_KEY_PREFIX: CONFIG_AWS_CUSTOMER_UPLOAD_KEY_PREFIX,
	AWS_COGNITO_REGION: CONFIG_AWS_COGNITO_REGION,
	AWS_ACCESS_KEY_ID: CONFIG_AWS_ACCESS_KEY_ID,
	AWS_ACCESS_KEY_SECRET: CONFIG_AWS_ACCESS_KEY_SECRET,
	AWS_DATA_ACCESS_KEY_ID: CONFIG_AWS_DATA_ACCESS_KEY_ID,
	AWS_DATA_ACCESS_KEY_SECRET: CONFIG_AWS_DATA_ACCESS_KEY_SECRET,
	AWS_KMS_KEY_ID: CONFIG_AWS_KMS_KEY_ID,

	ECONOMICS_OBSERVATION_START_DATE: CONFIG_ECONOMICS_OBSERVATION_START_DATE,
	AWS_ELECTRONIC_CONSENT_BUCKET: CONFIG_AWS_ELECTRONIC_CONSENT_BUCKET,
	AWS_WEBSITE_SCREENSHOT_BUCKET: CONFIG_AWS_WEBSITE_SCREENSHOT_BUCKET,

	APPLICANT_CLIENT_ID: CONFIG_APPLICANT_CLIENT_ID,
	WORTH_ADMIN_CLIENT_ID: CONFIG_WORTH_ADMIN_CLIENT_ID,
	CUSTOMER_CLIENT_ID: CONFIG_CUSTOMER_CLIENT_ID,

	PLAID_CLIENT_ID: CONFIG_PLAID_CLIENT_ID,
	PLAID_SECRET: CONFIG_PLAID_SECRET,
	PLAID_REDIRECT_URI: CONFIG_PLAID_REDIRECT_URI,
	PLAID_ENV: CONFIG_PLAID_ENV,
	PLAID_ASSETS_WEBHOOK_URL: CONFIG_PLAID_ASSETS_WEBHOOK_URL,
	PLAID_LINK_WEBHOOK_URL: CONFIG_PLAID_LINK_WEBHOOK_URL,
	PLAID_IDV_TEMPLATE_ID: CONFIG_PLAID_IDV_TEMPLATE_ID,

	PLAID_SANDBOX_CLIENT_ID: CONFIG_PLAID_SANDBOX_CLIENT_ID,
	PLAID_SANDBOX_SECRET: CONFIG_PLAID_SANDBOX_SECRET,
	PLAID_SANDBOX_ENV: CONFIG_PLAID_SANDBOX_ENV,
	PLAID_SANDBOX_IDV_TEMPLATE_ID: CONFIG_PLAID_SANDBOX_IDV_TEMPLATE_ID,

	QUICKBOOKS_CLIENT_ID: CONFIG_QUICKBOOKS_CLIENT_ID,
	QUICKBOOKS_SECRET: CONFIG_QUICKBOOKS_SECRET,
	QUICKBOOKS_ENVIRONMENT: CONFIG_QUICKBOOKS_ENVIRONMENT,
	QUICKBOOKS_REDIRECT_URI: CONFIG_QUICKBOOKS_REDIRECT_URI,

	TIN_LOGIN_ID: CONFIG_TIN_LOGIN_ID,
	TIN_LOGIN_PASSWORD: CONFIG_TIN_LOGIN_PASSWORD,

	TAX_STATUS_CLIENT_ID: CONFIG_TAX_STATUS_CLIENT_ID,
	TAX_STATUS_CLIENT_SECRET: CONFIG_TAX_STATUS_CLIENT_SECRET,
	TAX_STATUS_ACCESS_URL: CONFIG_TAX_STATUS_ACCESS_URL,
	TAX_STATUS_SCOPE: CONFIG_TAX_STATUS_SCOPE,
	TAX_STATUS_EUID: CONFIG_TAX_STATUS_EUID,
	TAX_STATUS_BASE_URL: CONFIG_TAX_STATUS_BASE_URL,
	TAX_STATUS_COMPANY_ID: CONFIG_TAX_STATUS_COMPANY_ID,
	TAX_STATUS_CALLBACK_URL: CONFIG_TAX_STATUS_CALLBACK_URL,
	TAX_STATUS_SUCCESS_REDIRECT_URL: CONFIG_TAX_STATUS_SUCCESS_REDIRECT_URL,

	MIDDESK_API_KEY: CONFIG_MIDDESK_API_KEY,
	MIDDESK_BASE_URL: CONFIG_MIDDESK_BASE_URL,
	MIDDESK_WEBHOOK_SECRET: CONFIG_MIDDESK_WEBHOOK_SECRET,
	MIDDESK_TIN_MOCK_TIMEOUT: CONFIG_MIDDESK_TIN_MOCK_TIMEOUT,

	RUTTER_URL: CONFIG_RUTTER_URL || "production.rutterapi.com",
	RUTTER_CLIENT_ID: CONFIG_RUTTER_CLIENT_ID || "",
	RUTTER_SECRET: CONFIG_RUTTER_SECRET || "",
	RUTTER_PUBLIC_KEY: CONFIG_RUTTER_PUBLIC_KEY || "",
	VERDATA_LENDER_ID: CONFIG_VERDATA_LENDER_ID,
	VERDATA_AUTHORIZATION_TOKEN: CONFIG_VERDATA_AUTHORIZATION_TOKEN,
	VERDATA_KEY: CONFIG_VERDATA_KEY,
	VERDATA_WEBHOOK_URL: CONFIG_VERDATA_WEBHOOK_URL,

	AWS_S3_BUCKET_URL: CONFIG_AWS_S3_BUCKET_URL,
	EQUIFAX_BASE_URL: CONFIG_EQUIFAX_BASE_URL,
	EQUIFAX_CLIENT_ID: CONFIG_EQUIFAX_CLIENT_ID,
	EQUIFAX_CLIENT_SECRET: CONFIG_EQUIFAX_CLIENT_SECRET,
	EQUIFAX_MEMBER_NUMBER: CONFIG_EQUIFAX_MEMBER_NUMBER,
	EQUIFAX_SECURITY_CODE: CONFIG_EQUIFAX_SECURITY_CODE,
	EQUIFAX_ATHENA_DB: CONFIG_EQUIFAX_ATHENA_DB,
	EQUIFAX_ATHENA_S3_OUTPUT: CONFIG_EQUIFAX_ATHENA_S3_OUTPUT,

	EQUIFAX_SANDBOX_BASE_URL: CONFIG_EQUIFAX_SANDBOX_BASE_URL,
	EQUIFAX_SANDBOX_CLIENT_ID: CONFIG_EQUIFAX_SANDBOX_CLIENT_ID,
	EQUIFAX_SANDBOX_CLIENT_SECRET: CONFIG_EQUIFAX_SANDBOX_CLIENT_SECRET,
	EQUIFAX_SANDBOX_MEMBER_NUMBER: CONFIG_EQUIFAX_SANDBOX_MEMBER_NUMBER,
	EQUIFAX_SANDBOX_SECURITY_CODE: CONFIG_EQUIFAX_SANDBOX_SECURITY_CODE,

	CRYPTO_IV: CONFIG_CRYPTO_IV,
	OPEN_AI_KEY: CONFIG_OPEN_AI_KEY,

	REDIS_URL: CONFIG_REDIS_URL,
	REDIS_HOST: CONFIG_REDIS_HOST,
	REDIS_PORT: CONFIG_REDIS_PORT,
	REDIS_USERNAME: CONFIG_REDIS_USERNAME,
	REDIS_PASSWORD: CONFIG_REDIS_PASSWORD,
	REDIS_EC_CLUSTER: parseBool(CONFIG_REDIS_EC_CLUSTER, true),
	REDIS_DISABLE_TLS: parseBool(CONFIG_REDIS_DISABLE_TLS, true),
	REDIS_DISABLE_TLS_REJECT_UNAUTHORIZED: parseBool(CONFIG_REDIS_DISABLE_TLS_REJECT_UNAUTHORIZED, true),
	REDIS_RECONNECT_MAX_WAIT: parseInt(CONFIG_REDIS_RECONNECT_MAX_WAIT),
	REDIS_KEY_PREFIX: CONFIG_REDIS_KEY_PREFIX || "",

	REDSHIFT_CLUSTER_ID: CONFIG_REDSHIFT_CLUSTER_ID,
	REDSHIFT_DATABASE: CONFIG_REDSHIFT_DATABASE,
	REDSHIFT_USER: CONFIG_REDSHIFT_USER,
	REDSHIFT_WORKGROUP_ARN: CONFIG_REDSHIFT_WORKGROUP_ARN,
	REDSHIFT_SECRET_ARN: CONFIG_REDSHIFT_SECRET_ARN,
	REDSHIFT_WORKGROUP_NAME: CONFIG_REDSHIFT_WORKGROUP_NAME,

	BULL_MQ_FETCH_SELLER_RETRY_ATTEMPTS: Number(CONFIG_BULL_MQ_FETCH_SELLER_RETRY_ATTEMPTS) || 1,
	BULL_MQ_FETCH_SELLER_REFETCH_TIME: Number(CONFIG_BULL_MQ_FETCH_SELLER_REFETCH_TIME) || 60000,
	BULL_MQ_SANDBOX_WORKER_COUNT: forceInt(CONFIG_BULL_MQ_SANDBOX_WORKER_COUNT, 5),

	GOOGLE_MAP_API_KEY: CONFIG_GOOGLE_MAP_API_KEY,

	SYNCHRONOUS_API_TIMEOUT_SECONDS: forceInt(CONFIG_SYNCHRONOUS_API_TIMEOUT_SECONDS, 60),

	CRYPTO_SECRET_KEY_V2: CONFIG_CRYPTO_SECRET_KEY_V2,
	CRYPTO_IV_V2: CONFIG_CRYPTO_IV_V2,
	FRED_API_KEY: CONFIG_FRED_API_KEY,
	GOOGLE_BUSINESS_CLIENT_ID: CONFIG_GOOGLE_BUSINESS_CLIENT_ID,
	GOOGLE_BUSINESS_CLIENT_SECRET: CONFIG_GOOGLE_BUSINESS_CLIENT_SECRET,
	GOOGLE_BUSINESS_REDIRECT_URI: CONFIG_GOOGLE_BUSINESS_REDIRECT_URI,
	LD_SDK_KEY: CONFIG_LD_SDK_KEY,
	LD_INTIALIZATION_TIMEOUT: parseInt(CONFIG_LD_INTIALIZATION_TIMEOUT),
	LD_TEST_FLAGS_FILE: CONFIG_LD_TEST_FLAGS_FILE || "",

	SERP_API_KEY: CONFIG_SERPAPI_KEY,
	NOTIFICATION_BASE_URL: CONFIG_NOTIFICATION_BASE_URL,

	USERS_NEW: CONFIG_USERS_NEW,
	CASES: CONFIG_CASES,
	BUSINESS: CONFIG_BUSINESS,
	SCORES: CONFIG_SCORES,
	NOTIFICATIONS: CONFIG_NOTIFICATIONS,
	INTEGRATIONS: CONFIG_INTEGRATIONS,
	WEBHOOKS: CONFIG_WEBHOOKS,
	REPORTS: CONFIG_REPORTS,
	DLQTOPIC: CONFIG_DLQTOPIC,
	ELECTRONIC_CONSENT: CONFIG_ELECTRONIC_CONSENT,
	FACTS_TOPIC: CONFIG_FACTS_KAFKA_TOPIC,
	WAREHOUSE_TOPIC: CONFIG_WAREHOUSE_KAFKA_TOPIC,
	ENTITY_MATCHING_REQUEST_TOPIC: CONFIG_ENTITY_MATCHING_REQUEST_KAFKA_TOPIC,

	ECONSENT_API_KEY: CONFIG_ECONSENT_API_KEY,
	MAX_CONCURRENT_QUERIES: CONFIG_MAX_CONCURRENT_QUERIES,

	GIACT_API_ENDPOINT: CONFIG_GIACT_API_ENDPOINT,
	GIACT_API_USERNAME: CONFIG_GIACT_API_USERNAME,
	GIACT_API_PASSWORD: CONFIG_GIACT_API_PASSWORD,
	GIACT_SANDBOX_API_ENDPOINT: CONFIG_GIACT_SANDBOX_API_ENDPOINT,
	GIACT_SANDBOX_API_USERNAME: CONFIG_GIACT_SANDBOX_API_USERNAME,
	GIACT_SANDBOX_API_PASSWORD: CONFIG_GIACT_SANDBOX_API_PASSWORD,
	EXPRESS_CACHE_SECONDS: forceInt(CONFIG_EXPRESS_CACHE_SECONDS, 300),

	MATCH_ENV: CONFIG_MATCH_ENV,
	MATCH_SANDBOX_URL: CONFIG_MATCH_SANDBOX_URL,
	MATCH_PRODUCTION_URL: CONFIG_MATCH_PRODUCTION_URL,
	MATCH_MTF_URL: CONFIG_MATCH_MTF_URL,

	TRULIOO_AUTH_API: CONFIG_TRULIOO_AUTH_API,
	TRULIOO_CLIENT_ID: CONFIG_TRULIOO_CLIENT_ID,
	TRULIOO_CLIENT_SECRET: CONFIG_TRULIOO_CLIENT_SECRET,
	TRULIOO_INITFLOW_API: CONFIG_TRULIOO_INITFLOW_API,
	TRULIOO_KYB_FLOWID: CONFIG_TRULIOO_KYB_FLOWID,
	TRULIOO_PSC_FLOWID: CONFIG_TRULIOO_PSC_FLOWID,
	TRULIOO_RETRIEVE_API: CONFIG_TRULIOO_RETRIEVE_API,
	TRULIOO_SUBMIT_API: CONFIG_TRULIOO_SUBMIT_API,
	TRULIOO_WEBHOOK_SECRET: CONFIG_TRULIOO_WEBHOOK_SECRET,

	KYX_BASE_URL: CONFIG_KYX_BASE_URL,
	KYX_TENANT_NAME: CONFIG_KYX_TENANT_NAME,
	KYX_CLIENT_ID: CONFIG_KYX_CLIENT_ID,
	KYX_CLIENT_SECRET: CONFIG_KYX_CLIENT_SECRET,
	KYX_ENV_MODE: CONFIG_KYX_ENV_MODE,

	STRIPE_PUBLIC_KEY: CONFIG_STRIPE_PUBLIC_KEY,
	STRIPE_SECRET_KEY: CONFIG_STRIPE_SECRET_KEY,
	STRIPE_WEBHOOK_URL: CONFIG_STRIPE_WEBHOOK_URL,

	VERDATA_CALLBACK_SECRET: CONFIG_VERDATA_CALLBACK_SECRET,
	VERDATA_SIGNATURE_MAX_AGE_SECONDS: forceInt(CONFIG_VERDATA_SIGNATURE_MAX_AGE_SECONDS, 3600)
};
