-- Rollback migration: Restore core_mcc_code table to state before this migration
-- This gracefully reverts labels back to original values and removes codes not in the original dataset
-- Foreign key relationships are preserved since we're not changing IDs

-- Update existing codes back to their original labels
UPDATE public.core_mcc_code SET label = 'Veterinary Services' WHERE code = 742;
UPDATE public.core_mcc_code SET label = 'Agricultural Co-operatives' WHERE code = 763;
UPDATE public.core_mcc_code SET label = 'Landscaping and Horticultural Services' WHERE code = 780;
UPDATE public.core_mcc_code SET label = 'Agricultural Services' WHERE code = 1111;
UPDATE public.core_mcc_code SET label = 'Fishing, Hunting, Trapping' WHERE code = 1141;
UPDATE public.core_mcc_code SET label = 'Agricultural Co-ops' WHERE code = 1151;
UPDATE public.core_mcc_code SET label = 'Crude Petroleum and Natural Gas' WHERE code = 1311;
UPDATE public.core_mcc_code SET label = 'General Contractors—Residential and Commercial' WHERE code = 1520;
UPDATE public.core_mcc_code SET label = 'Heating, Plumbing, and Air Conditioning Contractors' WHERE code = 1711;
UPDATE public.core_mcc_code SET label = 'Electrical Contractors' WHERE code = 1731;
UPDATE public.core_mcc_code SET label = 'Masonry, Stonework, Tile Setting, Plastering and Insulation Contractors' WHERE code = 1740;
UPDATE public.core_mcc_code SET label = 'Carpentry Contractors' WHERE code = 1750;
UPDATE public.core_mcc_code SET label = 'Roofing, Siding, and Sheet Metal Work Contractors' WHERE code = 1761;
UPDATE public.core_mcc_code SET label = 'Concrete Work Contractors' WHERE code = 1771;
UPDATE public.core_mcc_code SET label = 'Special Trade Contractors (Not Elsewhere Classified)' WHERE code = 1799;
UPDATE public.core_mcc_code SET label = 'Miscellaneous Publishing and Printing' WHERE code = 2741;
UPDATE public.core_mcc_code SET label = 'Commercial Printing' WHERE code = 2759;
UPDATE public.core_mcc_code SET label = 'Typesetting, Plate Making, and Related Services' WHERE code = 2791;
UPDATE public.core_mcc_code SET label = 'Specialty Cleaning, Polishing and Sanitation Preperations' WHERE code = 2842;
UPDATE public.core_mcc_code SET label = 'Petroleum Refining' WHERE code = 2911;
UPDATE public.core_mcc_code SET label = 'Airlines, Air Carriers' WHERE code = 3000;
UPDATE public.core_mcc_code SET label = 'Rubber and Plastics' WHERE code = 3061;
UPDATE public.core_mcc_code SET label = 'Leather Goods' WHERE code = 3111;
UPDATE public.core_mcc_code SET label = 'Concrete Products' WHERE code = 3272;
UPDATE public.core_mcc_code SET label = 'Primary Metals' WHERE code = 3312;
UPDATE public.core_mcc_code SET label = 'Car Rental' WHERE code = 3351;
UPDATE public.core_mcc_code SET label = 'Sheet Metal Work' WHERE code = 3444;
UPDATE public.core_mcc_code SET label = 'Hotels/Motels/Inns/Resorts' WHERE code = 3501;
UPDATE public.core_mcc_code SET label = 'Special Industry Machinery' WHERE code = 3559;
UPDATE public.core_mcc_code SET label = 'Electronic Components' WHERE code = 3679;
UPDATE public.core_mcc_code SET label = 'Electrical Equipment' WHERE code = 3695;
UPDATE public.core_mcc_code SET label = 'Motor Vehicles and Car Bodies' WHERE code = 3711;
UPDATE public.core_mcc_code SET label = 'Sporting Goods' WHERE code = 3949;
UPDATE public.core_mcc_code SET label = 'Railroads' WHERE code = 4011;
UPDATE public.core_mcc_code SET label = 'Local and Suburban Commuter Passenger Transportation, Including Ferries' WHERE code = 4111;
UPDATE public.core_mcc_code SET label = 'Passenger Railways' WHERE code = 4112;
UPDATE public.core_mcc_code SET label = 'Ambulance Services' WHERE code = 4119;
UPDATE public.core_mcc_code SET label = 'Taxicabs/Limousines' WHERE code = 4121;
UPDATE public.core_mcc_code SET label = 'Bus Lines' WHERE code = 4131;
UPDATE public.core_mcc_code SET label = 'Motor Freight Carriers and Trucking - Local and Long Distance, Moving and Storage Companies, and Local Delivery Services' WHERE code = 4214;
UPDATE public.core_mcc_code SET label = 'Courier Services—Air and Ground, and Freight Forwarders' WHERE code = 4215;
UPDATE public.core_mcc_code SET label = 'Public Warehousing and Storage—Farm Products, Refrigerated Goods, Household Goods, and Storage' WHERE code = 4225;
UPDATE public.core_mcc_code SET label = 'Cruise Lines' WHERE code = 4411;
UPDATE public.core_mcc_code SET label = 'Water Transportation' WHERE code = 4449;
UPDATE public.core_mcc_code SET label = 'Boat Rentals and Leases' WHERE code = 4457;
UPDATE public.core_mcc_code SET label = 'Marinas, Marine Service, and Supplies' WHERE code = 4468;
UPDATE public.core_mcc_code SET label = 'Airlines and Air Carriers NEC' WHERE code = 4511;
UPDATE public.core_mcc_code SET label = 'Airports, Flying Fields and Airport Terminals' WHERE code = 4582;
UPDATE public.core_mcc_code SET label = 'Pipelines' WHERE code = 4612;
UPDATE public.core_mcc_code SET label = 'Travel Agencies, Tour Operators' WHERE code = 4722;
UPDATE public.core_mcc_code SET label = 'TUI Travel - Germany' WHERE code = 4723;
UPDATE public.core_mcc_code SET label = 'Transportation Services (Not Elsewhere Classified)' WHERE code = 4789;
UPDATE public.core_mcc_code SET label = 'Telecommunication Equipment and Telephone Sales' WHERE code = 4812;
UPDATE public.core_mcc_code SET label = 'Telecommunication Services (incl. long-distance)' WHERE code = 4814;
UPDATE public.core_mcc_code SET label = 'Computer Network Services' WHERE code = 4816;
UPDATE public.core_mcc_code SET label = 'Telegraph Services' WHERE code = 4821;
UPDATE public.core_mcc_code SET label = 'Wires, Money Orders' WHERE code = 4829;
UPDATE public.core_mcc_code SET label = 'Cable, Satellite, and Other Pay Television and Radio Services' WHERE code = 4899;
UPDATE public.core_mcc_code SET label = 'Utilities' WHERE code = 4900;
UPDATE public.core_mcc_code SET label = 'Refuse, Sanitation Services' WHERE code = 4953;
UPDATE public.core_mcc_code SET label = 'Motor Vehicle Supplies and New Parts' WHERE code = 5013;
UPDATE public.core_mcc_code SET label = 'Office and Commercial Furniture' WHERE code = 5021;
UPDATE public.core_mcc_code SET label = 'Construction Materials (Not Elsewhere Classified)' WHERE code = 5039;
UPDATE public.core_mcc_code SET label = 'Photographic, Photocopy, Microfilm Equipment and Supplies' WHERE code = 5044;
UPDATE public.core_mcc_code SET label = 'Computers and Computer Peripheral Equipment and Software' WHERE code = 5045;
UPDATE public.core_mcc_code SET label = 'Commercial Equipment, Not Elsewhere Classified' WHERE code = 5046;
UPDATE public.core_mcc_code SET label = 'Medical, Dental, Ophthalmic and Hospital Equipment and Supplies' WHERE code = 5047;
UPDATE public.core_mcc_code SET label = 'Metal Service Centers and Offices' WHERE code = 5051;
UPDATE public.core_mcc_code SET label = 'Electrical Parts and Equipment' WHERE code = 5065;
UPDATE public.core_mcc_code SET label = 'Hardware, Equipment and Supplies' WHERE code = 5072;
UPDATE public.core_mcc_code SET label = 'Plumbing and Heating Equipment and Supplies' WHERE code = 5074;
UPDATE public.core_mcc_code SET label = 'Industrial Supplies (Not Elsewhere Classified)' WHERE code = 5085;
UPDATE public.core_mcc_code SET label = 'Precious Stones and Metal, Watches and Jewelry' WHERE code = 5094;
UPDATE public.core_mcc_code SET label = 'Durable Goods (Not Elsewhere Classified)' WHERE code = 5099;
UPDATE public.core_mcc_code SET label = 'Stationery, Office Supplies, Printing and Writing Paper' WHERE code = 5111;
UPDATE public.core_mcc_code SET label = 'Drugs, Drug Proprietaries, and Druggist Sundries' WHERE code = 5122;
UPDATE public.core_mcc_code SET label = 'Piece Goods, Notions, and Other Dry Goods' WHERE code = 5131;
UPDATE public.core_mcc_code SET label = 'Men''s, Women''s, and Children''s Uniforms and Commercial Clothing' WHERE code = 5137;
UPDATE public.core_mcc_code SET label = 'Commercial Footwear' WHERE code = 5139;
UPDATE public.core_mcc_code SET label = 'Chemicals and Allied Products (Not Elsewhere Classified)' WHERE code = 5169;
UPDATE public.core_mcc_code SET label = 'Petroleum and Petroleum Products' WHERE code = 5172;
UPDATE public.core_mcc_code SET label = 'Books, Periodicals and Newspapers' WHERE code = 5192;
UPDATE public.core_mcc_code SET label = 'Florists Supplies, Nursery Stock and Flowers' WHERE code = 5193;
UPDATE public.core_mcc_code SET label = 'Paints, Varnishes and Supplies' WHERE code = 5198;
UPDATE public.core_mcc_code SET label = 'Nondurable Goods (Not Elsewhere Classified)' WHERE code = 5199;
UPDATE public.core_mcc_code SET label = 'Home Supply Warehouse Stores' WHERE code = 5200;
UPDATE public.core_mcc_code SET label = 'Lumber and Building Materials Stores' WHERE code = 5211;
UPDATE public.core_mcc_code SET label = 'Glass, Paint, and Wallpaper Stores' WHERE code = 5231;
UPDATE public.core_mcc_code SET label = 'Hardware Stores' WHERE code = 5251;
UPDATE public.core_mcc_code SET label = 'Nurseries and Lawn and Garden Supply Stores' WHERE code = 5261;
UPDATE public.core_mcc_code SET label = 'Mobile Home Dealers' WHERE code = 5271;
UPDATE public.core_mcc_code SET label = 'Wholesale Clubs' WHERE code = 5300;
UPDATE public.core_mcc_code SET label = 'Discount Stores' WHERE code = 5310;
UPDATE public.core_mcc_code SET label = 'Department Stores' WHERE code = 5311;
UPDATE public.core_mcc_code SET label = 'Variety Stores' WHERE code = 5331;
UPDATE public.core_mcc_code SET label = 'Miscellaneous General Merchandise' WHERE code = 5399;
UPDATE public.core_mcc_code SET label = 'Grocery Stores, Supermarkets' WHERE code = 5411;
UPDATE public.core_mcc_code SET label = 'Freezer and Locker Meat Provisioners' WHERE code = 5422;
UPDATE public.core_mcc_code SET label = 'Candy, Nut and Confectionery Stores' WHERE code = 5441;
UPDATE public.core_mcc_code SET label = 'Dairy Products Stores' WHERE code = 5451;
UPDATE public.core_mcc_code SET label = 'Bakeries' WHERE code = 5462;
UPDATE public.core_mcc_code SET label = 'Miscellaneous Food Stores – Convenience Stores and Specialty Markets' WHERE code = 5499;
UPDATE public.core_mcc_code SET label = 'Car and Truck Dealers (New and Used) Sales, Service, Repairs, Parts and Leasing' WHERE code = 5511;
UPDATE public.core_mcc_code SET label = 'Automotive Tire Stores' WHERE code = 5532;
UPDATE public.core_mcc_code SET label = 'Automotive Parts and Accessories Stores' WHERE code = 5533;
UPDATE public.core_mcc_code SET label = 'Service Stations (With or without Ancillary Services)' WHERE code = 5541;
UPDATE public.core_mcc_code SET label = 'Boat Dealers' WHERE code = 5551;
UPDATE public.core_mcc_code SET label = 'Camper, Recreational and Utility Trailer Dealers' WHERE code = 5561;
UPDATE public.core_mcc_code SET label = 'Motorcycle Shops and Dealers' WHERE code = 5571;
UPDATE public.core_mcc_code SET label = 'Miscellaneous Automotive, Aircraft, and Farm Equipment Dealers (Not Elsewhere Classified)' WHERE code = 5599;
UPDATE public.core_mcc_code SET label = 'Men''s and Boys'' Clothing and Accessories Stores' WHERE code = 5611;
UPDATE public.core_mcc_code SET label = 'Women''s Accessory and Specialty Shops' WHERE code = 5631;
UPDATE public.core_mcc_code SET label = 'Sports and Riding Apparel Stores' WHERE code = 5655;
UPDATE public.core_mcc_code SET label = 'Shoe Stores' WHERE code = 5661;
UPDATE public.core_mcc_code SET label = 'Men''s and Women''s Clothing Stores' WHERE code = 5691;
UPDATE public.core_mcc_code SET label = 'Tailors, Seamstresses, Mending, and Alterations' WHERE code = 5697;
UPDATE public.core_mcc_code SET label = 'Wig and Toupee Stores' WHERE code = 5698;
UPDATE public.core_mcc_code SET label = 'Miscellaneous Apparel and Accessory Shops' WHERE code = 5699;
UPDATE public.core_mcc_code SET label = 'Furniture, Home Furnishings and Equipment Stores, Except Appliances' WHERE code = 5712;
UPDATE public.core_mcc_code SET label = 'Floor Covering Stores' WHERE code = 5713;
UPDATE public.core_mcc_code SET label = 'Drapery, Window Covering, and Upholstery Stores' WHERE code = 5714;
UPDATE public.core_mcc_code SET label = 'Miscellaneous Home Furnishing Specialty Stores' WHERE code = 5719;
UPDATE public.core_mcc_code SET label = 'Household Appliance Stores' WHERE code = 5722;
UPDATE public.core_mcc_code SET label = 'Music Stores – Musical Instruments, Pianos, and Sheet Music' WHERE code = 5733;
UPDATE public.core_mcc_code SET label = 'Computer Software Stores' WHERE code = 5734;
UPDATE public.core_mcc_code SET label = 'Caterers' WHERE code = 5811;
UPDATE public.core_mcc_code SET label = 'Eating Places & Restaurants' WHERE code = 5812;
UPDATE public.core_mcc_code SET label = 'Drinking Places (Alcoholic Beverages)—Bars, Taverns, Nightclubs, Cocktail Lounges, and Discotheques' WHERE code = 5813;
UPDATE public.core_mcc_code SET label = 'Fast Food Restaurants' WHERE code = 5814;
UPDATE public.core_mcc_code SET label = 'Digital Goods Media – Books, Movies, Digital artwork/images, Music' WHERE code = 5815;
UPDATE public.core_mcc_code SET label = 'Drug Stores and Pharmacies' WHERE code = 5912;
UPDATE public.core_mcc_code SET label = 'Package Stores – Beer, Wine, and Liquor' WHERE code = 5921;
UPDATE public.core_mcc_code SET label = 'Used Merchandise and Secondhand Stores' WHERE code = 5931;
UPDATE public.core_mcc_code SET label = 'Wrecking and Salvage Yards' WHERE code = 5935;
UPDATE public.core_mcc_code SET label = 'Bicycle Shops—Sales and Service' WHERE code = 5940;
UPDATE public.core_mcc_code SET label = 'Sporting Goods Stores' WHERE code = 5941;
UPDATE public.core_mcc_code SET label = 'Book Stores' WHERE code = 5942;
UPDATE public.core_mcc_code SET label = 'Stationery Stores, Office, and School Supply Stores' WHERE code = 5943;
UPDATE public.core_mcc_code SET label = 'Jewelry Stores, Watches, Clocks and Silverware Stores' WHERE code = 5944;
UPDATE public.core_mcc_code SET label = 'Hobby, Toy, and Game Stores' WHERE code = 5945;
UPDATE public.core_mcc_code SET label = 'Gift, Card, Novelty, and Souvenir Shops' WHERE code = 5947;
UPDATE public.core_mcc_code SET label = 'Luggage and Leather Goods Stores' WHERE code = 5948;
UPDATE public.core_mcc_code SET label = 'Sewing, Needlework, Fabric and Piece Goods Stores' WHERE code = 5949;
UPDATE public.core_mcc_code SET label = 'Glassware/Crystal Stores' WHERE code = 5950;
UPDATE public.core_mcc_code SET label = 'Mail Order Houses' WHERE code = 5961;
UPDATE public.core_mcc_code SET label = 'Door-To-Door Sales' WHERE code = 5963;
UPDATE public.core_mcc_code SET label = 'Direct Marketing - Other Services' WHERE code = 5969;
UPDATE public.core_mcc_code SET label = 'Art Dealers and Galleries' WHERE code = 5971;
UPDATE public.core_mcc_code SET label = 'Cosmetic Stores' WHERE code = 5977;
UPDATE public.core_mcc_code SET label = 'Typewriter Stores—Sales, Rentals, and Service' WHERE code = 5978;
UPDATE public.core_mcc_code SET label = 'Fuel Dealers (Non-Automotive Fuel, e.g., heating oil, propane)' WHERE code = 5983;
UPDATE public.core_mcc_code SET label = 'Florists' WHERE code = 5992;
UPDATE public.core_mcc_code SET label = 'Cigar Stores and Stands' WHERE code = 5993;
UPDATE public.core_mcc_code SET label = 'Pet Shops, Pet Foods and Supplies Stores' WHERE code = 5995;
UPDATE public.core_mcc_code SET label = 'Miscellaneous and Specialty Retail Shops' WHERE code = 5999;
UPDATE public.core_mcc_code SET label = 'Financial Institutions—Manual Cash Disbursements' WHERE code = 6010;
UPDATE public.core_mcc_code SET label = 'Financial Institutions' WHERE code = 6011;
UPDATE public.core_mcc_code SET label = 'Financial Institutions—Merchandise and Services' WHERE code = 6012;
UPDATE public.core_mcc_code SET label = 'Non-Financial Institutions—Foreign Currency, Money Orders (Not Wire Transfer), Stored Value Card/Load, and Travelers Cheques' WHERE code = 6051;
UPDATE public.core_mcc_code SET label = 'Security Brokers/Dealers' WHERE code = 6211;
UPDATE public.core_mcc_code SET label = 'Insurance Sales, Underwriting, and Premiums' WHERE code = 6300;
UPDATE public.core_mcc_code SET label = 'Real Estate Agents and Managers' WHERE code = 6513;
UPDATE public.core_mcc_code SET label = 'Lodging—Hotels, Motels, Resorts, Central Reservation Services (Not Elsewhere Classified)' WHERE code = 7011;
UPDATE public.core_mcc_code SET label = 'Sporting and Recreational Camps' WHERE code = 7032;
UPDATE public.core_mcc_code SET label = 'Trailer Parks and Campgrounds' WHERE code = 7033;
UPDATE public.core_mcc_code SET label = 'Laundry, Cleaning, and Garment Services' WHERE code = 7210;
UPDATE public.core_mcc_code SET label = 'Laundries - Family and Commercial' WHERE code = 7211;
UPDATE public.core_mcc_code SET label = 'Dry Cleaners' WHERE code = 7216;
UPDATE public.core_mcc_code SET label = 'Carpet and Upholstery Cleaning' WHERE code = 7217;
UPDATE public.core_mcc_code SET label = 'Photographic Studios' WHERE code = 7221;
UPDATE public.core_mcc_code SET label = 'Barber and Beauty Shops' WHERE code = 7230;
UPDATE public.core_mcc_code SET label = 'Shoe Repair Shops, Shoe Shine Parlors, and Hat Cleaning Shops' WHERE code = 7251;
UPDATE public.core_mcc_code SET label = 'Funeral Services and Crematories' WHERE code = 7261;
UPDATE public.core_mcc_code SET label = 'Tax Preparation Services' WHERE code = 7276;
UPDATE public.core_mcc_code SET label = 'Counseling Services—Debt, Marriage, and Personal' WHERE code = 7277;
UPDATE public.core_mcc_code SET label = 'Health and Beauty Spas' WHERE code = 7298;
UPDATE public.core_mcc_code SET label = 'Miscellaneous Personal Services (Not Elsewhere Classified)' WHERE code = 7299;
UPDATE public.core_mcc_code SET label = 'Advertising Services' WHERE code = 7311;
UPDATE public.core_mcc_code SET label = 'Credit Reporting Agencies' WHERE code = 7321;
UPDATE public.core_mcc_code SET label = 'Commercial Photography, Art and Graphics' WHERE code = 7333;
UPDATE public.core_mcc_code SET label = 'Quick Copy, Reproduction and Blueprinting Services' WHERE code = 7338;
UPDATE public.core_mcc_code SET label = 'Stenographic and Secretarial Support' WHERE code = 7339;
UPDATE public.core_mcc_code SET label = 'Exterminating and Disinfecting Services' WHERE code = 7342;
UPDATE public.core_mcc_code SET label = 'Cleaning, Maintenance, Janitorial Services' WHERE code = 7349;
UPDATE public.core_mcc_code SET label = 'Employment Agencies and Temporary Help Services' WHERE code = 7361;
UPDATE public.core_mcc_code SET label = 'Computer Programming, Data Processing, and Integrated Systems Design Services' WHERE code = 7372;
UPDATE public.core_mcc_code SET label = 'Data Processing Services' WHERE code = 7374;
UPDATE public.core_mcc_code SET label = 'Management, Consulting, and Public Relations Services' WHERE code = 7392;
UPDATE public.core_mcc_code SET label = 'Detective Agencies, Protective Services, and Security Services, including Armored Cars, and Guard Dogs' WHERE code = 7393;
UPDATE public.core_mcc_code SET label = 'Equipment, Tool, Furniture, and Appliance Rental and Leasing' WHERE code = 7394;
UPDATE public.core_mcc_code SET label = 'Photofinishing Laboratories and Photo Developing' WHERE code = 7395;
UPDATE public.core_mcc_code SET label = 'Business Services (Not Elsewhere Classified)' WHERE code = 7399;
UPDATE public.core_mcc_code SET label = 'Truck and Utility Trailer Rentals' WHERE code = 7513;
UPDATE public.core_mcc_code SET label = 'Automotive Top & Body Shops' WHERE code = 7531;
UPDATE public.core_mcc_code SET label = 'Tire Retreading and Repair Shops' WHERE code = 7534;
UPDATE public.core_mcc_code SET label = 'Automotive Paint Shops' WHERE code = 7535;
UPDATE public.core_mcc_code SET label = 'Automotive Service Shops' WHERE code = 7538;
UPDATE public.core_mcc_code SET label = 'Car Washes' WHERE code = 7542;
UPDATE public.core_mcc_code SET label = 'Towing Services' WHERE code = 7549;
UPDATE public.core_mcc_code SET label = 'Air Conditioning and Refrigeration Repair Shops' WHERE code = 7623;
UPDATE public.core_mcc_code SET label = 'Miscellaneous Repair Shops and Related Services' WHERE code = 7699;
UPDATE public.core_mcc_code SET label = 'Motion Picture and Video Tape Production and Distribution' WHERE code = 7829;
UPDATE public.core_mcc_code SET label = 'Motion Picture Theaters' WHERE code = 7832;
UPDATE public.core_mcc_code SET label = 'Dance Halls, Studios and Schools' WHERE code = 7911;
UPDATE public.core_mcc_code SET label = 'Theatrical Producers (Except Motion Pictures) and Ticket Agencies' WHERE code = 7922;
UPDATE public.core_mcc_code SET label = 'Bands, Orchestras, and Miscellaneous Entertainers (Not Elsewhere Classified)' WHERE code = 7929;
UPDATE public.core_mcc_code SET label = 'Bowling Alleys' WHERE code = 7933;
UPDATE public.core_mcc_code SET label = 'Commercial Sports, Professional Sports Clubs, Athletic Fields, and Sports Promoters' WHERE code = 7941;
UPDATE public.core_mcc_code SET label = 'Tourist Attractions and Exhibits' WHERE code = 7991;
UPDATE public.core_mcc_code SET label = 'Public Golf Courses' WHERE code = 7992;
UPDATE public.core_mcc_code SET label = 'Video Amusement Game Supplies' WHERE code = 7993;
UPDATE public.core_mcc_code SET label = 'Video Game Arcades/Establishments' WHERE code = 7994;
UPDATE public.core_mcc_code SET label = 'Betting, including Lottery Tickets, Casino Gaming Chips, Off-Track Betting, and Wagers at Race Tracks' WHERE code = 7995;
UPDATE public.core_mcc_code SET label = 'Amusement Parks, Circuses, Carnivals, and Fortune Tellers' WHERE code = 7996;
UPDATE public.core_mcc_code SET label = 'Recreation Services (Not Elsewhere Classified)' WHERE code = 7999;
UPDATE public.core_mcc_code SET label = 'Doctors and Physicians (Not Elsewhere Classified)' WHERE code = 8011;
UPDATE public.core_mcc_code SET label = 'Dentists and Orthodontists' WHERE code = 8021;
UPDATE public.core_mcc_code SET label = 'Chiropractors' WHERE code = 8041;
UPDATE public.core_mcc_code SET label = 'Optometrists and Ophthalmologists' WHERE code = 8042;
UPDATE public.core_mcc_code SET label = 'Opticians, Optical Goods, and Eyeglasses' WHERE code = 8043;
UPDATE public.core_mcc_code SET label = 'Podiatrists and Chiropodists' WHERE code = 8049;
UPDATE public.core_mcc_code SET label = 'Nursing and Personal Care Facilities' WHERE code = 8050;
UPDATE public.core_mcc_code SET label = 'Hospitals' WHERE code = 8062;
UPDATE public.core_mcc_code SET label = 'Medical and Dental Laboratories' WHERE code = 8071;
UPDATE public.core_mcc_code SET label = 'Medical Services and Health Practitioners (Not Elsewhere Classified)' WHERE code = 8099;
UPDATE public.core_mcc_code SET label = 'Legal Services and Attorneys' WHERE code = 8111;
UPDATE public.core_mcc_code SET label = 'Elementary and Secondary Schools' WHERE code = 8211;
UPDATE public.core_mcc_code SET label = 'Colleges, Universities, Professional Schools, and Junior Colleges' WHERE code = 8220;
UPDATE public.core_mcc_code SET label = 'Correspondence Schools' WHERE code = 8241;
UPDATE public.core_mcc_code SET label = 'Vocational and Trade Schools' WHERE code = 8249;
UPDATE public.core_mcc_code SET label = 'Schools and Educational Services (Not Elsewhere Classified)' WHERE code = 8299;
UPDATE public.core_mcc_code SET label = 'Child Care Services' WHERE code = 8351;
UPDATE public.core_mcc_code SET label = 'Charitable and Social Service Organizations' WHERE code = 8398;
UPDATE public.core_mcc_code SET label = 'Museums and Art Galleries' WHERE code = 8412;
UPDATE public.core_mcc_code SET label = 'Civic, Social, Fraternal Associations' WHERE code = 8641;
UPDATE public.core_mcc_code SET label = 'Political Organizations' WHERE code = 8651;
UPDATE public.core_mcc_code SET label = 'Religious Organizations' WHERE code = 8661;
UPDATE public.core_mcc_code SET label = 'Membership Organizations (Not Elsewhere Classified)' WHERE code = 8699;
UPDATE public.core_mcc_code SET label = 'Testing Laboratories (Non-Medical Testing)' WHERE code = 8734;
UPDATE public.core_mcc_code SET label = 'Architectural, Engineering, and Surveying Services' WHERE code = 8911;
UPDATE public.core_mcc_code SET label = 'Accounting, Auditing, and Bookkeeping Services' WHERE code = 8931;
UPDATE public.core_mcc_code SET label = 'Professional Services (Not Elsewhere Classified)' WHERE code = 8999;
UPDATE public.core_mcc_code SET label = 'Court Costs, Including Alimony and Child Support' WHERE code = 9211;
UPDATE public.core_mcc_code SET label = 'Legal and Court Services' WHERE code = 9222;
UPDATE public.core_mcc_code SET label = 'Tax Payments' WHERE code = 9311;
UPDATE public.core_mcc_code SET label = 'Government Services (Not Elsewhere Classified)' WHERE code = 9399;
UPDATE public.core_mcc_code SET label = 'Postal Services - Government Only' WHERE code = 9402;
UPDATE public.core_mcc_code SET label = 'U.S. Federal Government Agencies or Departments' WHERE code = 9405;
UPDATE public.core_mcc_code SET label = 'Environmental Quality Programs' WHERE code = 9511;
UPDATE public.core_mcc_code SET label = 'Housing Programs' WHERE code = 9532;
UPDATE public.core_mcc_code SET label = 'Administrative Services' WHERE code = 9611;
UPDATE public.core_mcc_code SET label = 'Space and Technology Research' WHERE code = 9711;
UPDATE public.core_mcc_code SET label = 'Undefined / Unknown' WHERE code = 9999;

-- Delete codes that were added by this migration but are not in the original dataset
DELETE FROM public.core_mcc_code 
WHERE code NOT IN (
    742, 763, 780, 1111, 1141, 1151, 1311, 1520, 1622, 1711, 1731, 1740, 1750, 1761, 1771, 1799,
    2011, 2086, 2251, 2253, 2399, 2421, 2511, 2621, 2741, 2759, 2791, 2842, 2911, 3000, 3061, 3111,
    3272, 3312, 3351, 3444, 3501, 3559, 3679, 3695, 3711, 3949, 4011, 4111, 4112, 4119, 4121, 4131,
    4214, 4215, 4225, 4411, 4449, 4457, 4468, 4511, 4582, 4612, 4722, 4723, 4789, 4812, 4814, 4816,
    4821, 4829, 4899, 4900, 4953, 5013, 5021, 5039, 5044, 5045, 5046, 5047, 5051, 5065, 5072, 5074,
    5085, 5094, 5099, 5111, 5122, 5131, 5137, 5139, 5169, 5172, 5192, 5193, 5198, 5199, 5200, 5211,
    5231, 5251, 5261, 5271, 5300, 5310, 5311, 5331, 5399, 5411, 5422, 5441, 5451, 5462, 5499, 5511,
    5532, 5533, 5541, 5551, 5561, 5571, 5599, 5611, 5631, 5655, 5661, 5691, 5697, 5698, 5699, 5712,
    5713, 5714, 5719, 5722, 5733, 5734, 5811, 5812, 5813, 5814, 5815, 5912, 5921, 5931, 5935, 5940,
    5941, 5942, 5943, 5944, 5945, 5947, 5948, 5949, 5950, 5961, 5963, 5969, 5971, 5977, 5978, 5983,
    5992, 5993, 5995, 5999, 6010, 6011, 6012, 6051, 6211, 6300, 6513, 7011, 7032, 7033, 7210, 7211,
    7216, 7217, 7221, 7230, 7251, 7261, 7276, 7277, 7298, 7299, 7311, 7321, 7333, 7338, 7339, 7342,
    7349, 7361, 7372, 7374, 7392, 7393, 7394, 7395, 7399, 7513, 7531, 7534, 7535, 7538, 7542, 7549,
    7623, 7699, 7829, 7832, 7911, 7922, 7929, 7933, 7941, 7991, 7992, 7993, 7994, 7995, 7996, 7999,
    8011, 8021, 8041, 8042, 8043, 8049, 8050, 8062, 8071, 8099, 8111, 8211, 8220, 8241, 8249, 8299,
    8351, 8398, 8412, 8641, 8651, 8661, 8699, 8734, 8911, 8931, 8999, 9211, 9222, 9311, 9399, 9402,
    9405, 9511, 9532, 9611, 9711, 9999
);
