create table if not exists integration_data.economics_data (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY NOT NULL,
	date_time date UNIQUE,
	gdp_pch INT NULL,
	gdp_pc1 INT NULL,
	t10y2y INT NULL,
	t10y2y_chg INT NULL,
	t10y2y_ch1 INT NULL,
	t10y INT NULL,
	t10y_chg INT NULL,
	t10y_ch1 INT NULL,
	t2y INT NULL,
	t2y_chg INT NULL,
	t2y_ch1 INT NULL,
	brent_pch INT NULL,
	brent_pc1 INT NULL,
	wtispot_pch INT NULL,
	wtispot_pc1 INT NULL,
	vix INT NULL,
	vix_chg INT NULL,
	vix_ch1 INT NULL,
	csentiment INT NULL,
	csentiment_chg_x INT NULL,
	csentiment_chg_y INT NULL,
	dolindx INT NULL,
	dolindx_chg INT NULL,
	dolindx_ch1 INT NULL,
	unemp INT NULL,
	unemp_chg INT NULL,
	unemp_ch1 INT NULL,
	cpi INT NULL,
	cpi_chg INT NULL,
	cpi_ch1 INT NULL,
	cpicore INT NULL,
	cpicore_chg INT NULL,
	cpicore_ch1 INT NULL,
	ccdelinq INT NULL,
	ccdelinq_chg INT NULL,
	ccdelinq_ch1 INT NULL,
	cloandelinq INT NULL,
	cloandelinq_chg INT NULL,
	cloandelinq_ch1 INT NULL,
	busloandelinq INT NULL,
	busloandelinq_chg INT NULL,
	busloandelinq_ch1 INT NULL,
	wagegrowth INT NULL,
	wagegrowth_chg INT NULL,
	usdeur INT NULL,
	usdeur_chg INT NULL,
	usdeur_ch1 INT NULL,
	usdpeso INT NULL,
	usdpeso_chg INT NULL,
	usdpeso_ch1 INT NULL,
	usdcan INT NULL,
	usdcan_chg INT NULL,
	usdcan_ch1 INT NULL,
	ppi_chg INT NULL,
	ppi_ch1 INT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
	CONSTRAINT unique_date_time UNIQUE (date_time)
);