CREATE OR REPLACE FUNCTION integration_data.extended_attributes (
        p_business_id uuid -- ← pass the business_id you need
    ) RETURNS TABLE (
        -- ===== Core identifiers =====
        business_id uuid,
        requested_at timestamptz,
        -- ===== Basic business information =====
        business_name text,
        address text,
        city text,
        state text,
        zip_code text,
        legal_ultimate_number text,
        -- ===== Company details =====
        employees integer,
        corporate_amount bigint,
        corporate_amount_type text,
        corporate_amount_precision text,
        max_year_established text,
        min_year_established text,
        -- ===== NAICS classification =====
        primary_naics_code text,
        primary_naics_sector text,
        primary_naics_subsector text,
        primary_naics_industry_group text,
        primary_naics_industry text,
        secondary_naics_1 text,
        secondary_naics_1_sector text,
        secondary_naics_1_subsector text,
        secondary_naics_1_industry_group text,
        secondary_naics_1_industry text,
        secondary_naics_2 text,
        secondary_naics_2_sector text,
        secondary_naics_2_subsector text,
        secondary_naics_2_industry_group text,
        secondary_naics_2_industry text,
        secondary_naics_3 text,
        secondary_naics_3_sector text,
        secondary_naics_3_subsector text,
        secondary_naics_3_industry_group text,
        secondary_naics_3_industry text,
        secondary_naics_4 text,
        secondary_naics_4_sector text,
        secondary_naics_4_subsector text,
        secondary_naics_4_industry_group text,
        secondary_naics_4_industry text,
        -- ===== SIC codes =====
        primary_sic_code text,
        secondary_sic_1 text,
        secondary_sic_2 text,
        secondary_sic_3 text,
        secondary_sic_4 text,
        -- ===== Geographic information =====
        latitude_avg numeric(10, 6),
        longitude_avg numeric(10, 6),
        latitude_array text,
        longitude_array text,
        -- ===== Location counts =====
        location_count integer,
        location_active_count integer,
        location_inactive_count integer,
        location_inactive_dt_count integer,
        location_inactive_old_count integer,
        location_business_count integer,
        location_residential_count integer,
        location_small_count integer,
        location_large_count integer,
        location_soho_count integer,
        location_unknown_size_count integer,
        -- ===== Entity-type counts =====
        location_corp_count integer,
        location_ccorp_count integer,
        location_scorp_count integer,
        location_llc_count integer,
        location_llp_count integer,
        location_lllp_count integer,
        location_limited_partner_count integer,
        location_partner_count integer,
        location_individual_sole_count integer,
        location_trust_count integer,
        location_mutual_count integer,
        location_nonprofit_ind_count integer,
        location_nonprofit_stat_count integer,
        location_gov_count integer,
        location_fedgov_count integer,
        location_edu_count integer,
        location_other_count integer,
        location_ids text,
        -- ===== Credit scores =====
        market_total_score_avg integer,
        market_total_score_max integer,
        market_total_score_min integer,
        market_total_score_array text,
        market_tel_score_avg integer,
        market_tel_score_max integer,
        market_tel_score_min integer,
        market_tel_score_array text,
        credit_score_avg integer,
        credit_score_max integer,
        credit_score_min integer,
        credit_score_array text,
        credit_perc_avg integer,
        credit_perc_max integer,
        credit_perc_min integer,
        credit_perc_array text,
        -- ===== Failure rates =====
        fail_rate_avg numeric(5, 2),
        fail_rate_array text,
        -- ===== Public records =====
        bankruptcy_count integer,
        bankruptcy_most_recent_age integer,
        judgment_count integer,
        judgment_most_recent_age integer,
        lien_count integer,
        lien_most_recent_age integer,
        bankrupt_count_credcls integer,
        bankrupt_count_failrt integer,
        bankrupt_count_field integer,
        -- ===== Equifax BMA 3-month non-financial trades =====
        trade_3m_nfin_trade_count integer,
        trade_3m_nfin_trade_total_balance bigint,
        trade_3m_nfin_worst_payment_status text,
        trade_3m_nfin_past_due_amount bigint,
        trade_3m_nfin_high_credit_limit bigint,
        trade_3m_nfin_percent_satisfactory_accounts integer
    ) AS $$
SELECT r.business_id,
    r.requested_at,
    -- ===== BASIC BUSINESS INFORMATION =====
    r.response->>'legultnameall',
    r.response->>'address_string',
    r.response->>'legultcityall',
    r.response->>'legultstateall',
    r.response->>'efx_legultzipcodeall',
    r.response->>'legultnumall',
    -- ===== COMPANY DETAILS =====
    (r.response->>'corpemployees')::integer,
    (r.response->>'corpamount')::bigint,
    r.response->>'corpamount_type',
    r.response->>'corpamount_prec',
    r.response->>'max_year_est',
    r.response->>'min_year_est',
    -- ===== NAICS CLASSIFICATION =====
    r.response->>'primnaicscode',
    r.response->>'primnaics_sector',
    r.response->>'primnaics_subsector',
    r.response->>'primnaics_industry_group',
    r.response->>'primnaics_industry',
    r.response->>'secnaics1',
    r.response->>'secnaics1_sector',
    r.response->>'secnaics1_subsector',
    r.response->>'secnaics1_industry_group',
    r.response->>'secnaics1_industry',
    r.response->>'secnaics2',
    r.response->>'secnaics2_sector',
    r.response->>'secnaics2_subsector',
    r.response->>'secnaics2_industry_group',
    r.response->>'secnaics2_industry',
    r.response->>'secnaics3',
    r.response->>'secnaics3_sector',
    r.response->>'secnaics3_subsector',
    r.response->>'secnaics3_industry_group',
    r.response->>'secnaics3_industry',
    r.response->>'secnaics4',
    r.response->>'secnaics4_sector',
    r.response->>'secnaics4_subsector',
    r.response->>'secnaics4_industry_group',
    r.response->>'secnaics4_industry',
    -- ===== SIC CODES =====
    r.response->>'primsic',
    r.response->>'secsic1',
    r.response->>'secsic2',
    r.response->>'secsic3',
    r.response->>'secsic4',
    -- ===== GEOGRAPHIC INFORMATION =====
    (r.response->>'location_latitude_avg')::numeric(10, 6),
    (r.response->>'location_longitude_avg')::numeric(10, 6),
    r.response->>'lat_array',
    r.response->>'lon_array',
    -- ===== LOCATION COUNTS =====
    (r.response->>'location_cnt')::integer,
    (r.response->>'location_active_cnt')::integer,
    (r.response->>'location_inactive_cnt')::integer,
    (r.response->>'location_inactivedt_cnt')::integer,
    (r.response->>'location_inactiveold_cnt')::integer,
    (r.response->>'location_biz_cnt')::integer,
    (r.response->>'location_res_cnt')::integer,
    (r.response->>'location_small_cnt')::integer,
    (r.response->>'location_large_cnt')::integer,
    (r.response->>'location_soho_cnt')::integer,
    (r.response->>'location_unknown_size_cnt')::integer,
    -- ===== ENTITY TYPE COUNTS =====
    (r.response->>'location_corp_cnt')::integer,
    (r.response->>'location_ccorp_cnt')::integer,
    (r.response->>'location_scorp_cnt')::integer,
    (r.response->>'location_llc_cnt')::integer,
    (r.response->>'location_llp_cnt')::integer,
    (r.response->>'location_lllp_cnt')::integer,
    (r.response->>'location_limpartner_cnt')::integer,
    (r.response->>'location_partner_cnt')::integer,
    (r.response->>'location_indsole_cnt')::integer,
    (r.response->>'location_trust_cnt')::integer,
    (r.response->>'location_mutual_cnt')::integer,
    (r.response->>'location_nonprofitind_cnt')::integer,
    (r.response->>'location_nonprofitstat_cnt')::integer,
    (r.response->>'location_gov_cnt')::integer,
    (r.response->>'location_fedgov_cnt')::integer,
    (r.response->>'location_edu_cnt')::integer,
    (r.response->>'location_other_cnt')::integer,
    r.response->>'location_ids',
    -- ===== CREDIT SCORES =====
    (r.response->>'mkt_totalscore_avg')::integer,
    (r.response->>'mkt_totalscore_max')::integer,
    (r.response->>'mkt_totalscore_min')::integer,
    r.response->>'mkt_totalscore_array',
    (r.response->>'mkt_telscore_avg')::integer,
    (r.response->>'mkt_telscore_max')::integer,
    (r.response->>'mkt_telscore_min')::integer,
    r.response->>'mkt_telscore_array',
    (r.response->>'creditscore_avg')::integer,
    (r.response->>'creditscore_max')::integer,
    (r.response->>'creditscore_min')::integer,
    r.response->>'creditscore_array',
    (r.response->>'creditperc_avg')::integer,
    (r.response->>'creditperc_max')::integer,
    (r.response->>'creditperc_min')::integer,
    r.response->>'creditperc_array',
    -- ===== FAILURE RATES =====
    (r.response->>'failrate_avg')::numeric(5, 2),
    r.response->>'failrate_array',
    -- ===== PUBLIC RECORDS =====
    (r.response->>'bankruptcy_count')::integer,
    (r.response->>'bankruptcy_most_recent_age')::integer,
    (r.response->>'judgement_count')::integer,
    (r.response->>'judgement_most_recent_age')::integer,
    (r.response->>'lien_count')::integer,
    (r.response->>'lien_most_recent_age')::integer,
    (r.response->>'bankrupt_cnt_credcls')::integer,
    (r.response->>'bankrupt_cnt_failrt')::integer,
    (r.response->>'bankrupt_cnt_field')::integer,
    -- ===== EQUIFAX BMA 3M - NON-FINANCIAL TRADE RECORDS =====
    (r.response->>'efxbma_3m_nfin_tr_count')::integer,
    (r.response->>'efxbma_3m_nfin_tr_total_bal')::bigint,
    r.response->>'efxbma_3m_nfin_worst_payment_status',
    (r.response->>'efxbma_3m_nfin_past_due_amount')::bigint,
    (r.response->>'efxbma_3m_nfin_high_credit_lim')::bigint,
    (
        r.response->>'efxbma_3m_nfin_per_satisfactory_acc'
    )::integer
FROM integration_data.request_response r
WHERE r.platform_id = 17 -- constant per original query
    AND r.business_id = p_business_id
    AND r.request_type = 'fetch_public_records'
    AND r.response->'efx_id' IS NOT NULL
ORDER BY r.requested_at DESC
LIMIT 1;
$$ LANGUAGE sql STABLE;