export const ERROR_CODES = {
	UNAUTHENTICATED: "UNAUTHENTICATED",
	UNAUTHORIZED: "UNAUTHORIZED",
	NOT_FOUND: "NOT_FOUND",
	NOT_ALLOWED: "NOT_ALLOWED",
	INVALID: "INVALID",
	DUPLICATE: "DUPLICATE",
	UNKNOWN_ERROR: "UNKNOWN_ERROR",
	DEPRECATED: "DEPRECATED",
	MAINTENANCE: "MAINTENANCE",
	VALIDATION_ERROR: "VALIDATION_ERROR"
} as const;
export type ErrorCode = keyof typeof ERROR_CODES;
