DELETE FROM score_category_factors WHERE code IN ('BUSINESS_OPERATIONS_AI_PLACEHOLDER', 'COMPANY_PROFILE_AI_PLACEHOLDER', 'FINANCIAL_TRENDS_AI_PLACEHOLDER', 'LIQUIDITY_AI_PLACEHOLDER');

DELETE FROM score_categories WHERE code IN ('BUSINESS_OPERATIONS', 'COMPANY_PROFILE', 'FINANCIAL_TRENDS', 'LIQUIDITY');
