import { logger } from "#helpers/logger";
import { isEmpty } from "#utils";
import { ConnectionWithTasks, getConnectionsAndTasks, processTasksForConnection } from "./lib";
import { RerunTrackingManager } from "#core/rerunTracking";
import { getPlatformCodesByChangedFacts } from "./lib";
import type { FactName } from "#lib/facts/types";
import type { ProcessTasksForConnectionResult } from "./lib/types";
import type { TaskCode } from "#constants";
import type { UUID } from "crypto";

interface RerunIntegrationsParams {
	businessID: string;
}

interface RerunIntegrationsBody {
	platform_codes?: string[];
	category_codes?: string[];
	task_codes?: TaskCode[];
	/** Automatically determine which platforms to rerun based on changed facts */
	fact_names?: FactName[];
	/**
	 * Optional metadata override to pass to each adapter process function.
	 * By default, the metadata is generated by the adapters -- however, you can provide your own metadata via this field.
	 * WARNING: The same metadata will be passed to *all* process functions, so you must ensure it is compatible with all adapters.
	 */
	metadata?: Record<string, any>;
}

/**
 * Reruns integrations based on the provided filters.
 * Uses adapters to generate platform-specific metadata.
 * Creates a MANUAL_REFRESH score trigger and initializes completion tracking.
 */
export const rerunIntegrations = async (params: RerunIntegrationsParams, body: RerunIntegrationsBody) => {
	const { businessID } = params;
	const { category_codes = [], task_codes = [], fact_names = [] } = body;
	const metadata = typeof body.metadata === "object" ? body.metadata : undefined;
	const platformCodes: Set<string> = Array.isArray(body.platform_codes) ? new Set(body.platform_codes) : new Set();

	logger.info(
		`Rerunning integrations for business ${businessID} - platform_codes: ${JSON.stringify(platformCodes)}, category_codes: ${JSON.stringify(category_codes)}, task_codes: ${JSON.stringify(task_codes)}, fact_names: ${JSON.stringify(fact_names)}`
	);

	/** If facts provided, determine affected platforms */
	if (fact_names && fact_names.length > 0) {
		const affectedPlatformCodes = getPlatformCodesByChangedFacts(fact_names);
		affectedPlatformCodes.forEach(code => platformCodes.add(code));

		logger.info(`Facts changed: ${JSON.stringify(fact_names)}, affected platforms: ${JSON.stringify(platformCodes)}`);
	}

	/** Get connections and their associated tasks based on filters */
	let connectionsWithTasks: ConnectionWithTasks[] = [];

	/** Only get connections and tasks if at least one filter is provided */
	if (!isEmpty(platformCodes) || !isEmpty(category_codes) || !isEmpty(task_codes)) {
		connectionsWithTasks = await getConnectionsAndTasks(
			businessID,
			Array.from(platformCodes),
			category_codes,
			task_codes
		);
	}

	if (connectionsWithTasks.length === 0) {
		logger.warn(`No connections found for business ${businessID} matching the provided filters`);
		return { message: "No matching connections found", run_count: 0, tasks_created: [] };
	}

	/** Create score trigger and initialize completion tracking */
	let scoreTriggerId: UUID | undefined;
	try {
		const manager = new RerunTrackingManager();
		const result = await manager.initialize({ businessID: businessID as UUID, connectionsWithTasks });
		scoreTriggerId = result.scoreTriggerId;
	} catch (error) {
		logger.error({
			businessID,
			error: error instanceof Error ? error.message : String(error),
			stack: error instanceof Error ? error.stack : undefined,
			message: "[RERUN_DEBUG] Failed to create score trigger and initialize tracking — continuing without tracking"
		});
	}

	const combinedResult: ProcessTasksForConnectionResult = { tasksCreated: [], errors: [] };

	/** Process each connection */
	await Promise.all(
		connectionsWithTasks.map(async conn => {
			const result = await processTasksForConnection(businessID, conn, task_codes, metadata, scoreTriggerId);
			combinedResult.tasksCreated.push(...result.tasksCreated);
			combinedResult.errors.push(...result.errors);
		})
	);

	return {
		message: `Rerun completed. ${combinedResult.tasksCreated.length} task(s) processed`,
		run_count: combinedResult.tasksCreated.length,
		tasks_created: combinedResult.tasksCreated,
		errors: combinedResult.errors.length > 0 ? combinedResult.errors : undefined,
		score_trigger_id: scoreTriggerId
	};
};
